// ops/1-assets/1-templates/vue/movies-prod/v5/vue/frontend/src/components/blog/sidebar/FollowUs.vue
<template>
  <div class="widget">
    <h5 class="widget-title position-relative">{{ $t('form.follow_us') }} :</h5>
    <ul class="p-0 m-0 list-unstyled widget_social_media">
      <li class="">
        <a href="https://www.facebook.com/" class="position-relative"><i class="fab fa-facebook"></i></a>
      </li>
      {{
        ''
      }}
      <li class="">
        <a href="https://twitter.com/" class="position-relative"><i class="fab fa-twitter"></i></a>
      </li>
      {{
        ''
      }}
      <li class="">
        <a href="https://github.com/" class="position-relative"><i class="fab fa-github"></i></a>
      </li>
      {{
        ''
      }}
      <li class="">
        <a href="https://www.instagram.com/" class="position-relative"><i class="fab fa-instagram"></i></a>
      </li>
    </ul>
  </div>
</template>
<script setup></script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/components/blog/sidebar/FollowUs.jsx
import React, { Fragment, memo } from "react";

//react-router-dom
import { Link } from "react-router-dom";

// the hook
import { useTranslation } from "react-i18next";

const FollowUs = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <div className="widget">
        <h5 className="widget-title position-relative">
          {" "}
          {t("form.follow_us")}:
        </h5>
        <ul className="p-0 m-0 list-unstyled widget_social_media">
          <li>
            <Link to="https://www.facebook.com/" className="position-relative">
              <i className="fab fa-facebook"></i>
            </Link>
          </li>
          <li>
            <Link to="https://twitter.com/" className="position-relative">
              <i className="fab fa-twitter"></i>
            </Link>
          </li>
          <li>
            <Link to="https://github.com/" className="position-relative">
              <i className="fab fa-github"></i>
            </Link>
          </li>
          <li>
            <Link to="https://www.instagram.com/" className="position-relative">
              <i className="fab fa-instagram"></i>
            </Link>
          </li>
        </ul>
      </div>
    </Fragment>
  );
});

FollowUs.displayName = "FollowUs";
export default FollowUs;
