// ops/1-assets/1-app-templates/all/movies-prod/v5/vue/dashboard/src/components/custom/loader/LoaderComponent.vue
<template>
  <div id="loading">
    <div :class="`loader simple-loader ${!show ? 'd-none' : ''}`">
      <div class="loader-body">
        <img src="/assets/loader.gif" alt="loader" class="image-loader img-fluid" />
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    show: {
      type: Boolean,
      default: false,
    },
  },
};
</script>

<style lang="scss" scoped></style>

// ops/1-assets/1-app-templates/all/movies-prod/v5/next-js/src/components/Loader.tsx
import { Fragment, memo } from "react";

// Next-Image
import Image from "next/image";

// img
// import Loader from '/assets/images/loader.gif'
import LoaderImg from '../../public/assets/images/loader.gif'

const Loader = memo(() => {
  return (
    <Fragment>
      <div className="loader simple-loader animate__animated animate__fadeOut">
        <div className="loader-body">
          <Image
            src={LoaderImg}
            alt="loader"
            className="img-fluid"
            width="300"
          />
        </div>
      </div>
    </Fragment>
  );
});

Loader.displayName = "Loader";
export default Loader;
