// ops/1-assets/1-app-templates/all/movies-prod/v5/react/frontend/src/components/cards/CastCard.jsx
import React, { Fragment, memo } from "react";

//react-router-dom
import { Link } from "react-router-dom";

// the hook
import { useTranslation } from "react-i18next";

const CastCard = memo((props) => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <div className="iq-cast">
        <img src={props.image} alt={`cast-${props.title}`} loading="lazy" />
        <div className="card-img-overlay iq-cast-body">
          <h6 className="cast-title fw-500">
            <Link to="/cast-detail">{t(props.title)}</Link>
          </h6>
          <span className="cast-subtitle">{t(props.category)}</span>
        </div>
      </div>
    </Fragment>
  );
});

CastCard.displayName = "CastCard";
export default CastCard;

// ops/1-assets/1-app-templates/react/movies-prod/v5/nuxt-js/components/cards/CastCard.vue
<template>
  <img
    :src="image"
    :alt="`cast-${title}`"
    loading="lazy"
    class="img-fluid object-cover mb-4 rounded"
  />
  <div className="text-center">
    <h6 className="mb-0">
      <nuxt-link
        :to="{ name: 'cast-detail' }"
        class="font-size-14 text-decoration-none cast-title text-capitalize"
        >{{ title }}</nuxt-link
      >
    </h6>
    <nuxt-link
      to="#"
      className="font-size-14 text-decoration-none text-capitalize text-body"
      >{{ designation }}</nuxt-link
    >
  </div>
</template>

<script setup>
defineProps({
  title: { type: String, default: "" },
  image: { type: String, default: "" },
  designation: { type: String, default: "" },
});
</script>
