// ops/1-assets/1-app-templates/vue/movies-prod/v5/next-js/src/components/cards/EpisodeCard.tsx
import { FC, Fragment, memo } from "react";
import Link from 'next/link';

interface EpisodeCardProps {
  image: string;
  link: string;
  showEpisod: string;
  episodDate: string;
  episodTime: string;
  episodTitle: string;
}

const EpisodeCard: FC<EpisodeCardProps> = memo(({ image, link, showEpisod, episodDate, episodTime, episodTitle }) => {
  return (
    <Fragment>
      <div className="episode-block">
        <div className="block-image position-relative">
          <Link href={link}>
              <img
                src={image}
                className="img-fluid img-zoom"
                loading="lazy"
                alt=""
              />
          </Link>
          <div className="episode-number">{showEpisod}</div>
          <div className="episode-play">
            <Link href="/tv-shows/episode" tabIndex={0}>
              <i className="fa-solid fa-play"></i>
            </Link>
          </div>
        </div>
        <div className="epi-desc p-3">
          <div className="d-flex align-items-center justify-content-between mb-3">
            <span className="border-gredient-left text-white rel-date">
              {episodDate}
            </span>
            <span className="text-primary run-time">{episodTime}</span>
          </div>
          <Link href="/tv-shows/episode">
            <h5 className="epi-name text-white mb-0">{episodTitle}</h5>
          </Link>
        </div>
      </div>
    </Fragment>
  );
});

EpisodeCard.displayName = "EpisodeCard";
export default EpisodeCard;

// ops/1-assets/1-app-templates/react/movies-prod/v5/nuxt-js/components/cards/EpisodeCard.vue
<template>
  <div class="episode-block">
    <div class="block-image position-relative">
      <nuxt-link :to="{ name: link }">
        <img :src="image" class="img-fluid img-zoom" loading="lazy" />
      </nuxt-link>
      <div class="episode-number">{{ showEpisod }}</div>
      <div class="episode-play">
        <nuxt-link :to="{ name: 'tv-shows-episode' }" tabindex="0"
          ><i class="fa-solid fa-play"></i
        ></nuxt-link>
      </div>
    </div>
    <div class="epi-desc p-3">
      <div class="d-flex align-items-center justify-content-between mb-3">
        <span class="border-gredient-left text-white rel-date">{{
          episodDate
        }}</span>
        <span class="text-primary run-time">{{ episodTime }}</span>
      </div>
      <nuxt-link :to="{ name: 'tv-shows-episode' }">
        <h5 class="epi-name text-white mb-0">{{ episodTitle }}</h5>
      </nuxt-link>
    </div>
  </div>
</template>
<script setup>
defineProps({
  image: { type: String, default: "" },
  link: { type: String, default: "/" },
  showEpisod: { type: String, default: "" },
  episodDate: { type: String, default: "" },
  episodTime: { type: String, default: "" },
  episodTitle: { type: String, default: "" },
});
</script>
