// ops/1-assets/2-app-templates/all/movies-prod/v4/code-react/dashboard/src/views/backend/main/comment.js
import React from 'react'
import { Link } from 'react-router-dom'
import {Col,Row,Container,OverlayTrigger,Tooltip} from 'react-bootstrap'
import  Card  from '../../../components/Card'

const Comment = () => {
    return (
        <>
            <Container fluid>
               <Row>
                  <Col sm="12">
                     <Card>
                        <Card.Header className="d-flex justify-content-between">
                           <Card.Header.Title className="">
                              <h4 className="card-title">Comment Lists</h4>
                           </Card.Header.Title>
                        </Card.Header>
                        <Card.Body>
                           <div className="table-responsive">
                              <table className="data-tables table movie_table" style={{width:"100%"}}>
                                 <thead>
                                    <tr>
                                       <th style={{width: "10%"}}>No</th>
                                       <th style={{width: "20%"}}>Title</th>
                                       <th style={{width: "10%"}}>Author</th>
                                       <th style={{width: "25%"}}>Description</th>
                                       <th style={{width: "15%"}}>Created Date</th>
                                       <th style={{width: "10%"}}>Action</th>
                                    </tr>
                                 </thead>
                                 <tbody>
                                    <tr>
                                       <td>1</td>
                                       <td>
                                          Lorem ipsum dolor
                                       </td>
                                       <td>Nick Allen</td>
                                       <td>
                                          <p className="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet</p>
                                       </td>
                                       <td>
                                          21 Jul, 2020
                                       </td>                                       
                                       <td>
                                          <div className="flex align-items-center list-user-action">
                                                <OverlayTrigger placement="top"overlay={<Tooltip>View</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-warning" to="#"><i className="lar la-eye"></i></Link>                                                
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Edit</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-success" to="#"><i className="ri-pencil-line"></i></Link>
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Delete</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-primary" to="#"><i className="ri-delete-bin-line"></i></Link>
                                                </OverlayTrigger>
                                          </div>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td>2</td>
                                       <td>
                                          Lorem ipsum dolor
                                       </td>
                                       <td>Hans Olo</td>
                                       <td>
                                          <p className="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet</p>
                                       </td>
                                       <td>
                                          12 Jun, 2020
                                       </td>                                       
                                       <td>
                                          <div className="flex align-items-center list-user-action">
                                                <OverlayTrigger placement="top"overlay={<Tooltip>View</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-warning" to="#"><i className="lar la-eye"></i></Link>                                                
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Edit</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-success" to="#"><i className="ri-pencil-line"></i></Link>
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Delete</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-primary" to="#"><i className="ri-delete-bin-line"></i></Link>
                                                </OverlayTrigger>
                                          </div>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td>3</td>
                                       <td>
                                          Lorem ipsum dolor
                                       </td>
                                       <td>Lynn Guini</td>
                                       <td>
                                          <p className="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet</p>
                                       </td>
                                       <td>
                                          01 Jan, 2020
                                       </td>                                       
                                       <td>
                                            <div className="flex align-items-center list-user-action">
                                                <OverlayTrigger placement="top"overlay={<Tooltip>View</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-warning" to="#"><i className="lar la-eye"></i></Link>                                                
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Edit</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-success" to="#"><i className="ri-pencil-line"></i></Link>
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Delete</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-primary" to="#"><i className="ri-delete-bin-line"></i></Link>
                                                </OverlayTrigger>
                                            </div>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td>4</td>
                                       <td>
                                          Lorem ipsum dolor
                                       </td>
                                       <td>aaronottix</td>
                                       <td>
                                          <p className="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet</p>
                                       </td>
                                       <td>
                                          19 Mar, 2020
                                       </td>                                       
                                       <td>
                                          <div className="flex align-items-center list-user-action">
                                             <Link onClick={(e)=>e.preventDefault()} className="iq-bg-warning" data-toggle="tooltip" data-placement="top" title=""
                                             data-original-title="View" to="#"><i className="lar la-eye"></i></Link>
                                             <Link onClick={(e)=>e.preventDefault()} className="iq-bg-success" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit" to="#"><i
                                                   className="ri-pencil-line"></i></Link>
                                             <Link onClick={(e)=>e.preventDefault()} className="iq-bg-primary" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" to="#"><i
                                                   className="ri-delete-bin-line"></i></Link>
                                          </div>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td>5</td>
                                       <td>
                                          Lorem ipsum dolor
                                       </td>
                                       <td>Marge Arita</td>
                                       <td>
                                          <p className="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet</p>
                                       </td>
                                       <td>
                                          21 Aug, 2020
                                       </td>                                       
                                       <td>
                                            <div className="flex align-items-center list-user-action">
                                                <OverlayTrigger placement="top"overlay={<Tooltip>View</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-warning" to="#"><i className="lar la-eye"></i></Link>                                                
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Edit</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-success" to="#"><i className="ri-pencil-line"></i></Link>
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Delete</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-primary" to="#"><i className="ri-delete-bin-line"></i></Link>
                                                </OverlayTrigger>
                                            </div>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td>6</td>
                                       <td>
                                          Lorem ipsum dolor
                                       </td>
                                       <td>Bill Dabear</td>
                                       <td>
                                          <p className="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet</p>
                                       </td>
                                       <td>
                                          15 May, 2020
                                       </td>                                       
                                       <td>
                                            <div className="flex align-items-center list-user-action">
                                                <OverlayTrigger placement="top"overlay={<Tooltip>View</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-warning" to="#"><i className="lar la-eye"></i></Link>                                                
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Edit</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-success" to="#"><i className="ri-pencil-line"></i></Link>
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Delete</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-primary" to="#"><i className="ri-delete-bin-line"></i></Link>
                                                </OverlayTrigger>
                                            </div>
                                       </td>
                                    </tr>                                 
                                    <tr>
                                       <td>7</td>
                                       <td>
                                          Lorem ipsum dolor
                                       </td>
                                       <td>Brock Lee</td>
                                       <td>
                                          <p className="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet</p>
                                       </td>
                                       <td>
                                          07 Jul, 2020
                                       </td>                                       
                                       <td>
                                            <div className="flex align-items-center list-user-action">
                                                <OverlayTrigger placement="top"overlay={<Tooltip>View</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-warning" to="#"><i className="lar la-eye"></i></Link>                                                
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Edit</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-success" to="#"><i className="ri-pencil-line"></i></Link>
                                                </OverlayTrigger>
                                                <OverlayTrigger placement="top"overlay={<Tooltip>Delete</Tooltip>}>
                                                    <Link onClick={(e)=>e.preventDefault()} className="iq-bg-primary" to="#"><i className="ri-delete-bin-line"></i></Link>
                                                </OverlayTrigger>
                                            </div>
                                       </td>
                                    </tr>
                                 </tbody>
                              </table>
                           </div>
                        </Card.Body>
                     </Card>
                  </Col>
               </Row>
            </Container>
        </>
    )
}
export default Comment;

// ops/1-assets/2-app-templates/all/movies-prod/v4/code-vue/src/views/BackendPages/Comment.vue
<template>
  <b-container fluid>
    <b-row>
      <b-col sm="12">
          <div class="iq-card">
            <div class="iq-card-header d-flex justify-content-between">
                <div class="iq-header-title">
                  <h4 class="card-title">Comment Lists</h4>
                </div>
            </div>
            <div class="iq-card-body">
                <div class="table-responsive">
                  <table class="data-tables table movie_table" style="width:100%">
                      <thead>
                        <tr>
                            <th style="width: 10%;">No</th>
                            <th style="width: 20%;">Title</th>
                            <th style="width: 10%;">Author</th>
                            <th style="width: 25%;">Description</th>
                            <th style="width: 15%;">Created Date</th>
                            <th style="width: 10%;">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr v-for="(item,index) in comment" :key="index">
                            <td>{{item.no}}</td>
                            <td>
                              {{item.title}}
                            </td>
                            <td>{{item.author}}</td>
                            <td>
                              <p class="mb-0">{{item.desc}}</p>
                            </td>
                            <td>
                              {{item.date}}
                            </td>
                            <td>
                              <div class="flex align-items-center list-user-action">
                                  <a class="iq-bg-warning" v-b-tooltip:top title="View" href="#"><i class="lar la-eye"></i></a>
                                  <a class="iq-bg-success" v-b-tooltip:top title="Edit" href="#"><i class="ri-pencil-line"></i></a>
                                  <a class="iq-bg-primary" v-b-tooltip:top title="Delete" href="#"><i class="ri-delete-bin-line"></i></a>
                              </div>
                            </td>
                        </tr>
                      </tbody>
                  </table>
                </div>
            </div>
          </div>
      </b-col>
    </b-row>
  </b-container>
</template>
<script>
import { core } from '../../config/pluginInit'
export default {
  name: 'Comment',
  mounted () {
    core.index()
    core.initDataTable()
  },
  methods: {
  },
  data () {
    return {
      comment: [
        {
          no: '1',
          title: 'Lorem ipsum dolor',
          author: 'Nick Allen',
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet',
          date: '21 Jul, 2020'
        },
        {
          no: '2',
          title: 'Lorem ipsum dolor',
          author: 'Hans Olo',
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet',
          date: '12 Jun, 2020'
        },
        {
          no: '3',
          title: 'Lorem ipsum dolor',
          author: 'Lynn Guini',
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet',
          date: '01 Jan, 2020'
        },
        {
          no: '4',
          title: 'Lorem ipsum dolor',
          author: 'aaronottix',
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet',
          date: '19 Mar, 2020'
        },
        {
          no: '5',
          title: 'Lorem ipsum dolor',
          author: 'Marge Arita',
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet',
          date: '21 Aug, 2020'
        },
        {
          no: '6',
          title: 'Lorem ipsum dolor',
          author: 'Bill Dabear',
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet',
          date: '15 May, 2020'
        },
        {
          no: '7',
          title: 'Lorem ipsum dolor',
          author: 'Brock Lee',
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rhoncus non elit a scelerisque. Etiam feugiat luctus est, vel commodo odio rhoncus sit amet',
          date: '07 Jul, 2020'
        }
      ]
    }
  }
}
</script>
