// ops/1-assets/1-app-templates/react/movies-prod/v5/nuxt-js/components/sections/UpcomingMovies.vue
<template>
  <!-- Upcoming Movies start -->
  <SectionSlider
    :title="$t(title)"
    :list="topTen"
    :slides-per-view="6"
    class="upcomimg-block streamit-block"
  >
    <template #headerLink>
      <nuxt-link
        :to="{ name: 'view-all' }"
        class="text-primary iq-view-all text-decoration-none flex-none"
        >{{ $t("ott_home.view_all") }}</nuxt-link
      >
    </template>
    <template #default="{ data }">
      <card-style
        :image="data.image"
        :title="$t(data.title)"
        :movie-time="data.movieTime"
        :watchlist-link="{ name: 'play-list' }"
        :link="{ name: 'movies-detail' }"
      ></card-style>
    </template>
  </SectionSlider>
  <!-- Upcoming Movies end -->
</template>

<script setup>
import { ref } from "vue";

//components
import SectionSlider from "../slider/SectionSlider.vue";
import CardStyle from "../cards/CardStyle.vue";

//static data
import { upcommingMovie } from "../../StaticData/data";

const title = ref("home.upcoming_movies");
const topTen = ref(upcommingMovie);
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/components/sections/UpcomingMovies.jsx
import { Fragment, memo, useState } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../../components/cards/CardStyle";

//data
import { upcommingMovie } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const UpcomingMovies = memo((props) => {
  const { t } = useTranslation();
  const [upcommingMovie2] = useState(upcommingMovie);

  const upcoming = t(props.title) || t("home.upcoming_movies")

  return (
    <Fragment>
      <SectionSlider
        title={upcoming}
        list={upcommingMovie}
        className="upcomimg-block streamit-block"
        slidesPerView={props.slides}
        viewAll={props.viewAll}
        slideMedium={props.slideMedium}
        paddingY={props.paddingY}
      // loop={true}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

upcommingMovie.DisplayName = upcommingMovie;
export default UpcomingMovies;
