// ops/1-assets/1-app-templates/react/movies-prod/v5/vue/frontend/src/components/sections/UpcomingMovies.vue
<template>
  <!-- Upcoming Movies start -->
  <SectionSlider :title="$t(props.title)" :list="topTen" :slides-per-view="5" class="upcomimg-block streamit-block" :margin-padding="paddingTop ? 'px-3 pt-2 my-4' : 'px-3 my-4'">
    <template #headerLink>
      <router-link :to="{ name: 'landing-page.view-all' }" class="text-primary iq-view-all text-decoration-none flex-none">{{ props.view }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :movie-time="data.movieTime" :watchlist-link="{ path: '/playlist' }" :link="{ path: '/movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Upcoming Movies end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { upcommingMovie } from '../../StaticData/data';
const props = defineProps({
  title: { type: String, default: 'home.upcoming_movies' },
  view: { type: String, default: '' },
  paddingTop: { type: String, default: '' },
});

const topTen = ref(upcommingMovie);
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/components/sections/UpcomingMovies.jsx
import { Fragment, memo, useState } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../../components/cards/CardStyle";

//data
import { upcommingMovie } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const UpcomingMovies = memo((props) => {
  const { t } = useTranslation();
  const [upcommingMovie2] = useState(upcommingMovie);

  const upcoming = t(props.title) || t("home.upcoming_movies")

  return (
    <Fragment>
      <SectionSlider
        title={upcoming}
        list={upcommingMovie}
        className="upcomimg-block streamit-block"
        slidesPerView={props.slides}
        viewAll={props.viewAll}
        slideMedium={props.slideMedium}
        paddingY={props.paddingY}
      // loop={true}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

upcommingMovie.DisplayName = upcommingMovie;
export default UpcomingMovies;
