// ops/1-assets/1-templates/vue/movies-prod/v5/vue/frontend/src/views/MainPages/MoviesPage.vue
<template>
  <MovieHeroSlider></MovieHeroSlider>

  <PopularMovies></PopularMovies>

  <SpecialsLatestMovies></SpecialsLatestMovies>
  <section class="recommended-block">
    <MoviesRecommendedForYou :view="true ? $t('ott_home.view_all') : null" :slides-per-view="6"></MoviesRecommendedForYou>
  </section>
</template>
<script setup>
// Hero Slider
import MovieHeroSlider from '../../components/slider/MovieHeroSlider.vue';

// Sections
import PopularMovies from '../../components/sections/PopularMovies.vue';
import SpecialsLatestMovies from '../../components/sections/Specials&LatestMovies.vue';
import MoviesRecommendedForYou from '../../components/sections/MoviesRecommendedForYou.vue';
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/views/MainPages/MoviesPage.jsx
import { Fragment, memo } from "react";

// hero slider
import MovieHeroSlider from "../../components/slider/MovieHeroSlider";

// section
import PopularMovies from "../../components/sections/PopularMovies";
import SpecialsLatestMovies from "../../components/sections/Specials&LatestMovies";
import MoviesRecommendedForYou from "../../components/sections/MoviesRecommendedForYou";

const MoviesPage = memo(() => {
  return (
    <Fragment>
      <MovieHeroSlider />
      <PopularMovies showViewAllLink={true} paddingY="my-4" />
      <SpecialsLatestMovies paddingY="my-4" />
      <MoviesRecommendedForYou slides="6" paddingY="my-4" />
    </Fragment>
  );
});

MoviesPage.displayName = "MoviesPage";
export default MoviesPage;
