// ops/1-assets/1-app-templates/react/movies-prod/v5/nuxt-js/components/partials/FooterDefault.vue
<template>
  <footer class="footer footer-default">
    <div class="container-fluid">
      <div class="footer-top">
        <div class="row">
          <div class="col-xl-3 col-lg-6 mb-5 mb-lg-0">
            <div class="footer-logo">
              <BrandLogo></BrandLogo>
            </div>
            <p class="mb-4 font-size-14">
              {{ $t("footer.email_us") }}:
              <span class="text-white">customer@streamit.com</span>
            </p>
            <p class="text-uppercase letter-spacing-1 font-size-14 mb-1">
              {{ $t("footer.customer_services") }}
            </p>
            <p class="mb-0 contact text-white">+ (480) 555-0103</p>
          </div>
          <div class="col-xl-2 col-lg-6 mb-5 mb-lg-0">
            <h4 class="footer-link-title">{{ $t("footer.quick_links") }}</h4>
            <ul class="list-unstyled footer-menu">
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'extra-about-us' }">
                  {{ $t("header.about_us") }}
                </nuxt-link>
              </li>
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'blogs' }">
                  {{ $t("header.blog") }}
                </nuxt-link>
              </li>
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'pricing-plan' }">
                  {{ $t("header.pricing_plan") }}
                </nuxt-link>
              </li>
              <li>
                <nuxt-link class="ms-3" :to="{ name: 'extra-faq' }">
                  {{ $t("header.faq") }}
                </nuxt-link>
              </li>
            </ul>
          </div>
          <div class="col-xl-2 col-lg-6 mb-5 mb-lg-0">
            <h4 class="footer-link-title">
              {{ $t("footer.movies_to_watch") }}
            </h4>
            <ul class="list-unstyled footer-menu">
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'view-all' }">
                  {{ $t("footer.top_trending") }}</nuxt-link>
              </li>
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'view-all' }">
                  {{ $t("footer.recommended") }}
                </nuxt-link>
              </li>
              <li>
                <nuxt-link class="ms-3" :to="{ name: 'view-all' }">
                  {{ $t("footer.popular") }}
                </nuxt-link>
              </li>
            </ul>
          </div>
          <div class="col-xl-2 col-lg-6 mb-5 mb-lg-0">
            <h4 class="footer-link-title">{{ $t("footer.about_company") }}</h4>
            <ul class="list-unstyled footer-menu">
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'extra-contact-us' }">{{ $t("header.contact_us") }}
                </nuxt-link>
              </li>
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'extra-privacy-policy' }">
                  {{ $t("header.privacy_policy") }}
                </nuxt-link>
              </li>
              <li>
                <nuxt-link class="ms-3" :to="{ name: 'extra-terms-of-use' }">
                  {{ $t("footer.terms_of_use") }}
                </nuxt-link>
              </li>
            </ul>
          </div>
          <div class="col-xl-3 col-lg-6">
            <h4 class="footer-link-title">
              {{ $t("footer.subscribe_newsletter") }}
            </h4>
            <div class="mailchimp mailchimp-dark">
              <div class="input-group mb-3 mt-4">
                <input type="text" class="form-control mb-0 font-size-14" :placeholder="$t('footer.email')"
                  aria-describedby="button-addon2" />
                <div class="iq-button">
                  <button id="button-addon2" type="submit" class="btn btn-sm">
                    {{ $t("footer.subscribe") }}
                  </button>
                </div>
              </div>
            </div>
            <div class="d-flex align-items-center mt-5">
              <span class="font-size-14 me-2">{{
                $t("footer.follow_us")
              }}</span>
              <ul class="p-0 m-0 list-unstyled widget_social_media">
                <li class="">
                  <a href="https://www.facebook.com/" class="position-relative">
                    <i class="fab fa-facebook"></i>
                  </a>
                </li>
                {{
                  " "
                }}
                <li class="">
                  <a href="https://twitter.com/" class="position-relative">
                    <i class="fab fa-twitter"></i>
                  </a>
                </li>
                {{
                  " "
                }}
                <li class="">
                  <a href="https://github.com/" class="position-relative">
                    <i class="fab fa-github"></i>
                  </a>
                </li>
                {{
                  " "
                }}
                <li class="">
                  <a href="https://www.instagram.com/" class="position-relative">
                    <i class="fab fa-instagram"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-bottom border-top">
        <div class="row align-items-center">
          <div class="col-md-6">
            <ul class="menu list-inline p-0 d-flex flex-wrap align-items-center">
              <li class="menu-item">
                <nuxt-link :to="{ name: 'extra-terms-of-use' }">{{ $t("footer.terms_of_use") }}
                </nuxt-link>
              </li>
              <li id="menu-item-7316" class="menu-item">
                <nuxt-link :to="{ name: 'extra-privacy-policy' }">{{ $t("footer.privacy-policy") }}
                </nuxt-link>
              </li>
              <li class="menu-item">
                <nuxt-link :to="{ name: 'extra-faq' }">{{ $t("header.faq") }}
                </nuxt-link>
              </li>
              <li class="menu-item">
                <nuxt-link :to="{ name: 'play-list' }">{{ $t("footer.watch_list") }}
                </nuxt-link>
              </li>
            </ul>
            <p class="font-size-14">
              © <span class="currentYear">2024 </span>
              <span class="text-primary">STREAMIT</span>.{{ $t("footer.desc") }}
            </p>
          </div>
          <div class="col-md-3"></div>
          <div class="col-md-3">
            <h6 class="font-size-14 pb-1">
              {{ $t("footer.download_app") }}
            </h6>
            <div class="d-flex align-items-center">
              <a class="app-image" href="#">
                <img src="/assets/images/footer/google-play.webp" loading="lazy" alt="play-store" />
              </a>
              <br />
              <a class="ms-3 app-image" href="#">
                <img src="/assets/images/footer/apple.webp" loading="lazy" alt="app-store" />
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <div id="back-to-top" style="display: none" class="animate__animated" :class="animationClass" @click="scrollToTop">
    <a id="top" class="p-0 btn bg-primary btn-sm position-fixed top border-0 rounded-circle" href="#top">
      <i class="fa-solid fa-chevron-up"></i>
    </a>
  </div>
</template>
<script setup>
import { ref, watch, onMounted, onBeforeUnmount } from "vue";
import BrandLogo from "../brand/BrandLogo.vue";
import { useRoute } from "vue-router";

const animationClass = ref("animate__fadeIn");

const scrollToTop = () => {
  window.scrollTo({ top: 0, behavior: "smooth" });
};

const handleScroll = () => {
  if (document.documentElement.scrollTop > 250) {
    animationClass.value = "animate__fadeIn";
  } else {
    animationClass.value = "animate__fadeOut";
  }
};
handleScroll();
onBeforeUnmount(() => {
  window.removeEventListener("scroll", handleScroll);
});

onMounted(() => {
  window.addEventListener("scroll", handleScroll);
});

const route = useRoute();
watch(
  () => route.name,
  () => {
    scrollToTop();
  }
);
</script>

// ops/1-assets/1-app-templates/all/movies-prod/v5/next-js/src/components/partials/FooterDefault.tsx
import { memo, Fragment, useState, useEffect } from "react";

import Link from "next/link";

// react-bootstrap
import { Container, Row, Col } from "react-bootstrap";



// components
import Logo from "../logo";


const FooterMega = memo(() => {
  const [animationClass, setAnimationClass] = useState("animate__fadeIn");
  // const location = useLocation();

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handleScroll = () => {
    if (document.documentElement.scrollTop > 250) {
      setAnimationClass("animate__fadeIn");
    } else {
      setAnimationClass("animate__fadeOut");
    }
  };

  useEffect(() => {
    handleScroll();
    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  // useEffect(() => {
  //   scrollToTop();
  // }, [location.pathname]);
  return (
    <>
      <Fragment>
        <footer className="footer footer-default">
          <Container fluid>
            <div className="footer-top">
              <Row>
                <Col xl={3} lg={6} className="mb-5 mb-lg-0">
                  <div className="footer-logo">
                    <Logo></Logo>
                  </div>
                  <p className="mb-4 font-size-14">
                    Email us:{" "}
                    <span className="text-white">customer@streamit.com</span>
                  </p>
                  <p className="text-uppercase letter-spacing-1 font-size-14 mb-1">
                    customer services
                  </p>
                  <p className="mb-0 contact text-white">+ (480) 555-0103</p>
                </Col>
                <Col xl={2} lg={6} className="mb-5 mb-lg-0">
                  <h4 className="footer-link-title">Quick Links</h4>
                  <ul className="list-unstyled footer-menu">
                    <li className="mb-3">
                      <Link href="/extra/about-us" className="ms-3">
                        about us
                      </Link>
                    </li>
                    <li className="mb-3">
                      <Link href="/blogs" className="ms-3">
                        Blog
                      </Link>
                    </li>
                    <li className="mb-3">
                      <Link href="/extra/pricing-plan" className="ms-3">
                        Pricing Plan
                      </Link>
                    </li>
                    <li>
                      <Link href="/extra/faq" className="ms-3">
                        FAQ
                      </Link>
                    </li>
                  </ul>
                </Col>
                <Col xl={2} lg={6} className="mb-5 mb-lg-0">
                  <h4 className="footer-link-title">Movies to watch</h4>
                  <ul className="list-unstyled footer-menu">
                    <li className="mb-3">
                      <Link href="/view-all" className="ms-3">
                        Top trending
                      </Link>
                    </li>
                    <li className="mb-3">
                      <Link href="/view-all" className="ms-3">
                        Recommended
                      </Link>
                    </li>
                    <li>
                      <Link href="/view-all" className="ms-3">
                        Popular
                      </Link>
                    </li>
                  </ul>
                </Col>
                <Col xl={2} lg={6} className="mb-5 mb-lg-0">
                  <h4 className="footer-link-title">About company</h4>
                  <ul className="list-unstyled footer-menu">
                    <li className="mb-3">
                      <Link href="/extra/contact-us" className="ms-3">
                        contact us
                      </Link>
                    </li>
                    <li className="mb-3">
                      <Link href="/extra/privacy-policy" className="ms-3">
                        privacy policy
                      </Link>
                    </li>
                    <li>
                      <Link href="/extra/terms-of-use" className="ms-3">
                        Terms of use
                      </Link>
                    </li>
                  </ul>
                </Col>
                <Col xl={3} lg={6}>
                  <h4 className="footer-link-title">Subscribe Newsletter</h4>
                  <div className="mailchimp mailchimp-dark">
                    <div className="input-group mb-3 mt-4">
                      <input
                        type="text"
                        className="form-control mb-0 font-size-14"
                        placeholder="Email*"
                        aria-describedby="button-addon2"
                      />
                      <div className="iq-button">
                        <button
                          type="submit"
                          className="btn btn-sm"
                          id="button-addon2"
                        >
                          Subscribe
                        </button>
                      </div>
                    </div>
                  </div>
                  <div className="d-flex align-items-center mt-5">
                    <span className="font-size-14 me-2">Follow Us:</span>
                    <ul className="p-0 m-0 list-unstyled widget_social_media">
                      <li className="">
                        <Link
                          href="https://www.facebook.com/"
                          className="position-relative"
                        >
                          <i className="fab fa-facebook"></i>
                        </Link>
                      </li>
                      <li className="">
                        <Link
                          href="https://twitter.com/"
                          className="position-relative"
                        >
                          <i className="fab fa-twitter"></i>
                        </Link>
                      </li>
                      <li className="">
                        <Link
                          href="https://github.com/"
                          className="position-relative"
                        >
                          <i className="fab fa-github"></i>
                        </Link>
                      </li>
                      <li className="">
                        <Link
                          href="https://www.instagram.com/"
                          className="position-relative"
                        >
                          <i className="fab fa-instagram"></i>
                        </Link>
                      </li>
                    </ul>
                  </div>
                </Col>
              </Row>
            </div>
            <div className="footer-bottom border-top">
              <Row className="align-items-center">
                <Col md={6}>
                  <ul className="menu list-inline p-0 d-flex flex-wrap align-items-center">
                    <li className="menu-item">
                      <Link href="/extra/terms-of-use"> Terms Of Use </Link>
                    </li>
                    <li id="menu-item-7316" className="menu-item">
                      <Link href="/extra/privacy-policy"> Privacy-Policy </Link>
                    </li>
                    <li className="menu-item">
                      <Link href="/faq"> FAQ </Link>
                    </li>
                    <li className="menu-item">
                      <Link href="/play-list"> Watch List </Link>
                    </li>
                  </ul>
                  <p className="font-size-14">
                    © <span className="currentYear">2023</span>{" "}
                    <span className="text-primary">STREAMIT</span>. All Rights
                    Reserved. All videos and shows on this platform are
                    trademarks of, and all related images and content are the
                    property of, Streamit Inc. Duplication and copy of this is
                    strictly prohibited. All rights reserved.
                  </p>
                </Col>
                <Col md={3}></Col>
                <Col md={3}>
                  <h6 className="font-size-14 pb-1">Download Streamit Apps</h6>
                  <div className="d-flex align-items-center">
                    <Link className="app-image" href="#">
                      <img src="/assets/images/footer/google-play.webp" loading="lazy" alt="play-store" />
                    </Link>
                    <br />
                    <Link className="ms-3 app-image" href="#">
                      <img src="/assets/images/footer/apple.webp" loading="lazy" alt="app-store" />
                    </Link>
                  </div>
                </Col>
              </Row>
            </div>
          </Container>
        </footer>
        <div
          id="back-to-top"
          style={{ display: "none" }}
          className={`animate__animated ${animationClass}`}
          onClick={scrollToTop}
        >
          <Link
            className="p-0 btn bg-primary btn-sm position-fixed top border-0 rounded-circle"
            id="top"
            href="#top"
          >
            <i className="fa-solid fa-chevron-up"></i>
          </Link>
        </div>
      </Fragment>
    </>
  );
});
FooterMega.displayName = "FooterMega";
export default FooterMega;
