// ops/1-assets/2-app-templates/all/movies-prod/v5/vue/frontend/src/views/Cast/ListPage.vue
<template>
  <section class="section-padding">
    <div class="container-fluid">
      <b-row class="row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 row-cols-xl-6">
        <b-col v-for="data in cast.slice(0, 12)" :key="data">
          <card-cast-grid :title="data.title" :designation="data.designation" :image="data.profile_image"></card-cast-grid>
        </b-col>
      </b-row>
      <div class="text-center">
        <div class="iq-button">
          <a href="javascript:void(0)" class="btn text-uppercase position-relative">
            <span class="button-text">{{ $t('ott_home.load_more') }}</span>
            {{ ' ' }}
            <i class="fa-solid fa-play"></i>
          </a>
        </div>
      </div>
    </div>
  </section>
</template>
<script setup>
import CardCastGrid from '../../components/cards/CardCastGrid.vue';
import { cast } from '../../StaticData/data';
</script>

// ops/1-assets/1-app-templates/all/movies-prod/v5/react/frontend/src/views/Cast/ListPage.jsx
import React, { Fragment, memo } from "react";

// react-bootstrap
import { Container, Row, Col } from "react-bootstrap";

//react-router-dom
import { Link } from "react-router-dom";

// components
import BreadcrumbWidget from "../../components/BreadcrumbWidget";
import CastCard from "../../components/cards/CastCard";

// data
import { cast } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

export const ListPage = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <BreadcrumbWidget title={t("header.cast")} />
      <section className="section-padding">
        <Container fluid>
          <Row className="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 row-cols-xl-6">
            {cast.map((item, index) => (
              <Col key={index}>
                <CastCard
                  title={t(item.title)}
                  category={item.designation}
                  image={item.profile_image}
                />
              </Col>
            ))}
          </Row>
          <div className="text-center">
            <div className="iq-button">
              <Link to="#" className="btn text-uppercase position-relative">
                <span className="button-text">{t("ott_home.load_more")}</span>{" "}
                <i className="fa-solid fa-play"></i>
              </Link>
            </div>
          </div>
        </Container>
      </section>
    </Fragment>
  );
});

ListPage.displayName = "ListPage";
export default ListPage;
