// ops/1-assets/1-app-templates/react/movies-prod/v5/vue/frontend/src/components/cards/TopTenCard.vue
<template>
  <div :class="`${classlist}`">
    <div class="block-image position-relative">
      <div class="img-box">
        <router-link class="overly-images" :to="link">
          <img :src="imagePath" alt="movie-card" class="img-fluid object-cover" loading="lazy" />
        </router-link>
        <span class="top-ten-numbers texture-text">{{ countValue }}</span>
      </div>
    </div>
  </div>
</template>
<script setup>
defineProps({
  imagePath: { type: String, default: '' },
  countValue: { type: Number, default: 0 },
  link: { type: [String, Object], default: () => '/' },
  classlist: { type: String, default: '' },
});
</script>

// ops/1-assets/1-templates/vue/movies-prod/v5/react/frontend/src/components/cards/TopTenCard.jsx
import { Fragment, memo } from "react";

//react-router-dom
import { Link } from "react-router-dom";

const TopTenCard = memo((props) => {
  return (
   <Fragment>
    <div className="iq-top-ten-block">
      <div className="block-image position-relative">
        <div className="img-box">
          <Link className="overly-images" to={props.link}>
            <img
              src={props.imagePath}
              alt="movie-card"
              className="img-fluid object-cover"
            />
          </Link>
          <span className="top-ten-numbers texture-text">{props.countValue}</span>
        </div>
      </div>
    </div>
   </Fragment> 
  );
});

TopTenCard.displayName = "TopTenCard";
export default TopTenCard;
