// ops/1-assets/1-templates/react/bootstrap-movies-prod/v5/nuxt-js/components/slider/VerticalSectionSlider.vue
<template>
  <div class="verticle-slider section-padding-bottom">
    <div class="slider">
      <div class="slider-flex position-relative">
        <div class="slider--col position-relative">
          <div
            class="vertical-slider-prev swiper-button"
            tabindex="0"
            role="button"
            aria-label="Previous slide"
            aria-controls="swiper-wrapper-b130b4e10e1468117"
          >
            <i class="iconly-Arrow-Up-2 icli"></i>
          </div>
          <div class="slider-thumbs" data-swiper="slider-thumbs">
            <div class="swiper-container" data-swiper="slider-thumbs-inner">
              <swiper
                v-if="render"
                :dir="rtl"
                :space-between="24"
                :slides-per-view="3"
                :navigation="{
                  nextEl: '.vertical-slider-next',
                  prevEl: '.vertical-slider-prev',
                }"
                :loop="true"
                :thumbs="{ swiper: thumbsSwiper }"
                :watch-slides-progress="true"
                :modules="modules"
                :direction="'vertical'"
                class="swiper-wrapper top-ten-slider-nav"
              >
                <SwiperSlide
                  v-for="data in sliderData"
                  :key="data"
                  tag="li"
                  class="swiper-slide swiper-bg"
                >
                  <div class="block-images position-relative">
                    <div class="img-box slider--image">
                      <img
                        :src="data.image"
                        class="img-fluid"
                        alt=""
                        loading="lazy"
                      />
                    </div>
                    <div class="block-description">
                      <h6 class="iq-title">
                        <nuxt-link :to="{ name: 'tv-shows-detail' }">{{
                          $t(data.title)
                        }}</nuxt-link>
                      </h6>
                      <div class="movie-time d-flex align-items-center my-2">
                        <span class="text-body">{{ data.movieTime }}</span>
                      </div>
                    </div>
                  </div>
                </SwiperSlide>
              </swiper>
              <div class="slider-next btn-verticle">
                <i class="ri-arrow-down-s-line vertical-aerrow"></i>
              </div>
            </div>
          </div>
          <div
            class="vertical-slider-next swiper-button"
            tabindex="0"
            role="button"
            aria-label="Next slide"
            aria-controls="swiper-wrapper-b130b4e10e1468117"
          >
            <i class="iconly-Arrow-Down-2 icli"></i>
          </div>
        </div>
        <div class="slider-images" data-swiper="slider-images">
          <swiper
            :loop="true"
            :space-between="10"
            :modules="modules"
            effect="fade"
            class="swiper-container"
            @swiper="setThumbsSwiper"
          >
            <SwiperSlide
              v-for="data in sliderData"
              :key="data"
              tag="li"
              class="swiper-slide"
            >
              <div class="slider--image block-images">
                <img :src="data.image" loading="lazy" alt="" />
              </div>
              <div class="description">
                <div class="block-description">
                  <ul
                    class="ps-0 mb-0 mb-1 pb-1 list-inline d-flex flex-wrap align-items-center movie-tag"
                  >
                    <li
                      class="position-relative text-capitalize font-size-14 letter-spacing-1"
                    >
                      <nuxt-link
                        :to="{ name: 'movies-detail' }"
                        class="text-white text-decoration-none"
                        >{{ $t("home.comedy") }}</nuxt-link
                      >
                    </li>
                    <li
                      class="position-relative text-capitalize font-size-14 letter-spacing-1"
                    >
                      <nuxt-link
                        :to="{ name: 'movies-detail' }"
                        class="text-white text-decoration-none"
                        >{{ $t("home.romance") }}</nuxt-link
                      >
                    </li>
                    <li
                      class="position-relative text-capitalize font-size-14 letter-spacing-1"
                    >
                      <nuxt-link
                        :to="{ name: 'movies-detail' }"
                        class="text-white text-decoration-none"
                        >{{ $t("home.action") }}</nuxt-link
                      >
                    </li>
                  </ul>
                  <h2 class="iq-title mb-3">
                    <nuxt-link :to="{ name: 'movies-detail' }">{{
                      $t(data.title)
                    }}</nuxt-link>
                  </h2>
                  <div class="d-flex align-items-center gap-3 mb-3">
                    <div class="slider-ratting d-flex align-items-center">
                      <ul
                        class="ratting-start p-0 m-0 list-inline text-warning d-flex align-items-center justify-content-left"
                      >
                        <li>
                          <i class="fa fa-star" aria-hidden="true"></i>
                        </li>
                      </ul>
                      <span class="text-white ms-2 font-size-14 fw-500"
                        >4.3/5</span
                      >
                    </div>
                    <span class="text-body">{{ data.movieTime }}</span>
                  </div>
                  <p class="mt-0 mb-3 line-count-2">
                    {{ $t(`ott_home.content_here`) }}
                  </p>
                  <div class="iq-button">
                    <nuxt-link
                      :to="{ name: 'movies-detail' }"
                      class="btn text-uppercase position-relative"
                    >
                      <span class="button-text">{{
                        $t(`ott_home.play_now`)
                      }}</span>
                      <i class="fa-solid fa-play"></i>
                    </nuxt-link>
                  </div>
                </div>
              </div>
            </SwiperSlide>
          </swiper>
        </div>
      </div>
    </div>
  </div>
</template>
<script setup>
import { Swiper, SwiperSlide } from "swiper/vue";

import { Navigation, Pagination, Thumbs, EffectFade } from "swiper";
import { ref, computed, watch } from "vue";
import { useSetting } from "../../store/setting/index";
const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);
const render = ref(true);
watch(
  () => rtl.value,
  () => {
    render.value = false;
    setTimeout(() => {
      render.value = true;
    }, 0);
  }
);

defineProps({
  sliderData: { type: Array, default: () => [] },
});

const modules = [Navigation, Pagination, Thumbs, EffectFade];

const thumbsSwiper = ref(null);

const setThumbsSwiper = (swiper) => {
  thumbsSwiper.value = swiper;
};
</script>

<style>
.swiper-button-lock {
  display: block;
}
</style>

// ops/1-assets/1-app-templates/react/movies-prod/v5/react/frontend/src/components/slider/VerticalSectionSlider.jsx
import { Fragment, memo, useEffect, useState } from "react";

//react-router-dom
import { Link } from "react-router-dom";

//swiper
import { Swiper, SwiperSlide } from "swiper/react";
import { FreeMode, Navigation, Thumbs } from "swiper";

// the hook
import { useTranslation } from "react-i18next";
import { useSelector } from "react-redux";
import { theme_scheme_direction } from "../../store/setting/selectors";

const VerticalSectionSlider = memo(({ sliderData, containerFluid }) => {
  const { t } = useTranslation();
  const [thumbsSwiper, setThumbsSwiper] = useState(null);


  const themeSchemeDirection = useSelector(theme_scheme_direction);

  return (
    <Fragment>
      <div className="verticle-slider section-padding-bottom">
        <div className={containerFluid}>
          <div className="slider">
            <div className="slider-flex position-relative">
              <div className="slider--col position-relative">
                <div className="vertical-slider-prev swiper-button"><i className="iconly-Arrow-Up-2 icli"></i></div>
                <div className="slider-thumbs" data-swiper="slider-thumbs">
                  <div
                    className="swiper-container"
                    data-swiper="slider-thumbs-inner"
                  >
                    <Swiper
                      spaceBetween={24}
                      slidesPerView={3}
                      dir={themeSchemeDirection}
                      navigation={{
                        nextEl: ".vertical-slider-next",
                        prevEl: ".vertical-slider-prev",
                      }}
                      loop={true}
                      watchSlidesProgress={true}
                      modules={[FreeMode, Navigation, Thumbs]}
                      thumbs={{
                        swiper:
                          thumbsSwiper && !thumbsSwiper.destroyed
                            ? thumbsSwiper
                            : null,
                      }}
                      direction="vertical"
                      className="swiper-wrapper top-ten-slider-nav"
                    >
                      {sliderData.map((data) => (
                        <SwiperSlide
                          key={data.title + "tranding-thumb"}
                          tag="li"
                          className="swiper-slide swiper-bg"
                        >
                          <div className="block-images position-relative">
                            <div className="img-box slider--image">
                              <img
                                src={data.image}
                                className="img-fluid"
                                alt=""
                                loading="lazy"
                              />
                            </div>
                            <div className="block-description">
                              <h6 className="iq-title">
                                <Link to="/shows-details">{t(data.title)}</Link>
                              </h6>
                              <div className="movie-time d-flex align-items-center my-2">
                                <span className="text-body">
                                  {data.movieTime}
                                </span>
                              </div>
                            </div>
                          </div>
                        </SwiperSlide>
                      ))}
                    </Swiper>
                    <div className="slider-next btn-verticle">
                      <i className="ri-arrow-down-s-line vertical-aerrow"></i>
                    </div>
                  </div>
                </div>
                <div
                  className="vertical-slider-next swiper-button"
                  tabIndex="0"
                  role="button"
                  aria-label="Next slide"
                  aria-controls="swiper-wrapper-b130b4e10e1468117"
                >
                  <i className="iconly-Arrow-Down-2 icli"></i>
                </div>
              </div>
              <div className="slider-images" data-swiper="slider-images">
                <Swiper
                  dir={themeSchemeDirection}
                  spaceBetween={10}
                  modules={[FreeMode, Navigation, Thumbs]}
                  effect="fade"
                  className="swiper-container responsive-swiper-vertical"
                  loop={true}
                  watchSlidesProgress={true}
                  onSwiper={setThumbsSwiper}
                  breakpoints={{
                    675:{
                      direction: "horizontal"
                    },
                    1025:{
                      direction: "vertical"
                    }
                  }}
                >
                  {sliderData.map((data) => (
                    <SwiperSlide
                      key={data.title + "tranding-main"}
                      tag="li"
                      className="swiper-slide"
                    >
                      <div className="slider--image block-images">
                        <img src={data.image} loading="lazy" alt="" />
                      </div>
                      <div className="description">
                        <div className="block-description">
                          <ul className="ps-0 mb-0 mb-1 pb-1 list-inline d-flex flex-wrap align-items-center movie-tag">
                            <li className="position-relative text-capitalize font-size-14 letter-spacing-1">
                              <Link
                                to="/view-all"
                                className="text-white text-decoration-none"
                              >
                                {t("home.comedy")}
                              </Link>
                            </li>
                            <li className="position-relative text-capitalize font-size-14 letter-spacing-1">
                              <Link
                                to="/view-all"
                                className="text-white text-decoration-none"
                              >
                                {t("home.romance")}
                              </Link>
                            </li>
                            <li className="position-relative text-capitalize font-size-14 letter-spacing-1">
                              <Link
                                to="/view-all"
                                className="text-white text-decoration-none"
                              >
                                {t("home.action")}
                              </Link>
                            </li>
                          </ul>
                          <h2 className="iq-title mb-3">
                            <Link to="/shows-details">{t(data.title)}</Link>
                          </h2>
                          <div className="d-flex align-items-center gap-3 mb-3">
                            <div className="slider-ratting d-flex align-items-center">
                              <ul className="ratting-start p-0 m-0 list-inline text-warning d-flex align-items-center justify-content-left">
                                <li>
                                  <i
                                    className="fa fa-star"
                                    aria-hidden="true"
                                  ></i>
                                </li>
                              </ul>
                              <span className="text-white ms-2 font-size-14 fw-500">
                                4.3/5
                              </span>
                            </div>
                            <span className="text-body">{data.movieTime}</span>
                          </div>
                          <p className="mt-0 mb-3 line-count-2">
                            {t("ott_home.content_here")}
                          </p>
                          <div className="iq-button">
                            <Link
                              to="/movies-detail"
                              className="btn text-uppercase position-relative"
                            >
                              <span className="button-text">
                                {t("ott_home.play_now")}
                              </span>
                              <i className="fa-solid fa-play"></i>
                            </Link>
                          </div>
                        </div>
                      </div>
                    </SwiperSlide>
                  ))}
                </Swiper>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Fragment>
  );
});

VerticalSectionSlider.displayName = "VerticalSectionSlider";
export default VerticalSectionSlider;
