// ops/1-assets/2-app-templates/all/movies-prod/v5/vue/frontend/src/components/slider/OttHeroSlider.vue
<template>
  <div class="iq-banner-thumb-slider">
    <div class="slider">
      <div class="position-relative slider-bg d-flex justify-content-end">
        <div class="position-relative my-auto">
          <div class="horizontal_thumb_slider" data-swiper="slider-thumbs-ott">
            <div class="banner-thumb-slider-nav">
              <Swiper
                v-if="render"
                :dir="rtl"
                :slides-per-view="2"
                :navigation="{
                  prevEl: '.slider-prev',
                  nextEl: '.slider-next',
                }"
                class="swiper-horizontal swiper-container m-0"
                :space-between="24"
                :modules="modules"
                :loop="true"
                :looped-slides="8"
                :thumbs="{ swiper: thumbsSwiper }">
                <SwiperSlide class="swiper-bg">
                  <div class="block-images position-relative">
                    <div class="img-box">
                      <img src="/assets/images/movies/ott1.webp" class="img-fluid" alt="" loading="lazy" />
                      <div class="block-description">
                        <h6 class="iq-title fw-500 mb-0">{{ $t('ott_home.the_hunter') }}</h6>
                        <span class="fs-12">2 {{ $t('ott_home.hr') }} 6 {{ $t('countdown.minute') }}</span>
                      </div>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide class="swiper-bg">
                  <div class="block-images position-relative">
                    <div class="img-box">
                      <img src="/assets/images/movies/ott2.webp" class="img-fluid" alt="" loading="lazy" />
                      <div class="block-description">
                        <h6 class="iq-title fw-500 mb-0">{{ $t('ott_home.the_mandalorian') }}</h6>
                        <span class="fs-12">2 {{ $t('ott_home.hr') }} 14 {{ $t('countdown.minute') }}</span>
                      </div>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide class="swiper-bg">
                  <div class="block-images position-relative">
                    <div class="img-box">
                      <img src="/assets/images/movies/ott3.webp" class="img-fluid" alt="" loading="lazy" />
                      <div class="block-description">
                        <h6 class="iq-title fw-500 mb-0">{{ $t('ott_home.better_call_saul') }}</h6>
                        <span class="fs-12">2 {{ $t('ott_home.hr') }} 55 {{ $t('countdown.minute') }}</span>
                      </div>
                    </div>
                  </div>
                </SwiperSlide>
              </Swiper>
              <div class="slider-prev swiper-button">
                <i class="iconly-Arrow-Left-2 icli"></i>
              </div>
              <div class="slider-next swiper-button">
                <i class="iconly-Arrow-Right-2 icli"></i>
              </div>
            </div>
          </div>
        </div>
        <div class="slider-images" data-swiper="slider-images-ott">
          <Swiper v-if="render" class="swiper-container" :dir="rtl" :loop="true" :space-between="0" :slides-per-view="1" :looped-slides="8" :effect="'fade'" :modules="modules" @swiper="setThumbsSwiper">
            <SwiperSlide class="p-0">
              <div class="slider--image block-images">
                <img src="/assets/images/movies/ott1.webp" loading="lazy" alt="banner" />
              </div>
              <div class="description">
                <div class="row align-items-center h-100">
                  <div class="col-lg-6 col-md-12">
                    <div class="slider-content">
                      <div class="d-flex align-items-center RightAnimate mb-3">
                        <span class="badge rounded-0 text-dark text-uppercase px-3 py-2 me-3 bg-white mr-3">Pg</span>
                        <ul class="p-0 mb-0 list-inline d-flex flex-wrap align-items-center movie-tag">
                          <li class="position-relative text-capitalize font-size-14 letter-spacing-1">
                            <router-link to="" class="text-decoration-none">{{ $t('ott_home.adventure') }}</router-link>
                          </li>
                          <li class="position-relative text-capitalize font-size-14 letter-spacing-1">
                            <router-link to="" class="text-decoration-none">{{ $t('ott_home.thriller') }}</router-link>
                          </li>
                          <li class="position-relative text-capitalize font-size-14 letter-spacing-1">
                            <router-link to="" class="text-decoration-none">{{ $t('ott_home.drama') }}</router-link>
                          </li>
                        </ul>
                      </div>
                      <h1 class="texture-text big-font letter-spacing-1 line-count-1 text-capitalize RightAnimate-two">
                        {{ $t('ott_home.the_hunter') }}
                      </h1>
                      <p class="line-count-3 RightAnimate-two">{{ $t('ott_home.after_death') }}</p>
                      <div class="d-flex flex-wrap align-items-center gap-3 RightAnimate-three">
                        <div class="slider-ratting d-flex align-items-center">
                          <ul class="ratting-start p-0 m-0 list-inline text-warning d-flex align-items-center justify-content-left">
                            <li>
                              <i class="fa fa-star" aria-hidden="true"></i>
                            </li>
                          </ul>
                          <span class="text-white ms-2 font-size-14 fw-500">4.3/5</span>
                          <span class="ms-2">
                            <img src="/assets/images/movies/imdb-logo.svg" alt="imdb logo" class="img-fluid" loading="lazy" />
                          </span>
                        </div>
                        <span class="font-size-14 fw-500 text-capitalize">2 {{ $t('ott_home.hr') }} : 6 {{ $t('ott_home.mins') }}</span>
                        <div class="text-primary font-size-14 fw-500 text-capitalize">
                          {{ $t('ott_home.genres') }}: <router-link :to="{ name: 'landing-page.view-all' }" class="text-decoration-none ms-1">{{ $t('ott_home.drama') }}</router-link>
                        </div>
                        <div class="text-primary font-size-14 fw-500 text-capitalize">
                          {{ $t('ott_home.starting') }}: <router-link to="" class="text-decoration-none ms-1">{{ $t('ott_home.jeffrey_silver') }}</router-link>
                        </div>
                      </div>
                    </div>
                    <custom-button :button-title="$t('ott_home.stream_now')" :link="{ path: '/movies-detail' }"></custom-button>
                  </div>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide class="p-0">
              <div class="slider--image block-images">
                <img src="/assets/images/movies/ott2.webp" loading="lazy" alt="banner" />
              </div>
              <div class="description">
                <div class="row align-items-center h-100">
                  <div class="col-lg-6 col-md-12">
                    <div class="slider-content">
                      <div class="d-flex align-items-center RightAnimate mb-3">
                        <span class="badge rounded-0 text-dark text-uppercase px-3 py-2 me-3 bg-white mr-3">NC-17</span>
                        <ul class="p-0 mb-0 list-inline d-flex flex-wrap align-items-center movie-tag">
                          <li class="position-relative text-capitalize font-size-14 letter-spacing-1">
                            <router-link to="" class="text-decoration-none">{{ $t('ott_home.animation') }}</router-link>
                          </li>
                          <li class="position-relative text-capitalize font-size-14 letter-spacing-1">
                            <router-link to="" class="text-decoration-none">{{ $t('ott_home.sci_fi') }}</router-link>
                          </li>
                          <li class="position-relative text-capitalize font-size-14 letter-spacing-1">
                            <router-link to="" class="text-decoration-none">{{ $t('ott_home.action') }}</router-link>
                          </li>
                        </ul>
                      </div>
                      <h1 class="texture-text big-font letter-spacing-1 line-count-1 text-capitalize RightAnimate-two">
                        {{ $t('ott_home.the_mandalorian') }}
                      </h1>
                      <p class="line-count-3 RightAnimate-two">{{ $t('ott_home.after_galactic') }}</p>
                      <div class="d-flex flex-wrap align-items-center gap-3 RightAnimate-three">
                        <div class="slider-ratting d-flex align-items-center">
                          <ul class="ratting-start p-0 m-0 list-inline text-warning d-flex align-items-center justify-content-left">
                            <li>
                              <i class="fa fa-star" aria-hidden="true"></i>
                            </li>
                          </ul>
                          <span class="text-white ms-2 font-size-14 fw-500">4.3/5</span>
                        </div>
                        <span class="font-size-14 fw-500 text-capitalize">2 {{ $t('ott_home.hr') }} : 14 {{ $t('ott_home.mins') }}</span>
                        <div class="text-primary font-size-14 fw-500 text-capitalize">
                          {{ $t('ott_home.genres') }}: <router-link :to="{ name: 'landing-page.view-all' }" class="text-decoration-none ms-1">{{ $t('ott_home.sci_fi') }}</router-link>
                        </div>
                        <div class="text-primary font-size-14 fw-500 text-capitalize">
                          {{ $t('ott_home.starting') }}: <router-link to="" class="text-decoration-none ms-1">{{ $t('ott_home.james_chinlund') }}</router-link>
                        </div>
                      </div>
                    </div>
                    <custom-button :button-title="$t('ott_home.stream_now')" :link="{ path: '/movies-detail' }"></custom-button>
                  </div>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide class="p-0">
              <div class="slider--image block-images">
                <img src="/assets/images/movies/ott3.webp" loading="lazy" alt="banner" />
              </div>
              <div class="description">
                <div class="row align-items-center h-100">
                  <div class="col-lg-6 col-md-12">
                    <div class="slider-content">
                      <div class="d-flex align-items-center RightAnimate mb-3">
                        <span class="badge rounded-0 text-dark text-uppercase px-3 py-2 me-3 bg-white mr-3">G</span>
                        <ul class="p-0 mb-0 list-inline d-flex flex-wrap align-items-center movie-tag">
                          <li class="position-relative text-capitalize font-size-14 letter-spacing-1">
                            <router-link to="" class="text-decoration-none">{{ $t('ott_home.history') }}</router-link>
                          </li>
                          <li class="position-relative text-capitalize font-size-14 letter-spacing-1">
                            <router-link to="" class="text-decoration-none">{{ $t('ott_home.action') }}</router-link>
                          </li>
                        </ul>
                      </div>
                      <h1 class="texture-text big-font letter-spacing-1 line-count-1 text-capitalize RightAnimate-two">
                        {{ $t('ott_home.better_call_saul') }}
                      </h1>
                      <p class="line-count-3 RightAnimate-two">{{ $t('ott_home.ex_jimmy') }}</p>
                      <div class="d-flex flex-wrap align-items-center gap-3 RightAnimate-three">
                        <div class="slider-ratting d-flex align-items-center">
                          <ul class="ratting-start p-0 m-0 list-inline text-warning d-flex align-items-center justify-content-left">
                            <li>
                              <i class="fa fa-star" aria-hidden="true"></i>
                            </li>
                          </ul>
                        </div>
                        <span class="font-size-14 fw-500 text-capitalize">2 {{ $t('ott_home.hr') }}: 55 {{ $t('ott_home.mins') }}</span>
                        <div class="text-primary font-size-14 fw-500 text-capitalize">
                          {{ $t('ott_home.genres') }}: <router-link :to="{ name: 'landing-page.view-all' }" class="text-decoration-none ms-1">{{ $t('ott_home.horror') }}</router-link>
                        </div>
                        <div class="text-primary font-size-14 fw-500 text-capitalize">
                          {{ $t('ott_home.starting') }}: <router-link :to="{ name: 'landing-page.cast-detail' }" class="text-decoration-none ms-1">{{ $t('ott_home.brenda_chapman') }}</router-link>
                          <span class="text-body">,</span>
                          <router-link to="" class="text-decoration-none ms-1">{{ $t('ott_home.caleb_deschannelr') }}</router-link>
                        </div>
                      </div>
                    </div>
                    <custom-button :button-title="$t('ott_home.stream_now')" :link="{ path: '/movies-detail' }"></custom-button>
                  </div>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { Swiper, SwiperSlide } from 'swiper/vue';
import { Navigation, Controller, Thumbs, EffectFade } from 'swiper';
import CustomButton from '../CustomButton.vue';
import { ref, computed, watch } from 'vue';
import { useSetting } from '../../store/setting/index';
const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);
const render = ref(true);
watch(
  () => rtl.value,
  () => {
    thumbsSwiper.value = null;
    render.value = false;
    setTimeout(() => {
      render.value = true;
    }, 0);
  }
);

// Swiper Modules
const modules = [Navigation, Controller, Thumbs, EffectFade];
const thumbsSwiper = ref(null);
const setThumbsSwiper = (swiper) => {
  thumbsSwiper.value = swiper;
};
</script>

// ops/1-assets/1-app-templates/react/movies-prod/v5/next-js/src/components/slider/OttHeroSlider.tsx
import React, { Fragment, useState, useEffect } from "react";

// next link
import Link from "next/link";

// next image
import Image from "next/image";

// components
import CustomButton from "../CustomButton";

// swiper
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { Navigation, Thumbs } from "swiper";

SwiperCore.use([Navigation, Thumbs]);

// Redux Selector / Action
import { useSelector } from "react-redux";
import { theme_scheme_direction } from "../../store/setting/selectors";

const OttHeroSlider = () => {
  const themeSchemeDirection = useSelector(theme_scheme_direction);
  const [thumbsSwiper, setThumbsSwiper] = useState<SwiperCore | null>(null);
  const [render, setRender] = useState(true)
  useEffect(() => {
    setRender(false)
    setTimeout(() => {
      setRender(true)
    }, 100);
    return () => { };
  }, []);

  return (
    <Fragment>
      <div className="iq-banner-thumb-slider">
        <div className="slider">
          <div className="position-relative slider-bg d-flex justify-content-end">
            <div className="position-relative my-auto">
              <div
                className="horizontal_thumb_slider"
                data-swiper="slider-thumbs-ott"
              >
                <div className="banner-thumb-slider-nav">
                  <Swiper
                    key={String(themeSchemeDirection)}
                    dir={String(themeSchemeDirection)}
                    tag="ul"
                    thumbs={{
                      swiper:
                        thumbsSwiper && !thumbsSwiper.destroyed
                          ? thumbsSwiper
                          : null,
                    }}
                    direction="horizontal"
                    navigation={{
                      prevEl: ".slider-prev",
                      nextEl: ".slider-next",
                    }}
                    spaceBetween={24}
                    loop={true}
                    slidesPerView={2}
                    breakpoints={{
                      0: {
                        direction: "horizontal",
                        slidesPerView: 1,
                      },
                      768: {
                        direction: "horizontal",
                        slidesPerView: 2,
                      },
                    }}
                    watchSlidesProgress={true}
                    className="swiper-horizontal swiper-container mb-0"
                  >
                    <SwiperSlide className="swiper-bg">
                      <div className="block-images position-relative">
                        <div className="img-box">
                          <Image
                            src="/assets/images/movies/ott1.webp"
                            className="img-fluid"
                            alt=""
                            loading="lazy"
                            width={0}
                            height={0}
                            sizes="100vw"
                          />
                          <div className="block-description ps-3">
                            <h6 className="iq-title fw-500 mb-0">The Hunter</h6>
                            <span className="fs-12">2 hr 6 minute</span>
                          </div>
                        </div>
                      </div>
                    </SwiperSlide>
                    <SwiperSlide className="swiper-bg">
                      <div className="block-images position-relative">
                        <div className="img-box">
                          <Image
                            src="/assets/images/movies/ott2.webp"
                            className="img-fluid"
                            alt=""
                            loading="lazy"
                            width={0}
                            height={0}
                            sizes="100vw"
                          />
                          <div className="block-description ps-3">
                            <h6 className="iq-title fw-500 mb-0"> The Mandalorian </h6>
                            <span className="fs-12">2 hr 14 minute</span>
                          </div>
                        </div>
                      </div>
                    </SwiperSlide>
                    <SwiperSlide className="swiper-bg">
                      <div className="block-images position-relative">
                        <div className="img-box">
                          <Image
                            src="/assets/images/movies/ott3.webp"
                            className="img-fluid"
                            alt=""
                            loading="lazy"
                            width={0}
                            height={0}
                            sizes="100vw"
                          />
                          <div className="block-description ps-3">
                            <h6 className="iq-title fw-500 mb-0">Better call saul</h6>
                            <span className="fs-12">2 hr 55 minute</span>
                          </div>
                        </div>
                      </div>
                    </SwiperSlide>
                  </Swiper>
                  <div className="slider-prev swiper-button">
                    <i className="iconly-Arrow-Left-2 icli"></i>
                  </div>
                  <div className="slider-next swiper-button">
                    <i className="iconly-Arrow-Right-2 icli"></i>
                  </div>
                </div>
              </div>
            </div>
            <div className="slider-images" data-swiper="slider-images-ott">
              <Swiper
                key={String(themeSchemeDirection)}
                dir={String(themeSchemeDirection)}
                tag="ul"
                onSwiper={setThumbsSwiper}
                slidesPerView={1}
                watchSlidesProgress={true}
                allowTouchMove={false}
                loop={true}
                className="swiper-container"
              >
                <SwiperSlide className="p-0">
                  <div className="slider--image block-images">
                    <Image src="/assets/images/movies/ott1.webp" loading="lazy" alt="banner" width={0}
                      height={0}
                      sizes="100vw" />
                  </div>
                  <div className="description">
                    <div className="row align-items-center h-100">
                      <div className="col-lg-6 col-md-12">
                        <div className="slider-content">
                          <div className="d-flex align-items-center RightAnimate mb-3">
                            <span className="badge rounded-0 text-dark text-uppercase px-3 py-2 me-3 bg-white mr-3">
                              Pg
                            </span>
                            <ul className="p-0 mb-0 list-inline d-flex flex-wrap align-items-center movie-tag">
                              <li className="position-relative text-capitalize font-size-14 letter-spacing-1">
                                <Link
                                  href="/view-all"
                                  className="text-decoration-none"
                                >
                                  Adventure
                                </Link>
                              </li>
                              <li className="position-relative text-capitalize font-size-14 letter-spacing-1">
                                <Link
                                  href="/view-all"
                                  className="text-decoration-none"
                                >
                                  Thriller
                                </Link>
                              </li>
                              <li className="position-relative text-capitalize font-size-14 letter-spacing-1">
                                <Link
                                  href="/view-all"
                                  className="text-decoration-none"
                                >
                                  Drama
                                </Link>
                              </li>
                            </ul>
                          </div>
                          <h1 className="texture-text big-font letter-spacing-1 line-count-1 text-capitalize RightAnimate-two">
                            The Hunter
                          </h1>
                          <p className="line-count-3 RightAnimate-two">
                            After the death of their father, two siblings fight
                            for the throne, thereby causing a civil war known as
                            the Dance of the Dragons. Rhaenyra tries to hold the
                            realm together as the tension rises following a
                            tragic loss. Meanwhile, Daemon prepares for war.
                          </p>
                          <div className="d-flex flex-wrap align-items-center gap-3 RightAnimate-three">
                            <div className="slider-ratting d-flex align-items-center">
                              <ul className="ratting-start p-0 m-0 list-inline text-warning d-flex align-items-center justify-content-left">
                                <li>
                                  <i
                                    className="fa fa-star"
                                    aria-hidden="true"
                                  ></i>
                                </li>
                              </ul>
                              <span className="text-white ms-2 font-size-14 fw-500">
                                4.3/5
                              </span>
                              <span className="ms-2">
                                <Image
                                  src="/assets/images/movies/imdb-logo.svg"
                                  alt="imdb logo"
                                  className="img-fluid"
                                  width={50}
                                  height={50}
                                  sizes="100vw"
                                />
                              </span>
                            </div>
                            <span className="font-size-14 fw-500">
                              2 Hr : 6 Mins
                            </span>
                            <div className="text-primary font-size-14 fw-500 text-capitalize">
                              genres:{" "}
                              <Link
                                href="/view-all"
                                className="text-decoration-none ms-1"
                              >
                                Drama
                              </Link>
                            </div>
                            <div className="text-primary font-size-14 fw-500 text-capitalize">
                              Starting:{" "}
                              <Link
                                href="/cast/detail"
                                className="text-decoration-none ms-1"
                              >
                                Jeffrey Silver
                              </Link>
                            </div>
                          </div>
                        </div>
                        <CustomButton
                          buttonTitle="Stream Now "
                          link="/movies/detail"
                          linkButton="false"
                        />
                      </div>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide className="p-0">
                  <div className="slider--image block-images">
                    <Image src="/assets/images/movies/ott2.webp" loading="lazy" alt="banner" width={0}
                      height={0}
                      sizes="100vw" />
                  </div>
                  <div className="description">
                    <div className="row align-items-center h-100">
                      <div className="col-lg-6 col-md-12">
                        <div className="slider-content">
                          <div className="d-flex align-items-center RightAnimate mb-3">
                            <span className="badge rounded-0 text-dark text-uppercase px-3 py-2 me-3 bg-white mr-3">
                              NC-17
                            </span>
                            <ul className="p-0 mb-0 list-inline d-flex flex-wrap align-items-center movie-tag">
                              <li className="position-relative text-capitalize font-size-14 letter-spacing-1">
                                <Link
                                  href="/view-all"
                                  className="text-decoration-none"
                                >
                                  Animation
                                </Link>
                              </li>
                              <li className="position-relative text-capitalize font-size-14 letter-spacing-1">
                                <Link
                                  href="/view-all"
                                  className="text-decoration-none"
                                >
                                  Sci-Fi
                                </Link>
                              </li>
                              <li className="position-relative text-capitalize font-size-14 letter-spacing-1">
                                <Link
                                  href="/view-all"
                                  className="text-decoration-none"
                                >
                                  Action
                                </Link>
                              </li>
                            </ul>
                          </div>
                          <h1 className="texture-text big-font letter-spacing-1 line-count-1 text-capitalize RightAnimate-two">
                            The Mandalorian
                          </h1>
                          <p className="line-count-3 RightAnimate-two">
                            After the fall of the Galactic Empire, a lone
                            gunfighter makes his way through the outer reaches
                            of the lawless galaxy he show follows the adventures
                            of a lone Mandalorian bounty hunter, Din Djarin, as
                            he navigates the outer reaches of the galaxy, far
                            from the authority of the New Republic.
                          </p>
                          <div className="d-flex flex-wrap align-items-center gap-3 RightAnimate-three">
                            <div className="slider-ratting d-flex align-items-center">
                              <ul className="ratting-start p-0 m-0 list-inline text-warning d-flex align-items-center justify-content-left">
                                <li>
                                  <i
                                    className="fa fa-star"
                                    aria-hidden="true"
                                  ></i>
                                </li>
                              </ul>
                              <span className="text-white ms-2 font-size-14 fw-500">
                                4.3/5
                              </span>
                            </div>
                            <span className="font-size-14 fw-500">
                              2 Hr : 14 Mins
                            </span>
                            <div className="text-primary font-size-14 fw-500 text-capitalize">
                              genres:{" "}
                              <Link
                                href="/view-all"
                                className="text-decoration-none ms-1"
                              >
                                Sci-Fi
                              </Link>
                            </div>
                            <div className="text-primary font-size-14 fw-500 text-capitalize">
                              Starting:{" "}
                              <Link
                                href="/cast/detail"
                                className="text-decoration-none ms-1"
                              >
                                James Chinlund
                              </Link>
                            </div>
                          </div>
                        </div>
                        <CustomButton
                          buttonTitle="Stream Now "
                          link="/movies/detail"
                          linkButton="false"
                        />
                      </div>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide className="p-0">
                  <div className="slider--image block-images">
                    <Image src="/assets/images/movies/ott3.webp" loading="lazy" alt="banner" width={0}
                      height={0}
                      sizes="100vw" />
                  </div>
                  <div className="description">
                    <div className="row align-items-center h-100">
                      <div className="col-lg-6 col-md-12">
                        <div className="slider-content">
                          <div className="d-flex align-items-center RightAnimate mb-3">
                            <span className="badge rounded-0 text-dark text-uppercase px-3 py-2 me-3 bg-white mr-3">
                              G
                            </span>
                            <ul className="p-0 mb-0 list-inline d-flex flex-wrap align-items-center movie-tag">
                              <li className="position-relative text-capitalize font-size-14 letter-spacing-1">
                                <Link
                                  href="/view-all"
                                  className="text-decoration-none"
                                >
                                  History
                                </Link>
                              </li>
                              <li className="position-relative text-capitalize font-size-14 letter-spacing-1">
                                <Link
                                  href="/view-all"
                                  className="text-decoration-none"
                                >
                                  Action
                                </Link>
                              </li>
                            </ul>
                          </div>
                          <h1 className="texture-text big-font letter-spacing-1 line-count-1 text-capitalize RightAnimate-two">
                            Better call saul
                          </h1>
                          <p className="line-count-3 RightAnimate-two">
                            Ex-con artist Jimmy McGill turns into a small-time
                            attorney and goes through a series of trials and
                            tragedies, as he transforms into his alter ego Saul
                            Goodman, a morally challenged criminal lawyer.
                          </p>
                          <div className="d-flex flex-wrap align-items-center gap-3 RightAnimate-three">
                            <div className="slider-ratting d-flex align-items-center">
                              <ul className="ratting-start p-0 m-0 list-inline text-warning d-flex align-items-center justify-content-left">
                                <li>
                                  <i
                                    className="fa fa-star"
                                    aria-hidden="true"
                                  ></i>
                                </li>
                              </ul>
                            </div>
                            <span className="font-size-14 fw-500">
                              2 Hr : 55 Mins
                            </span>
                            <div className="text-primary font-size-14 fw-500 text-capitalize">
                              genres:{" "}
                              <Link
                                href="/view-all"
                                className="text-decoration-none ms-1"
                              >
                                horror
                              </Link>
                            </div>
                            <div className="text-primary font-size-14 fw-500 text-capitalize">
                              Starting:{" "}
                              <Link
                                href="/cast/detail"
                                className="text-decoration-none ms-1"
                              >
                                Brenda Chapman
                              </Link>
                              <span className="text-body">,</span>
                              <Link
                                href="/cast/detail"
                                className="text-decoration-none ms-1"
                              >
                                Caleb Deschannelr
                              </Link>
                            </div>
                          </div>
                        </div>
                        <CustomButton
                          buttonTitle="Stream Now "
                          link="/movies/detail"
                          linkButton="false"
                        />
                      </div>
                    </div>
                  </div>
                </SwiperSlide>
              </Swiper>
            </div>
          </div>
        </div>
      </div>
    </Fragment>
  );
};
export default OttHeroSlider;
