// ops/1-assets/1-app-templates/all/movies-prod/v5/react/frontend/src/views/Playlist.jsx
import React, { Fragment, memo, useState } from "react";

//react bootstrap
import {
  Col,
  Container,
  Row,
  Nav,
  Tab,
  Button,
  Modal,
  Form,
} from "react-bootstrap";

//react-router-dom
import { Link } from "react-router-dom";

//utilites
import { useEnterExit } from "../utilities/usePage";

//function
import { generateImgPath } from "../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const Playlist = memo(() => {
  const { t } = useTranslation();
  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  useEnterExit();

  const playlist = [
    {
      image: generateImgPath("/assets/images/movies/playlist/01.webp"),
      title: t("playlist.play_list1"),
      category: t("playlist.public"),
      views: `3 ${t("playlist.views")}`,
    },
    {
      image: generateImgPath("/assets/images/movies/playlist/02.webp"),
      title: t("playlist.play_list2"),
      category: t("playlist.private"),
      views: `1 ${t("playlist.views")}`,
    },
    {
      image: generateImgPath("/assets/images/movies/playlist/03.webp"),
      title: t("playlist.play_list3"),
      category: t("playlist.public"),
      views: `10 ${t("playlist.views")}`,
    },
    {
      image: generateImgPath("/assets/images/movies/playlist/04.webp"),
      title: t("playlist.play_list4"),
      category: t("playlist.public"),
      views: `30 ${t("playlist.views")}`,
    },
    {
      image: generateImgPath("/assets/images/movies/playlist/05.webp"),
      title: t("playlist.play_list5"),
      category: t("playlist.private"),
      views: `2 ${t("playlist.views")}`,
    },
    {
      image: generateImgPath("/assets/images/movies/playlist/06.webp"),
      title: t("playlist.play_list6"),
      category: t("playlist.public"),
      views: `10 ${t("playlist.views")}`,
    },
    {
      image: generateImgPath("/assets/images/movies/playlist/07.webp"),
      title: t("playlist.play_list7"),
      category: t("playlist.public"),
      views: `50 ${t("playlist.views")}`,
    },
  ];
  return (
    <Fragment>
      <div className="section-padding-bottom">
        <div className="profile-box">
          <Container fluid>
            <div className="d-flex flex-wrap align-items-center justify-content-between gap-2">
              <div className="d-flex align-items-center gap-3">
                <div className="account-logo d-flex align-items-center position-relative">
                  <img
                    src={generateImgPath("/assets/images/pages/profile.webp")}
                    alt="profile"
                    className="img-fluid object-cover rounded-3"
                  />
                  <i className="fa-regular fa-pen-to-square"></i>
                </div>
                <div>
                  <h6 className="font-size-18 text-capitalize text-white fw-500">
                    {t("playlist.admin")}
                  </h6>
                  <span className="font-size-14 text-white fw-500">
                    {t("playlist.admin")}@{t("playlist.admin")}.com
                  </span>
                </div>
              </div>
              <div className="iq-button">
                <Link
                  to="/pricing"
                  className="btn text-uppercase position-relative"
                >
                  <span className="button-text">
                    {t("playlist.subscription")}
                  </span>{" "}
                  <i className="fa-solid fa-play"></i>
                </Link>
              </div>
            </div>
          </Container>
        </div>
        <Container fluid>
          <div className="content-details iq-custom-tab-style-two">
            <Tab.Container defaultActiveKey="first">
              <Nav className="d-flex justify-content-center nav nav-pills tab-header">
                <Nav className="" id="nav-tab" role="tablist">
                  <Nav.Link
                    eventKey="first"
                    variant=" d-flex align-items-center"
                    id="nav-playlist-tab"
                    data-bs-toggle="tab"
                    data-bs-target="#nav-playlist"
                    type="button"
                    role="tab"
                    aria-controls="nav-playlist"
                    aria-selected="true"
                  >
                    {t("playlist.playlist")}
                  </Nav.Link>
                  <Nav.Link
                    eventKey="second"
                    variant=""
                    id="nav-watchlist-tab"
                    data-bs-toggle="tab"
                    data-bs-target="#nav-watchlist"
                    type="button"
                    role="tab"
                    aria-controls="nav-watchlist"
                    aria-selected="false"
                  >
                    {t("header.watchlist")}
                  </Nav.Link>
                  <Nav.Link
                    eventKey="third"
                    variant=""
                    id="nav-favourite-tab"
                    data-bs-toggle="tab"
                    data-bs-target="#nav-favourite"
                    type="button"
                    role="tab"
                    aria-controls="nav-favourite"
                    aria-selected="false"
                  >
                    {t("header.favorites")}
                  </Nav.Link>
                </Nav>
              </Nav>
              <Tab.Content className="p-0">
                <Tab.Pane
                  className=" fade show"
                  eventKey="first"
                  id="nav-playlist"
                  role="tabpanel"
                  aria-labelledby="nav-playlist-tab"
                >
                  <div className="overflow-hidden animated fadeInUp">
                    <div className="d-flex align-items-center justify-content-between my-4">
                      <h5 className="main-title text-capitalize mb-0">
                        {t("playlist.my_playlist")}
                      </h5>
                    </div>
                    <Row className="row-cols-1 row-cols-md-2 row-cols-lg-4">
                      {playlist.map((item, index) => {
                        return (
                          <Col className="mb-4" key={index}>
                            <div className="watchlist-warpper card-hover-style-two">
                              <div className="block-images position-relative w-100">
                                <div className="img-box">
                                  <Link
                                    to="/watchlist-detail"
                                    className="position-absolute top-0 bottom-0 start-0 end-0"
                                  ></Link>
                                  <img
                                    src={item.image}
                                    alt="movie-card"
                                    className="img-fluid object-cover w-100 d-block border-0"
                                  />
                                </div>
                                <div className="card-description">
                                  <h5 className="text-capitalize fw-500">
                                    <Link to="/watchlist-detail">
                                      {t(item.title)}
                                    </Link>
                                  </h5>
                                  <div className="d-flex align-items-center gap-3">
                                    <div className="d-flex align-items-center gap-1 font-size-12">
                                      <i className="fa-solid fa-earth-americas text-primary"></i>
                                      <span className="text-body fw-semibold text-capitalize">
                                        {item.category}
                                      </span>
                                    </div>
                                    <div className="d-flex align-items-center gap-1 font-size-12">
                                      <i className="fa-regular fa-eye text-primary"></i>
                                      <span className="text-body fw-semibold text-capitalize">
                                        {item.views}
                                      </span>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </Col>
                        );
                      })}
                    </Row>
                    <div className="text-center">
                      <div className="iq-button">
                        <Button
                          type="button"
                          className="btn text-uppercase position-relativ"
                          onClick={handleShow}
                        >
                          <span className="button-text">
                            {t("playlist.create_playlist")}
                          </span>{" "}
                          <i className="fa-solid fa-play"></i>
                        </Button>
                      </div>
                    </div>
                  </div>
                </Tab.Pane>
                <Tab.Pane
                  className=" fade"
                  id="nav-watchlist"
                  eventKey="second"
                  role="tabpanel"
                  aria-labelledby="nav-watchlist-tab"
                >
                  <div className="overflow-hidden">
                    <div className="d-flex align-items-center justify-content-between my-4">
                      <h5 className="main-title text-capitalize mb-0">
                        {t("playlist.my_watchlist")}
                      </h5>
                    </div>
                    <Row className="row-cols-1 row-cols-md-2 row-cols-lg-4">
                      {playlist.slice(0, 4).map((item, index) => {
                        return (
                          <Col className="mb-4" key={index}>
                            <div className="watchlist-warpper card-hover-style-two">
                              <div className="block-images position-relative w-100">
                                <div className="img-box">
                                  <Link
                                    to="/watchlist-detail"
                                    className="position-absolute top-0 bottom-0 start-0 end-0"
                                  ></Link>
                                  <img
                                    src={item.image}
                                    alt="movie-card"
                                    className="img-fluid object-cover w-100 d-block border-0"
                                  />
                                </div>
                                <div className="card-description">
                                  <h5 className="text-capitalize fw-500">
                                    <Link to="/watchlist-detail">
                                      {t(item.title)}
                                    </Link>
                                  </h5>
                                  <div className="d-flex align-items-center gap-3">
                                    <div className="d-flex align-items-center gap-1 font-size-12">
                                      <i className="fa-solid fa-earth-americas text-primary"></i>
                                      <span className="text-body fw-semibold text-capitalize">
                                        {item.category}
                                      </span>
                                    </div>
                                    <div className="d-flex align-items-center gap-1 font-size-12">
                                      <i className="fa-regular fa-eye text-primary"></i>
                                      <span className="text-body fw-semibold text-capitalize">
                                        {item.views}
                                      </span>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </Col>
                        );
                      })}
                    </Row>
                    <div className="text-center">
                      <div className="iq-button">
                        <Button
                          type="button"
                          className="btn text-uppercase position-relativ"
                          onClick={handleShow}
                        >
                          <span className="button-text">
                            {t("playlist.create_watchlist")}{" "}
                          </span>
                          <i className="fa-solid fa-play"></i>
                        </Button>
                      </div>
                    </div>
                  </div>
                </Tab.Pane>
                <Tab.Pane
                  className=" fade"
                  id="nav-favourite"
                  eventKey="third"
                  role="tabpanel"
                  aria-labelledby="nav-favourite-tab"
                >
                  <div className="overflow-hidden">
                    <div className="d-flex align-items-center justify-content-between my-4">
                      <h5 className="main-title text-capitalize mb-0">
                        {t("playlist.my_favourite")}
                      </h5>
                    </div>
                    <Row className="row-cols-1 row-cols-md-2 row-cols-lg-4">
                      {playlist.map((item, index) => {
                        return (
                          <Col className="mb-4" key={index}>
                            <div className="watchlist-warpper card-hover-style-two">
                              <div className="block-images position-relative w-100">
                                <div className="img-box">
                                  <Link
                                    to="/watchlist-detail"
                                    className="position-absolute top-0 bottom-0 start-0 end-0"
                                  ></Link>
                                  <img
                                    src={item.image}
                                    alt="movie-card"
                                    className="img-fluid object-cover w-100 d-block border-0"
                                  />
                                </div>
                                <div className="card-description">
                                  <h5 className="text-capitalize fw-500">
                                    <Link to="/watchlist-detail">
                                      {t(item.title)}
                                    </Link>
                                  </h5>
                                  <div className="d-flex align-items-center gap-3">
                                    <div className="d-flex align-items-center gap-1 font-size-12">
                                      <i className="fa-solid fa-earth-americas text-primary"></i>
                                      <span className="text-body fw-semibold text-capitalize">
                                        {item.category}
                                      </span>
                                    </div>
                                    <div className="d-flex align-items-center gap-1 font-size-12">
                                      <i className="fa-regular fa-eye text-primary"></i>
                                      <span className="text-body fw-semibold text-capitalize">
                                        {item.views}
                                      </span>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </Col>
                        );
                      })}
                    </Row>
                    <div className="text-center">
                      <div className="iq-button">
                        <Button
                          type="button"
                          className="btn text-uppercase position-relativ"
                          onClick={handleShow}
                        >
                          <span className="button-text">
                            {t("playlist.create_playlist")}{" "}
                          </span>
                          <i className="fa-solid fa-play"></i>
                        </Button>
                      </div>
                    </div>
                  </div>
                </Tab.Pane>
              </Tab.Content>
            </Tab.Container>
            <Modal
              show={show}
              onHide={handleClose}
              size="lg"
              contentClassName="border-0"
            >
              <Modal.Header closeButton className="border-0">
                <div>
                  <Modal.Title as="h1" className="text-capitalize fs-5 fw-500">
                    {t("playlist.new_playlist")}
                  </Modal.Title>
                  <p className="mb-0">{t("playlist.information")}</p>
                </div>
              </Modal.Header>
              <Modal.Body>
                <Form>
                  <Form.Group className="form-group">
                    <Form.Label className="text-white fw-500 mb-2">
                      {t("playlist.name")} *
                    </Form.Label>
                    <Form.Control type="text" />
                  </Form.Group>
                  <Form.Group className="form-group">
                    <Form.Label className="text-white fw-500 mb-2">
                      {t("playlist.description")}
                    </Form.Label>
                    <textarea className="form-control" cols="5"></textarea>
                  </Form.Group>
                  <Form.Group className="form-group">
                    <Form.Label className="text-white fw-500 mb-2">
                      {t("playlist.privacy")}
                    </Form.Label>
                    <Form.Select className="form-control">
                      <option>{t("playlist.public")}</option>
                      <option>{t("playlist.private")}</option>
                    </Form.Select>
                  </Form.Group>
                  <Form.Group className="form-group">
                    <div className="text-white fw-500">
                      {t("playlist.thumbnail")}
                    </div>
                    <small className="d-block my-2">
                      {t("playlist.maximum_upload")}
                    </small>
                    <Form.Control type="file" />
                  </Form.Group>
                  <Form.Group className="form-group d-flex align-items-center gap-3">
                    <button
                      className="btn btn-sm btn-light text-uppercase fw-medium">
                      {t("playlist.cancel")}
                    </button>
                    <Button
                      className="btn btn-sm btn-primary text-uppercase fw-medium"
                      onClick={handleClose}
                    >
                      {t("playlist.save")}
                    </Button>
                  </Form.Group>
                </Form>
              </Modal.Body>
            </Modal>
          </div>
        </Container>

        {/*  */}
      </div>
    </Fragment>
  );
});

export default Playlist;

// ops/1-assets/1-app-templates/all/movies-prod/v5/vue/frontend/src/views/PlayList.vue
<template>
  <div class="section-padding-bottom">
    <div class="profile-box">
      <div class="container-fluid">
        <div class="d-flex flex-wrap align-items-center justify-content-between gap-2">
          <div class="d-flex align-items-center gap-3">
            <div class="account-logo d-flex align-items-center position-relative">
              <img src="/assets/images/pages/profile.webp" class="img-fluid object-cover rounded-3" alt="profile" loading="lazy" />
              <i class="fa-regular fa-pen-to-square"></i>
            </div>
            <div>
              <h6 class="font-size-18 text-capitalize text-white fw-500">{{ $t('playlist.admin') }}</h6>
              <span class="font-size-14 text-white fw-500">admin@admin.com</span>
            </div>
          </div>
          <div class="iq-button">
            <router-link :to="{ name: 'landing-page.pricing-plan' }" class="btn text-uppercase position-relative">
              <span class="button-text">{{ $t('playlist.subscription') }}</span>
              {{ '' }}
              <i class="fa-solid fa-play"></i>
            </router-link>
          </div>
        </div>
      </div>
    </div>
    <div class="tabs">
      <div class="container-fluid">
        <div class="content-details iq-custom-tab-style-two">
          <b-tabs class="trending-custom-tab" content-class="px-0" pills nav-class="d-flex justify-content-center nav nav-pills tab-header">
            <b-tab :title="$t('header.playlist')" active>
              <div class="overflow-hidden animate__animated animate__fadeInUp">
                <div class="d-flex align-items-center justify-content-between my-4">
                  <h5 class="main-title text-capitalize mb-0">{{ $t('playlist.my_playlist') }}</h5>
                </div>
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
                  <div v-for="data in playlistData" :key="'playlist' + data.title" class="col mb-4">
                    <WatchlistCard :image="data.image" :title="$t(data.title)" :category="$t(data.category)" :views="$t(data.views)" :view_count="data.view_count"></WatchlistCard>
                  </div>
                </div>
              </div>
              <create-playlist buttonname="playlist.create_playlist"></create-playlist>
            </b-tab>
            <b-tab :title="$t('header.watchlist')">
              <div class="overflow-hidden animate__animated animate__fadeInUp">
                <div class="d-flex align-items-center justify-content-between my-4">
                  <h5 class="main-title text-capitalize mb-0">{{ $t('playlist.my_watchlist') }}</h5>
                </div>
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
                  <div v-for="data in playlistData.slice(0, 4)" :key="'playlist' + data.title" class="col mb-4">
                    <WatchlistCard :image="data.image" :title="$t(data.title)" :category="$t(data.category)" :views="$t(data.views)" :view_count="data.view_count"></WatchlistCard>
                  </div>
                </div>
              </div>
              <create-playlist buttonname="sweetalert.create_watchlist"></create-playlist>
            </b-tab>
            <b-tab :title="$t('header.favorites')">
              <div class="overflow-hidden animate__animated animate__fadeInUp">
                <div class="d-flex align-items-center justify-content-between my-4">
                  <h5 class="main-title text-capitalize mb-0">{{ $t('playlist.my_favourite') }}</h5>
                </div>
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
                  <div v-for="data in playlistData" :key="'playlist' + data.title" class="col mb-4">
                    <WatchlistCard :image="data.image" :title="$t(data.title)" :category="$t(data.category)" :views="$t(data.views)" :view_count="data.view_count"></WatchlistCard>
                  </div>
                </div>
              </div>
              <create-playlist buttonname="playlist.create_playlist"></create-playlist>
            </b-tab>
          </b-tabs>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { onMounted, onUnmounted } from 'vue';
import WatchlistCard from '../components/cards/WatchlistCard.vue';
import CreatePlaylist from '../components/CreatePlaylist.vue';
import { generateImgPath } from '../StaticData/data';
onMounted(() => {
  document.body.classList.add('custom-header-relative');
});

onUnmounted(() => {
  document.body.classList.remove('custom-header-relative');
});

const playlistData = [
  {
    image: generateImgPath('/assets/images/movies/playlist/01.webp'),
    title: 'playlist.play_list1',
    category: 'playlist.public',
    view_count: '3',
    views: 'playlist.views',
  },
  {
    image: generateImgPath('/assets/images/movies/playlist/02.webp'),
    title: 'playlist.play_list2',
    category: 'playlist.private',
    view_count: '1',
    views: 'playlist.views',
  },
  {
    image: generateImgPath('/assets/images/movies/playlist/03.webp'),
    title: 'playlist.play_list3',
    category: 'playlist.public',
    view_count: '10',
    views: 'playlist.views',
  },
  {
    image: generateImgPath('/assets/images/movies/playlist/04.webp'),
    title: 'playlist.play_list4',
    category: 'playlist.public',
    view_count: '30',
    views: 'playlist.views',
  },
  {
    image: generateImgPath('/assets/images/movies/playlist/05.webp'),
    title: 'playlist.play_list5',
    category: 'playlist.private',
    view_count: '2',
    views: 'playlist.views',
  },
  {
    image: generateImgPath('/assets/images/movies/playlist/06.webp'),
    title: 'playlist.play_list6',
    category: 'playlist.public',
    view_count: '10',
    views: 'playlist.views',
  },
  {
    image: generateImgPath('/assets/images/movies/playlist/07.webp'),
    title: 'playlist.play_list7',
    category: 'playlist.public',
    view_count: '50',
    views: 'playlist.views',
  },
];
</script>
