// ops/1-assets/2-app-templates/all/movies-prod/v5/vue/frontend/src/components/slider/VideoHeroSlider.vue
<template>
  <section class="banner-container">
    <div class="movie-banner">
      <Swiper
        v-if="render"
        :dir="rtl"
        :navigation="{
          prevEl: '.swiper-banner-button-prev',
          nextEl: '.swiper-banner-button-next',
        }"
        :slides-per-view="1.2"
        :modules="modules"
        :loop="true"
        :centered-slides="true"
        class="swiper-banner-container iq-rtl-direction">
        <SwiperSlide class="video-1 p-0">
          <div class="movie-banner-image">
            <img src="/assets/images/video/banner-1.webp" alt="movie-banner-image" loading="lazy" />
          </div>
          <div class="shows-content h-100">
            <b-row class="align-items-center h-100">
              <b-col lg="7" md="12">
                <h1 class="texture-text big-font letter-spacing-1 line-count-1 text-uppercase RightAnimate-two" data-animation-in="fadeInLeft" data-delay-in="0.6">{{ $t('home.sapce') }}</h1>
                <div class="flex-wrap align-items-center fadeInLeft animated" data-animation-in="fadeInLeft" style="opacity: 1">
                  <div class="slider-ratting d-flex align-items-center gap-3">
                    <ul class="ratting-start p-0 m-0 list-inline text-primary d-flex align-items-center justify-content-left">
                      <li>
                        <i class="fas fa-star" aria-hidden="true"></i>
                      </li>
                      <li>
                        <i class="fas fa-star" aria-hidden="true"></i>
                      </li>
                      <li>
                        <i class="fas fa-star" aria-hidden="true"></i>
                      </li>
                      <li>
                        <i class="fa fa-star-half" aria-hidden="true"></i>
                      </li>
                    </ul>
                    <span class="text-white">3.5(lmdb)</span>
                  </div>
                  <div class="d-flex flex-wrap align-items-center gap-3 movie-banner-time">
                    <span class="badge bg-secondary p-2">
                      <i class="fa fa-eye"></i>
                      PG
                    </span>
                    <span class="font-size-6">
                      <i class="fa-solid fa-circle"></i>
                    </span>
                    <span class="trending-time font-normal text-lowercase"> 1{{ $t('ott_home.hr') }} 44{{ $t('ott_home.mins') }}</span>
                    <span class="font-size-6">
                      <i class="fa-solid fa-circle"></i>
                    </span>
                    <span class="trending-year font-normal"> Feb 2018 </span>
                  </div>
                  <p class="movie-banner-text line-count-3" data-animation-in="fadeInUp" data-delay-in="1.2">{{ $t('home.dinosaurs_group') }}</p>
                </div>
                <div class="iq-button" data-animation-in="fadeInUp" data-delay-in="1.2">
                  <router-link :to="{ name: 'landing.video-detail' }" class="btn text-uppercase position-relative">
                    <span class="button-text">{{ $t('detail_page.play_now') }}</span>
                    {{ '' }}
                    <i class="fa-solid fa-play"></i>
                  </router-link>
                </div>
              </b-col>
              <b-col lg="5" md="12" class="trailor-video iq-slider d-none d-lg-block">
                <a href="#" class="video-open playbtn" tabindex="0">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="80px" height="80px" viewBox="0 0 213.7 213.7" enable-background="new 0 0 213.7 213.7" xml:space="preserve" @click="toggler = !toggler">
                    <polygon class="triangle" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" points="73.5,62.5 148.5,105.8 73.5,149.1 "></polygon>
                    <circle class="circle" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" cx="106.8" cy="106.8" r="103.3"></circle>
                  </svg>
                  {{ '' }}
                  <span class="w-trailor text-uppercase" @click="toggler = !toggler">{{ $t('home.watch_trailer') }}</span>
                </a>
              </b-col>
            </b-row>
          </div>
        </SwiperSlide>
        <SwiperSlide class="video-1 p-0">
          <div class="movie-banner-image">
            <img src="/assets/images/video/banner-2.webp" alt="movie-banner-image" loading="lazy" />
          </div>
          <div class="shows-content h-100">
            <b-row class="align-items-center h-100">
              <b-col lg="7" md="12">
                <h1 class="texture-text big-font letter-spacing-1 line-count-1 text-uppercase RightAnimate-two" data-animation-in="fadeInLeft" data-delay-in="0.6">{{ $t('home.dragon_king') }}</h1>
                <div class="flex-wrap align-items-center fadeInLeft animated" data-animation-in="fadeInLeft" style="opacity: 1">
                  <div class="slider-ratting d-flex align-items-center gap-3">
                    <ul class="ratting-start p-0 m-0 list-inline text-primary d-flex align-items-center justify-content-left">
                      <li>
                        <i class="fas fa-star" aria-hidden="true"></i>
                      </li>
                      <li>
                        <i class="fas fa-star" aria-hidden="true"></i>
                      </li>
                      <li>
                        <i class="fas fa-star" aria-hidden="true"></i>
                      </li>
                      <li>
                        <i class="fa fa-star-half" aria-hidden="true"></i>
                      </li>
                    </ul>
                    <span class="text-white">3.5(lmdb)</span>
                  </div>
                  <div class="d-flex flex-wrap align-items-center gap-3 movie-banner-time">
                    <span class="badge bg-secondary p-2">
                      <i class="fa fa-eye"></i>
                      G
                    </span>
                    <span class="font-size-6">
                      <i class="fa-solid fa-circle"></i>
                    </span>
                    <span class="trending-time font-normal text-lowercase"> 2{{ $t('ott_home.hr') }} 42{{ $t('ott_home.mins') }}</span>
                    <span class="font-size-6">
                      <i class="fa-solid fa-circle"></i>
                    </span>
                    <span class="trending-year font-normal"> Nov 2017 </span>
                  </div>
                  <p class="movie-banner-text line-count-3" data-animation-in="fadeInUp" data-delay-in="1.2">{{ $t('home.brutal_emperor') }}</p>
                </div>
                <div class="iq-button" data-animation-in="fadeInUp" data-delay-in="1.2">
                  <router-link :to="{ name: 'landing.video-detail' }" class="btn text-uppercase position-relative">
                    <span class="button-text">{{ $t('detail_page.play_now') }}</span>
                    {{ '' }}
                    <i class="fa-solid fa-play"></i>
                  </router-link>
                </div>
              </b-col>
              <b-col lg="5" md="12" class="trailor-video iq-slider d-none d-lg-block">
                <a href="#" class="video-open playbtn" tabindex="0">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="80px" height="80px" viewBox="0 0 213.7 213.7" enable-background="new 0 0 213.7 213.7" xml:space="preserve" @click="toggler = !toggler">
                    <polygon class="triangle" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" points="73.5,62.5 148.5,105.8 73.5,149.1 "></polygon>
                    <circle class="circle" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" cx="106.8" cy="106.8" r="103.3"></circle>
                  </svg>
                  {{ '' }}
                  <span class="w-trailor text-uppercase" @click="toggler = !toggler">{{ $t('home.watch_trailer') }}</span>
                </a>
              </b-col>
            </b-row>
          </div>
        </SwiperSlide>
        <SwiperSlide class="video-1 p-0">
          <div class="movie-banner-image">
            <img src="/assets/images/video/banner-3.webp" alt="movie-banner-image" loading="lazy" />
          </div>
          <div class="shows-content h-100">
            <b-row class="align-items-center h-100">
              <b-col lg="7" md="12">
                <h1 class="texture-text big-font letter-spacing-1 line-count-1 text-uppercase RightAnimate-two" data-animation-in="fadeInLeft" data-delay-in="0.6">{{ $t('home.charlie_chaplin') }}</h1>
                <div class="flex-wrap align-items-center fadeInLeft animated" data-animation-in="fadeInLeft" style="opacity: 1">
                  <div class="slider-ratting d-flex align-items-center gap-3">
                    <ul class="ratting-start p-0 m-0 list-inline text-primary d-flex align-items-center justify-content-left">
                      <li>
                        <i class="fas fa-star" aria-hidden="true"></i>
                      </li>
                      <li>
                        <i class="fas fa-star" aria-hidden="true"></i>
                      </li>
                      <li>
                        <i class="fas fa-star" aria-hidden="true"></i>
                      </li>
                      <li>
                        <i class="fa fa-star-half" aria-hidden="true"></i>
                      </li>
                    </ul>
                    <span class="text-white">3.5(lmdb)</span>
                  </div>
                  <div class="d-flex flex-wrap align-items-center gap-3 movie-banner-time">
                    <span class="badge bg-secondary p-2">
                      <i class="fa fa-eye"></i>
                      PG-13
                    </span>
                    <span class="font-size-6">
                      <i class="fa-solid fa-circle"></i>
                    </span>
                    <span class="trending-time font-normal text-lowercase"> 2{{ $t('ott_home.hr') }} 12{{ $t('ott_home.mins') }}</span>
                    <span class="font-size-6">
                      <i class="fa-solid fa-circle"></i>
                    </span>
                    <span class="trending-year font-normal"> Dec 2018 </span>
                  </div>
                  <p class="movie-banner-text line-count-3" data-animation-in="fadeInUp" data-delay-in="1.2">{{ $t('home.jumbo_also') }}</p>
                </div>
                <div class="iq-button" data-animation-in="fadeInUp" data-delay-in="1.2">
                  <router-link :to="{ name: 'landing.video-detail' }" class="btn text-uppercase position-relative">
                    <span class="button-text">{{ $t('detail_page.play_now') }}</span>
                    {{ '' }}
                    <i class="fa-solid fa-play"></i>
                  </router-link>
                </div>
              </b-col>
              <b-col lg="5" md="12" class="trailor-video iq-slider d-none d-lg-block">
                <a href="#" class="video-open playbtn" tabindex="0">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="80px" height="80px" viewBox="0 0 213.7 213.7" enable-background="new 0 0 213.7 213.7" xml:space="preserve" @click="toggler = !toggler">
                    <polygon class="triangle" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" points="73.5,62.5 148.5,105.8 73.5,149.1 "></polygon>
                    <circle class="circle" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" cx="106.8" cy="106.8" r="103.3"></circle>
                  </svg>
                  {{ '' }}
                  <span class="w-trailor text-uppercase" @click="toggler = !toggler">{{ $t('home.watch_trailer') }}</span>
                </a>
              </b-col>
            </b-row>
          </div>
        </SwiperSlide>

        <div class="swiper-banner-button-next">
          <i class="iconly-Arrow-Right-2 icli arrow-icon"></i>
        </div>
        <div class="swiper-banner-button-prev">
          <i class="iconly-Arrow-Left-2 icli arrow-icon"></i>
        </div>
      </Swiper>
    </div>
  </section>
</template>
<script setup>
import { Swiper, SwiperSlide } from 'swiper/vue';
import { Navigation } from 'swiper';
import { ref, computed, watch } from 'vue';
import { useEnterExit } from '../../utilities/usePage';
import { useSetting } from '../../store/setting/index';
const store = useSetting();
const rtl = computed(() => store.theme_scheme_direction_value);
const render = ref(true);
watch(
  () => rtl.value,
  () => {
    render.value = false;
    setTimeout(() => {
      render.value = true;
    }, 0);
  }
);

// Swiper Modules
const modules = [Navigation];

useEnterExit();
</script>

// ops/1-assets/1-app-templates/all/movies-prod/v5/next-js/src/components/slider/VideoHeroSlider.tsx
import React, { memo, Fragment, useState } from "react";

//react-bootstrap
import { Col, Row } from "react-bootstrap";

// router
import Link from "next/link";

//react fs-lightbox
import FsLightbox from "fslightbox-react";

// swiper
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation } from "swiper";

// Redux Selector / Action
import { useSelector } from "react-redux";
import { theme_scheme_direction } from "../../store/setting/selectors";

const VideoHeroSlider = memo(() => {
  const themeSchemeDirection = useSelector(theme_scheme_direction);
  const [toggler, setToggler] = useState(false);
  return (
    <Fragment>
      <section className="banner-container section-padding-bottom">
        <div className="movie-banner">
          <div id="banner-detail-slider" className="banner-container">
            <div className="movie-banner tvshows-slider">
              <Swiper
                key={String(themeSchemeDirection)}
                dir={String(themeSchemeDirection)}
                navigation={{
                  prevEl: ".swiper-banner-button-prev",
                  nextEl: ".swiper-banner-button-next",
                }}
                slidesPerView={1.2}
                modules={[Navigation]}
                loop={true}
                centeredSlides={true}
                className="swiper-banner-container"
              >
                <SwiperSlide>
                  <div className="movie-banner-image">
                    <img src="/assets/images/video/banner-1.webp" alt="movie-banner-image" />
                  </div>
                  <div className="shows-content h-100">
                    <Row className=" align-items-center h-100">
                      <Col lg="7" md="12">
                        <h1
                          className="texture-text big-font letter-spacing-1 line-count-1 text-uppercase RightAnimate-two"
                          data-animation-in="fadeInLeft"
                          data-delay-in="0.6"
                        >
                          Sapce
                        </h1>
                        <div
                          className="flex-wrap align-items-center fadeInLeft animated"
                          data-animation-in="fadeInLeft"
                          style={{ opacity: 1 }}
                        >
                          <div className="slider-ratting d-flex align-items-center gap-3">
                            <ul className="ratting-start p-0 m-0 list-inline text-primary d-flex align-items-center justify-content-left">
                              <li>
                                <i
                                  className="fas fa-star"
                                  aria-hidden="true"
                                ></i>
                              </li>
                              <li>
                                <i
                                  className="fas fa-star"
                                  aria-hidden="true"
                                ></i>
                              </li>
                              <li>
                                <i
                                  className="fas fa-star"
                                  aria-hidden="true"
                                ></i>
                              </li>
                              <li>
                                <i
                                  className="fa fa-star-half"
                                  aria-hidden="true"
                                ></i>
                              </li>
                            </ul>
                            <span className="text-white">3.5(lmdb)</span>
                          </div>
                          <div className="d-flex flex-wrap align-items-center gap-3 movie-banner-time">
                            <span className="badge bg-secondary p-2">
                              <i className="fa fa-eye"></i>
                              PG
                            </span>
                            <span className="font-size-6">
                              <i className="fa-solid fa-circle"></i>
                            </span>
                            <span className="trending-time font-normal">
                              {" "}
                              1hr : 44mins{" "}
                            </span>
                            <span className="font-size-6">
                              <i className="fa-solid fa-circle"></i>
                            </span>
                            <span className="trending-year font-normal">
                              {" "}
                              Feb 2018{" "}
                            </span>
                          </div>
                          <p
                            className="movie-banner-text line-count-3"
                            data-animation-in="fadeInUp"
                            data-delay-in="1.2"
                          >
                            Dinosaurs are a diverse group of reptiles of the
                            clade Dinosauria. They first appeared during the
                            Triassic period, between 243 and 233.23 million
                            years ago, although the exact origin and timing of
                            the evolution of dinosaurs is the subject of active
                            research.
                          </p>
                        </div>
                        <div
                          className="iq-button"
                          data-animation-in="fadeInUp"
                          data-delay-in="1.2"
                        >
                          <Link
                            href="/videos/detail"
                            className="btn text-uppercase position-relative"
                          >
                            <span className="button-text">Play Now</span>
                            <i className="fa-solid fa-play"></i>
                          </Link>
                        </div>
                      </Col>
                      <Col
                        lg="5"
                        md="12"
                        className="trailor-video iq-slider d-none d-lg-block"
                      >
                        <Link
                          href="#"
                          className="video-open playbtn"
                          tabIndex={0}
                        >
                          <svg
                            version="1.1"
                            xmlns="http://www.w3.org/2000/svg"
                            x="0px"
                            y="0px"
                            width="80px"
                            height="80px"
                            viewBox="0 0 213.7 213.7"
                            enableBackground="new 0 0 213.7 213.7"
                            xmlSpace="preserve"
                            onClick={() => setToggler(!toggler)}
                          >
                            <polygon
                              className="triangle"
                              fill="none"
                              strokeWidth="7"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeMiterlimit="10"
                              points="73.5,62.5 148.5,105.8 73.5,149.1 "
                            ></polygon>
                            <circle
                              className="circle"
                              fill="none"
                              strokeWidth="7"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeMiterlimit="10"
                              cx="106.8"
                              cy="106.8"
                              r="103.3"
                            ></circle>
                          </svg>
                          <span
                            className="w-trailor text-uppercase"
                            onClick={() => setToggler(!toggler)}
                          >
                            Watch Trailer
                          </span>
                        </Link>
                      </Col>
                    </Row>
                  </div>
                </SwiperSlide>
                <SwiperSlide>
                  <div className="movie-banner-image">
                    <img src="/assets/images/video/banner-2.webp" alt="movie-banner-image" />
                  </div>
                  <div className="shows-content h-100">
                    <Row className="align-items-center h-100">
                      <Col lg="7" md="12">
                        <h1
                          className="texture-text big-font letter-spacing-1 line-count-1 text-uppercase RightAnimate-two"
                          data-animation-in="fadeInLeft"
                          data-delay-in="0.6"
                        >
                          The Dragon King
                        </h1>
                        <div
                          className="flex-wrap align-items-center fadeInLeft animated"
                          data-animation-in="fadeInLeft"
                          style={{ opacity: 1 }}
                        >
                          <div className="slider-ratting d-flex align-items-center gap-3">
                            <ul className="ratting-start p-0 m-0 list-inline text-primary d-flex align-items-center justify-content-left">
                              <li>
                                <i
                                  className="fas fa-star"
                                  aria-hidden="true"
                                ></i>
                              </li>
                              <li>
                                <i
                                  className="fas fa-star"
                                  aria-hidden="true"
                                ></i>
                              </li>
                              <li>
                                <i
                                  className="fas fa-star"
                                  aria-hidden="true"
                                ></i>
                              </li>
                              <li>
                                <i
                                  className="fa fa-star-half"
                                  aria-hidden="true"
                                ></i>
                              </li>
                            </ul>
                            <span className="text-white">3.5(lmdb)</span>
                          </div>
                          <div className="d-flex flex-wrap align-items-center gap-3 movie-banner-time">
                            <span className="badge bg-secondary p-2">
                              <i className="fa fa-eye"></i>G
                            </span>
                            <span className="font-size-6">
                              <i className="fa-solid fa-circle"></i>
                            </span>
                            <span className="trending-time font-normal">
                              2hr : 42mins{" "}
                            </span>
                            <span className="font-size-6">
                              <i className="fa-solid fa-circle"></i>
                            </span>
                            <span className="trending-year font-normal">
                              {" "}
                              Nov 2017{" "}
                            </span>
                          </div>
                          <p
                            className="movie-banner-text line-count-3"
                            data-animation-in="fadeInUp"
                            data-delay-in="1.2"
                          >
                            The most brutal emperor in the history of world.He
                            was the founder of the most contiguous empire of the
                            world i.e. the Mongol empire.He made an army by
                            himself by uniting some nomadic tribes and trained
                            them.
                          </p>
                        </div>
                        <div
                          className="iq-button"
                          data-animation-in="fadeInUp"
                          data-delay-in="1.2"
                        >
                          <Link
                            href="/videos/detail"
                            className="btn text-uppercase position-relative"
                          >
                            <span className="button-text">Play Now</span>
                            <i className="fa-solid fa-play"></i>
                          </Link>
                        </div>
                      </Col>
                      <Col
                        lg="5"
                        md="12"
                        className="trailor-video iq-slider d-none d-lg-block"
                      >
                        <Link
                          href="#"
                          className="video-open playbtn"
                          tabIndex={0}
                        >
                          <svg
                            version="1.1"
                            xmlns="http://www.w3.org/2000/svg"
                            x="0px"
                            y="0px"
                            width="80px"
                            height="80px"
                            viewBox="0 0 213.7 213.7"
                            enableBackground="new 0 0 213.7 213.7"
                            xmlSpace="preserve"
                            onClick={() => setToggler(!toggler)}
                          >
                            <polygon
                              className="triangle"
                              fill="none"
                              strokeWidth="7"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeMiterlimit="10"
                              points="73.5,62.5 148.5,105.8 73.5,149.1 "
                            ></polygon>
                            <circle
                              className="circle"
                              fill="none"
                              strokeWidth="7"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeMiterlimit="10"
                              cx="106.8"
                              cy="106.8"
                              r="103.3"
                            ></circle>
                          </svg>
                          <span
                            className="w-trailor text-uppercase"
                            onClick={() => setToggler(!toggler)}
                          >
                            Watch Trailer
                          </span>
                        </Link>
                      </Col>
                    </Row>
                  </div>
                </SwiperSlide>
                <SwiperSlide>
                  <div className="movie-banner-image">
                    <img src="/assets/images/video/banner-3.webp" alt="movie-banner-image" />
                  </div>
                  <div className="shows-content h-100">
                    <Row className="align-items-center h-100">
                      <Col lg="7" md="12">
                        <h1
                          className="texture-text big-font letter-spacing-1 line-count-1 text-uppercase RightAnimate-two"
                          data-animation-in="fadeInLeft"
                          data-delay-in="0.6"
                        >
                          charlie chaplin
                        </h1>
                        <div
                          className="flex-wrap align-items-center fadeInLeft animated"
                          data-animation-in="fadeInLeft"
                          style={{ opacity: 1 }}
                        >
                          <div className="slider-ratting d-flex align-items-center gap-3">
                            <ul className="ratting-start p-0 m-0 list-inline text-primary d-flex align-items-center justify-content-left">
                              <li>
                                <i
                                  className="fas fa-star"
                                  aria-hidden="true"
                                ></i>
                              </li>
                              <li>
                                <i
                                  className="fas fa-star"
                                  aria-hidden="true"
                                ></i>
                              </li>
                              <li>
                                <i
                                  className="fas fa-star"
                                  aria-hidden="true"
                                ></i>
                              </li>
                              <li>
                                <i
                                  className="fa fa-star-half"
                                  aria-hidden="true"
                                ></i>
                              </li>
                            </ul>
                            <span className="text-white">3.5(lmdb)</span>
                          </div>
                          <div className="d-flex flex-wrap align-items-center gap-3 movie-banner-time">
                            <span className="badge bg-secondary p-2">
                              <i className="fa fa-eye"></i>
                              PG-13
                            </span>
                            <span className="font-size-6">
                              <i className="fa-solid fa-circle"></i>
                            </span>
                            <span className="trending-time font-normal">
                              {" "}
                              2hr : 12mins{" "}
                            </span>
                            <span className="font-size-6">
                              <i className="fa-solid fa-circle"></i>
                            </span>
                            <span className="trending-year font-normal">
                              {" "}
                              Dec 2018{" "}
                            </span>
                          </div>
                          <p
                            className="movie-banner-text line-count-3"
                            data-animation-in="fadeInUp"
                            data-delay-in="1.2"
                          >
                            Jumbo also known as Jumbo the Elephant and Jumbo the
                            Circus Elephant, was a 19th-century male African
                            bush elephant born in Sudan. Jumbo was exported to
                            Jardin des Plantes, a zoo in Paris, and then
                            transferred in 1865 to London Zoo in England.
                            Despite public protest, Jumbo was sold to P. T.
                            Barnum, who took him to the United States for
                            exhibition in March 1882.
                          </p>
                        </div>
                        <div
                          className="iq-button"
                          data-animation-in="fadeInUp"
                          data-delay-in="1.2"
                        >
                          <Link
                            href="/videos/detail"
                            className="btn text-uppercase position-relative"
                          >
                            <span className="button-text">Play Now</span>
                            <i className="fa-solid fa-play"></i>
                          </Link>
                        </div>
                      </Col>
                      <Col
                        lg="5"
                        md="12"
                        className="trailor-video iq-slider d-none d-lg-block"
                      >
                        <Link
                          href="#"
                          className="video-open playbtn"
                          tabIndex={0}
                        >
                          <svg
                            version="1.1"
                            xmlns="http://www.w3.org/2000/svg"
                            x="0px"
                            y="0px"
                            width="80px"
                            height="80px"
                            viewBox="0 0 213.7 213.7"
                            enableBackground="new 0 0 213.7 213.7"
                            xmlSpace="preserve"
                            onClick={() => setToggler(!toggler)}
                          >
                            <polygon
                              className="triangle"
                              fill="none"
                              strokeWidth="7"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeMiterlimit="10"
                              points="73.5,62.5 148.5,105.8 73.5,149.1 "
                            ></polygon>
                            <circle
                              className="circle"
                              fill="none"
                              strokeWidth="7"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeMiterlimit="10"
                              cx="106.8"
                              cy="106.8"
                              r="103.3"
                            ></circle>
                          </svg>
                          <span
                            className="w-trailor text-uppercase"
                            onClick={() => setToggler(!toggler)}
                          >
                            Watch Trailer
                          </span>
                        </Link>
                      </Col>
                    </Row>
                  </div>
                </SwiperSlide>

                <div className="swiper-banner-button-next">
                  <i className="iconly-Arrow-Right-2 icli arrow-icon"></i>
                </div>
                <div className="swiper-banner-button-prev">
                  <i className="iconly-Arrow-Left-2 icli arrow-icon"></i>
                </div>
              </Swiper>
            </div>
          </div>
        </div>
      </section>
      <FsLightbox
        toggler={toggler}
        sources={["/assets/images/video/trailer.mp4"]}
      />
    </Fragment>
  );
});

VideoHeroSlider.displayName = "VideoHeroSlider";
export default VideoHeroSlider;
