// ops/1-assets/1-app-templates/all/movies-prod/v5/nuxt-js/components/CustomButton.vue
<template>
  <div v-if="linkButton === true" class="iq-button link-button">
    <nuxt-link :to="{ name: link }" class="btn text-capitalize position-relative">
      <span class="button-text">{{ buttonTitle }}</span>
    </nuxt-link>
  </div>
  <div v-else class="iq-button">
    <nuxt-link :to="link" class="btn text-uppercase position-relative">
      <span class="button-text">{{ buttonTitle }}</span>
      <i class="fa-solid fa-play"></i>
    </nuxt-link>
  </div>
</template>
<script setup>
defineProps({
  buttonTitle: { type: String, default: '' },
  link: {
    type: Object,
    default: () => {
      return { path: '' };
    },
  },
  linkButton: { type: Boolean, default: false },
});
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/components/CustomButton.jsx
import React, { memo, Fragment } from "react";

// react-router-dom
import { Link } from "react-router-dom";

const CustomButton = memo((props) => {
  return (
    <Fragment>
      {props.linkButton === "true" && (
        <div className="iq-button link-button">
          <Link
            to={props.link}
            className="btn text-capitalize position-relative"
          >
            <span className="button-text">{props.buttonTitle}</span>
          </Link>
        </div>
      )}
      {props.linkButton === "false" && (
        <div className="iq-button">
          <Link
            to={props.link}
            className="btn text-uppercase position-relative"
          >
            <span className="button-text">{props.buttonTitle}{" "}</span>
            <i className="fa-solid fa-play"></i>
          </Link>
        </div>
      )}
    </Fragment>
  );
});

CustomButton.displayName = "CustomButton";
export default CustomButton;
