// ops/1-assets/1-app-templates/react/movies-prod/v5/react/frontend/src/views/MainPages/IndexPage.jsx
import { memo } from "react";

// hero slider
import HomeHeroSlider from "../../components/slider/HomeHeroSlider";

// sections
import ContinueWatching from "../../components/sections/ContinueWatching";
import UpcomingMovies from "../../components/sections/UpcomingMovies";
import LatestMovies from "../../components/sections/LatestMovies";
import VerticalSectionSlider from "../../components/slider/VerticalSectionSlider";
import TrendingSlider from "../../components/sections/Trending";
import SuggestedBlock from "../../components/sections/SuggestedBlock";
import RecommendedTVShow from "../../components/sections/RecommendedTVShow";
import ParallexSection from "../../components/sections/ParallexSection";

//static data
import { verticleLatestMovies, latestMovie } from "../../StaticData/data";

const HomePage = memo(() => {
  const showViewAllLink = true;
  return (
    <>
      <HomeHeroSlider />

      <ContinueWatching slidesPerView={4} />

      <UpcomingMovies paddingY="my-4" />

      <LatestMovies sliderData={latestMovie} paddingY="my-4" />

      <VerticalSectionSlider sliderData={verticleLatestMovies} containerFluid="container-fluid" />

      <SuggestedBlock paddingY="my-4" />

      <ParallexSection />

      <TrendingSlider />

      <RecommendedTVShow paddingY='my-4' />
    </>
  );
});

HomePage.displayName = "HomePage";
export default HomePage;

// ops/1-assets/2-app-templates/all/movies-prod/v5/vue/frontend/src/views/MainPages/IndexPage.vue
<template>
  <HomeHeroSlider></HomeHeroSlider>

  <section class="continue-watching-block">
    <ContinueWatching :slides-per-view="4"></ContinueWatching>
  </section>

  <UpcomingMovies :view="true ? $t('ott_home.view_all') : null" :slides-per-view="6"></UpcomingMovies>

  <LatestMovies :slider-data="latestMovie"></LatestMovies>

  <VerticalSectionSlider :slider-data="verticleLatestMovies" container-fluid="containerFluid"></VerticalSectionSlider>

  <SuggestedBlock></SuggestedBlock>

  <ParallexSection></ParallexSection>

  <TrendingSlider></TrendingSlider>

  <RecommendedTVShow></RecommendedTVShow>
</template>
<script setup>
// Hero Slider
import HomeHeroSlider from '../../components/slider/HomeHeroSlider.vue';

// Sections
import TrendingSlider from '../../components/sections/TrendingSection.vue';
import ContinueWatching from '../../components/sections/ContinueWatching.vue';
import UpcomingMovies from '../../components/sections/UpcomingMovies.vue';
import LatestMovies from '../../components/sections/LatestMovies.vue';
import SuggestedBlock from '../../components/sections/SuggestedBlock.vue';
import RecommendedTVShow from '../../components/sections/RecommendedTVShow.vue';
import ParallexSection from '../../components/sections/ParallexSection.vue';
import VerticalSectionSlider from '../../components/slider/VerticalSectionSlider.vue';

import { verticleLatestMovies, latestMovie } from '../../StaticData/data';
</script>
