// frontend/5-react/2-next/1-next13(pages-router)/2-head-link-image/app1/src/pages/movies/index.tsx
import { GetServerSideProps } from 'next'
import Image from 'next/image'

type Movie = {
  id: number
  title: string
  url: string
  background_image: string
}

type Props = {
  movies: Movie[]
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const res = await fetch('https://yts.mx/api/v2/list_movies.json?sort_by=rating')
  const json = await res.json()

  return {
    props: {
      movies: json.data.movies,
    },
  }
}

export default function SSR({ movies }: Props) {
  return (
    <div>
      <h1>SSR: 무비 리스트</h1>
      {movies.map((movie) => (
        <div key={movie.id}>
          <a href={movie.url}>{movie.title}</a>
          <Image src={movie.background_image} alt={movie.title} width={300} height={169} />
        </div>
      ))}
    </div>
  )
}

// start/8-Students/jung/4-vue/5-todo-app/app1/src/views/Movies.vue
<template>
<div>
    <h1>Movie App</h1>
    <div id="movies">
      <div v-for="movie in movies" :key="movie.id" class="movie">
        <a class="movieTitle" :href="movie.url">{{ movie.title }}</a>
        <img class="movieImage" :src="movie.background_image" :alt="movie.title" />
      </div>
    </div>
  </div></template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'

interface Movie {
  id: number
  title: string
  url: string
  background_image: string
}

const movies = ref<Movie[]>([])

function getMovies() {
  fetch('https://yts.mx/api/v2/list_movies.json?sort_by=rating')
    .then(res => res.json())
    .then(json => {
      movies.value = json.data.movies
    })
}

onMounted(() => {
  getMovies()
})
</script>

<style scoped>
.movieTitle {
  font-size: 20px;
  color: #1a45e1;
  text-decoration: none;
  display: block;
}
.movieImage {
  width: 200px;
  height: auto;
  margin-top: 10px;
}
</style>
