// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/views/ExtraPages/AboutSections/ContactUs.jsx
import { memo, Fragment } from "react";

// react-bootstrap
import { Container, Row, Col, Image } from "react-bootstrap";

//react-router-dom
import { Link } from "react-router-dom";

// img
import img1 from "/assets/images/pages/map.webp";

// the hook
import { useTranslation } from "react-i18next";

const ContactUs = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <section
        className="section-padding"
        style={{ backgroundColor: "var(--bs-gray-900)" }}
      >
        <Container>
          <Row className="about-us-row text-center align-items-center">
            <Col lg="6" md="5">
              <div className="text-center">
                <Image
                  width="497"
                  height="477"
                  src={img1}
                  className=" img-fluid attachment-large size-large"
                  alt=""
                  loading="lazy"
                />
              </div>
            </Col>
            <Col lg="6" md="7">
              <h2 className="text-capitalize text-start">
                {t("about_us.contact_here")}
              </h2>
              <p className="mb-0 text-start">
                {t("about_us.streamit_located")}{" "}
                <Link to="mailto:info@medyapim.com">hello@streamit.com</Link>{" "}
                {t("about_us.tech_related")}
              </p>
              <Row className="mt-2 iq-rtl-direction">
                <Col md="4">
                  <div className="counter">
                    <span className="counter-number">4</span>
                  </div>
                  <div className="counter-title">{t("about_us.branch")}</div>
                </Col>
                <Col md="4">
                  <div className="iq-contact-list">
                    <div className="counter">
                      <span className="counter-number"> 500 + </span>
                    </div>
                    <div className="counter-title">
                      {t("about_us.employee")}
                    </div>
                  </div>
                </Col>
                <Col md="4">
                  <div className="iq-contact-list">
                    <div className="counter">
                      <span className="counter-number"> 1000 + </span>
                    </div>
                    <div className="counter-title">{t("about_us.client")}</div>
                  </div>
                </Col>
              </Row>
            </Col>
          </Row>
        </Container>
      </section>
    </Fragment>
  );
});

ContactUs.displayName = "ContactUs";
export default ContactUs;

// ops/1-assets/2-app-templates/all/movies-prod/v5/vue/frontend/src/views/ExtraPages/AboutSections/ContactUs.vue
<template>
  <section class="section-padding" style="background-color: var(--bs-gray-900)">
    <b-container>
      <b-row class="about-us-row text-center align-items-center">
        <b-col md="6">
          <div class="text-center">
            <img
width="497" height="477" src="/assets/images/pages/map.webp" class="attachment-large size-large" alt=""
              loading="lazy" />
          </div>
        </b-col>
        <b-col md="6">
          <div class="text-left iq-title-box iq-title-default">
            <h2 class="text-capitalize text-start">{{ $t('about_us.contact_here') }}</h2>
            <p class="mb-0 text-start">{{ $t('about_us.streamit_located') }} <a
                href="mailto:info@medyapim.com">hello@streamit.com</a> {{ $t('about_us.tech_related') }}</p>
            <b-row class="mt-2 iq-rtl-direction">
              <b-col md="4">
                <div class="counter">
                  <Vue3autocounter ref="counter" :start-amount="0" :end-amount="4" />
                </div>
                <div class="counter-title">{{ $t('about_us.branch') }}</div>
              </b-col>
              <b-col md="4">
                <div class="iq-contact-list">
                  <div class="counter">
                    <Vue3autocounter ref="counter" :start-amount="0" :end-amount="500" suffix=" +" />
                  </div>
                  <div class="counter-title">{{ $t('about_us.employee') }}</div>
                </div>
              </b-col>
              <b-col md="4">
                <div class="iq-contact-list">
                  <div class="counter">
                    <Vue3autocounter ref="counter" :start-amount="0" :end-amount="1000" suffix=" +" separator="" />
                  </div>
                  <div class="counter-title">{{ $t('about_us.client') }}</div>
                </div>
              </b-col>
            </b-row>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </section>
</template>
<script>
import Vue3autocounter from 'vue3-autocounter';
export default {
  name: 'WidgetBasic',
  components: {
    Vue3autocounter,
  },
};
</script>
