// ops/1-assets/1-templates/vue/movies-prod/v4/code-nuxt/pages/backend/category/AddCategory.vue
<template>
  <b-container fluid>
    <b-row class="row">
      <b-col sm="12">
        <div class="iq-card">
          <div class="iq-card-header d-flex justify-content-between">
            <div class="iq-header-title">
              <h4 class="card-title">
                Add Category
              </h4>
            </div>
          </div>
          <div class="iq-card-body">
            <div class="row">
              <div class="col-lg-12">
                <b-form>
                  <b-form-group>
                    <b-form-input v-model="categories.name" type="text" class="form-control" placeholder="Name" required />
                  </b-form-group>
                  <b-form-group>
                    <b-form-textarea
                      id="text"
                      v-model="categories.description"
                      name="text"
                      rows="5"
                      class="form-control"
                      placeholder="Description"
                      required
                    />
                  </b-form-group>
                  <b-form-group label="Status">
                    <b-form-radio-group
                      v-model="categories.status"
                      :options="options"
                      class="radio-btn"
                      value-field="item"
                      text-field="name"
                      disabled-field="notEnabled"
                    />
                  </b-form-group>
                  <b-form-group>
                    <button class="btn btn-primary mr-1">
                      Submit
                    </button>
                    <button type="reset" class="btn btn-danger">
                      cancel
                    </button>
                  </b-form-group>
                </b-form>
              </div>
            </div>
          </div>
        </div>
      </b-col>
    </b-row>
  </b-container>
</template>
<script>
export default {
  layout: 'BackendLayout',
  name: 'AddCategory',
  data () {
    return {
      formType: false,
      categories: {
        id: 0,
        name: '',
        description: '',
        status: ''
      },
      editing: false,
      newID: 0,
      options: [
        { item: 'enable', name: 'enable' },
        { item: 'disable', name: 'disable' }
      ],
      categoryList: [
        { id: '1', name: 'Drama', description: 'Lorem ipsum dolor sit amet', movie: '20' },
        { id: '2', name: 'Comedy', description: 'Lorem ipsum dolor sit amet', movie: '20' },
        { id: '3', name: 'Romance', description: 'Lorem ipsum dolor sit amet', movie: '20' }
      ]
    }
  },
  computed: {
  },
  mounted () {
    // core.index()
    if ('id' in this.$route.params) {
      const selectedCategory = this.categoryList.filter((item) => {
        if (item.id === this.$route.params.id) {
          return item
        }
      })
      if (selectedCategory) {
        this.categories = selectedCategory[0]
        this.formType = 'Edit'
      }
    }
  },
  methods: {
    saveCategory () {
      const category = this.categoryList
      this.categories.id = parseInt(category[category.length - 1].id) + 1
      this.$store.dispatch('Category/addCategoryAction', this.categories)
      this.$router.push('backend/category/CategoryList')
    },
    updateCategory () {
      this.$store.dispatch('Category/updateCategoryAction', this.categories)
      this.$router.push('backend/category/CategoryList')
    },
    processSave () {
      if ('id' in this.$route.params) {
        this.updateCategory()
      } else {
        this.saveCategory()
      }
    }
  }
}
</script>

// ops/1-assets/1-templates/react/bootstrap-movies-prod/v4/code-react/dashboard/src/views/backend/category/add-category.js
import React from 'react'
import {Container,Row,Col,Form,Button} from 'react-bootstrap'
import Card  from '../../../components/Card'
import {useHistory} from 'react-router-dom'

const AddCategory = () => { 
    let history =useHistory()

    return (
       <> 
            <Container fluid>
                <Row>
                    <Col sm="12">
                        <Card>
                            <Card.Header className="d-flex justify-content-between">
                                <Card.Header.Title>
                                    <h4 className="card-title">Add Category</h4>
                                </Card.Header.Title>
                            </Card.Header>
                            <Card.Body>
                                <Row>
                                    <Col lg="12">
                                        <Form>
                                            <Form.Group>
                                                <Form.Control type="text" placeholder="Name"/>
                                            </Form.Group>
                                            <Form.Group>
                                                <Form.Control as="textarea" id="text" name="text" rows="5" placeholder="Description"></Form.Control>
                                            </Form.Group>
                                            <Form.Group className="radio-box">
                                                <label>Status</label>
                                                <div className="radio-btn">
                                                    <div className="custom-control custom-radio custom-control-inline">
                                                        <input type="radio" id="customRadio6" name="customRadio-1" className="custom-control-input"/>
                                                        <label className="custom-control-label" htmlFor="customRadio6">enable</label>
                                                    </div>
                                                    <div className="custom-control custom-radio custom-control-inline">
                                                        <input type="radio" id="customRadio7" name="customRadio-1" className="custom-control-input"/>
                                                        <label className="custom-control-label" htmlFor="customRadio7">disable </label>
                                                    </div>
                                                </div>
                                            </Form.Group>
                                            <Form.Group className="form-group">
                                                <Button type="button" onClick={()=> history.push('/category-list')}variant=" btn-primary">Submit</Button>{' '}
                                                <Button type="reset" variant=" btn-danger">Cancel</Button>
                                            </Form.Group>
                                        </Form>
                                    </Col>
                                </Row>
                            </Card.Body>
                        </Card>
                    </Col>
                </Row>
            </Container>

       </>
    )
}
export default AddCategory;
