// ops/1-assets/2-app-templates/all/movies-prod/v4/code-vue/src/views/FrontendPages/AboutPages/ContactUs.vue
<template>
    <div class="container-fluid p-0" >
            <div class="map-container" style=" left: 0px;">
               <div class="container">
                  <div class="row about-us-row text-center align-items-center">
                     <div class="col-md-6">
                        <div class="text-center">
                           <img width="497" height="477" src="@/assets/images/frontend/about-us/06.jpg" class="attachment-large size-large" alt="" loading="lazy" >
                        </div>
                     </div>
                     <div class="col-md-6">
                        <div class=" text-left iq-title-box iq-title-default">
                           <h2 class="iq-title">Contact Us Here</h2>
                           <p class="iq-title-desc">Streamit is located in Los Angeles city and you can contact us at <a href="#">hello@streamit.com</a> for any tech-related support and assistance. We love to hear from our Streamit users.</p>
                           <div class="row mt-2 iq-rtl-direction">
                              <div class="col-md-4">
                                 <div class="counter">
                                    <span class="counter-number" data-duration="2000" data-to-value="4" data-from-value="0" data-delimiter=",">4</span>
                                 </div>
                                 <div class="counter-title">Branch</div>
                              </div>
                              <div class="col-md-4">
                                 <div class="iq-contact-list" data-element_type="column">
                                 <div class="counter">
                                    <span class="counter-number" data-duration="2000" data-to-value="4" data-from-value="0" data-delimiter=",">
                                       500+
                                    </span>
                                 </div>
                                 <div class="counter-title">Employee</div>
                                 </div>
                              </div>
                              <div class="col-md-4">
                                 <div class="iq-contact-list" data-element_type="column">
                                 <div class="counter">
                                    <span class="counter-number" data-duration="2000" data-to-value="4" data-from-value="0" data-delimiter=",">
                                       1,000+
                                    </span>
                                 </div>
                                 <div class="counter-title">Clients</div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
</template>
<script>
export default {
  name: 'ContactUs'
}
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/next-js/src/pages/extra/AboutSections/ContactUs.tsx
import { memo, Fragment } from "react";

// react-bootstrap
import { Container, Row, Col } from 'react-bootstrap'

// next link
import Link from "next/link";

// next image
import Image from "next/image"

//plugins
import CountUp from 'react-countup';

const ContactUs = memo(() => {
  return (
    <Fragment>
      <section className="section-padding" style={{ backgroundColor: "var(--bs-gray-900)" }}>
        <Container>
          <Row className="about-us-row text-center align-items-center">
            <Col lg="6" md="5">
              <div className="text-center">
                <Image width="497" height="477" src="/assets/images/pages/map.webp" className="attachment-large size-large" alt="" loading="lazy" />
              </div>
            </Col>
            <Col lg="6" md="7">
              <h2 className="text-capitalize text-start">Contact Us Here</h2>
              <p className="mb-0 text-start">Streamit is located in Los Angeles city and you can contact us at <Link href="mailto:info@medyapim.com">hello@streamit.com</Link> for any tech-related support and assistance. We love to hear from our Streamit users.</p>
              <Row className="mt-2 iq-rtl-direction">
                <Col md="4">
                  <div className="counter">
                    <CountUp start={0} end={4} duration={1.5} enableScrollSpy className="counter-number" />
                  </div>
                  <div className="counter-title">Branch</div>
                </Col>
                <Col md="4">
                  <div className="iq-contact-list">
                    <div className="counter">
                      <CountUp className="counter-number" start={0} end={500} duration={1.5} enableScrollSpy /> <span> +</span>
                    </div>
                    <div className="counter-title">Employee</div>
                  </div>
                </Col>
                <Col md="4">
                  <div className="iq-contact-list">
                    <div className="counter">
                      <CountUp className="counter-number" start={0} end={1000} duration={1.5} enableScrollSpy /> <span> +</span>
                    </div>
                    <div className="counter-title">Clients</div>
                  </div>
                </Col>
              </Row>
            </Col>
          </Row>
        </Container>
      </section>
    </Fragment>
  )
});

ContactUs.displayName = "ContactUs";
export default ContactUs;
