// ops/1-assets/2-app-templates/all/movies-prod/v5/next-js/src/pages/extra/about-us.tsx
import { Fragment, memo } from "react";

//components
import TeamSection from "./AboutSections/TeamSection";
import ContactUs from "./AboutSections/ContactUs";
import WorkSection from "./AboutSections/WorkSection";

//custom hook
import { useBreadcrumb } from "@/utilities/usePage";

const AboutUs = memo(() => {
  useBreadcrumb('About us')
  return (
    <Fragment>
      <TeamSection></TeamSection>
      <ContactUs></ContactUs>
      <WorkSection></WorkSection>
    </Fragment>
  );
});

AboutUs.displayName = "AboutUs";
export default AboutUs;

// ops/1-assets/1-templates/vue/movies-prod/v5/nuxt-js/pages/extra/about-us.vue
<template>
  <section class="section-padding">
    <team-section></team-section>
  </section>
  <contact-us></contact-us>
  <work-section></work-section>
</template>

<script setup>
//components
import TeamSection from "./AboutSections/TeamSection.vue";
import ContactUs from "./AboutSections/ContactUs.vue";
import WorkSection from "./AboutSections/WorkSection.vue";

//custom hooks
import { useBreadcrumb } from "~/utilities/usePage";

useBreadcrumb("About Us");
</script>
