// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/views/BlogPages/ListPage.jsx
import React, { Fragment, memo } from "react";

//react bootstrap
import { Container, Row, Col } from "react-bootstrap";

//components
import CardBlogList from "../../components/cards/CardBlogList";
import DetailMetaList from "../../components/blog/DetailMetaList";
import BreadCrumbWidget from "../../components/BreadcrumbWidget";

//static data
import { blogs } from "../../StaticData/blogs";

// the hook
import { useTranslation } from "react-i18next";

const BlogList = memo((props) => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <BreadCrumbWidget title={t(props.title)} />
      <div className="section-padding">
        <Container>
          <Row>
            <Col lg="8" sm="12">
              {blogs.slice(0, 7).map((item, index) => {
                return (
                  <CardBlogList
                    key={index}
                    slug={item.slug}
                    title={t(item.title)}
                    thumbnail={item.thumbnail}
                    blogDate={item.blogDate}
                    username={t(item.username)}
                    categories={t(item.categories)}
                    tags={item.tags}
                    description={t(item.description)}
                  />
                );
              })}
            </Col>
            <Col lg="4" sm="12">
              <DetailMetaList></DetailMetaList>
            </Col>
          </Row>
        </Container>
      </div>
    </Fragment>
  );
});

BlogList.displayName = "BlogList";
export default BlogList;

// ops/1-assets/1-templates/vue/movies-prod/v5/vue/frontend/src/views/BlogPages/ListPage.vue
<template>
  <div class="section-padding">
    <div class="container">
      <b-row>
        <b-col lg="8" sm="12">
          <div v-for="data in blogs" :key="data">
            <card-blog-list :title="$t(data.title)" :slug="data.slug" :thumbnail="data.thumbnail" :tags="data.tags" :username="data.username" :description="data.description" :date="data.blogDate" :categories="data.categories"></card-blog-list>
          </div>
        </b-col>
        <b-col lg="4" sm="12">
          <detail-meta-list></detail-meta-list>
        </b-col>
      </b-row>
    </div>
  </div>
</template>
<script setup>
import CardBlogList from '../../components/cards/CardBlogList.vue';
import { blogs } from '../../StaticData/blogs';

import DetailMetaList from '../../components/blog/DetailMetaList.vue';
</script>
