// ops/1-assets/1-app-templates/vue/movies-prod/v5/nuxt-js/pages/tv-shows/index.vue
<template>
  <TvShowHeroSlider></TvShowHeroSlider>

  <TVPopularShows></TVPopularShows>

  <BestOfInternationalShows></BestOfInternationalShows>

  <ShowsWeRecommend></ShowsWeRecommend>
</template>

<script setup>
// Hero Slider
import TvShowHeroSlider from "../../components/slider/TvShowHeroSlider.vue";

// sections
import TVPopularShows from "../../components/sections/TVPopularShows.vue";
import BestOfInternationalShows from "../../components/sections/BestOfInternationalShows.vue";
import ShowsWeRecommend from "../../components/sections/ShowsWeRecommend.vue";
import { useEnterExit } from "~/utilities/usePage";

import { onMounted } from "vue";
import { useStremit } from "~/store/streamit";

const store = useStremit();

onMounted(() => {
  store.breadcrumbSet({ show: false, name: "" });
});

useEnterExit();
</script>

// ops/1-assets/1-app-templates/react/movies-prod/v5/next-js/src/pages/tv-shows/index.tsx
import { memo, Fragment } from "react";

//hero-slider
import TvShowHeroSlider from "@/components/slider/TvShowHeroSlider";

//sections
import TVPopularShows from "@/components/sections/TVPopularShows";
import BestOfInternationalShows from "@/components/sections/BestOfInternationalShows";
import ShowsWeRecommend from "@/components/sections/ShowsWeRecommend";

import { useEnterExit } from "@/utilities/usePage";

const TvShows = memo(() => {
  useEnterExit()
  return (
    <Fragment>
      <TvShowHeroSlider />
      <TVPopularShows />
      <BestOfInternationalShows />
      <ShowsWeRecommend />
    </Fragment>
  );
});

TvShows.displayName = "TvShows";
export default TvShows;
