// ops/1-assets/1-app-templates/react/movies-prod/v5/next-js/src/components/BreadcrumbWidget.tsx
import { Fragment, memo } from "react";

//react bootstrap
import { Breadcrumb, Container, Row, Col } from "react-bootstrap";

//function
import { generateImgPath } from "../StaticData/data";

//react-redux
import { useSelector } from "react-redux";
import { getBreadcrumb } from "@/store/streamit/selectors";

//img
const imagePath = generateImgPath("/assets/images/pages/01.webp");

const BreadCrumbWidget = memo(() => {
  const breadcrumb = useSelector(getBreadcrumb)
  return (
    <Fragment>
      {breadcrumb.show ?
        <div
          className="iq-breadcrumb"
          style={{ backgroundImage: `url(${imagePath})` }}
        >
          <Container fluid>
            <Row className="align-items-center">
              <Col sm="12">
                <nav className="text-center">
                  <h2 className="title text-capitalize">{breadcrumb.name}</h2>
                  <Breadcrumb
                    className="main-bg"
                    listProps={{
                      className: "text-center justify-content-center",
                    }}
                  >
                    <Breadcrumb.Item>Home</Breadcrumb.Item>
                    <Breadcrumb.Item active>{breadcrumb.name}</Breadcrumb.Item>
                  </Breadcrumb>
                </nav>
              </Col>
            </Row>
          </Container>
        </div> : ''}
    </Fragment>
  );
});

BreadCrumbWidget.displayName = "BreadCrumbWidget";
export default BreadCrumbWidget;

// ops/1-assets/1-app-templates/react/movies-prod/v5/nuxt-js/components/BreadcrumbWidget.vue
<template>
  <div
    class="iq-breadcrumb"
    :style="`background-image: url(${generateImgPath(
      '/assets/images/pages/01.webp'
    )})`"
  >
    <b-container fluid>
      <b-row class="align-items-center">
        <b-col>
          <nav aria-label="breadcrumb" class="text-center">
            <h2 class="title">{{ pageName }}</h2>
            <ol class="breadcrumb justify-content-center">
              <li class="breadcrumb-item">
                <nuxt-link :to="{ name: 'index' }">{{
                  $t("header.home")
                }}</nuxt-link>
              </li>
              <li class="breadcrumb-item active">
                {{ pageName }}
              </li>
            </ol>
          </nav>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>
<script setup>
import { generateImgPath } from "../StaticData/data";
import { useStremit } from "~/store/streamit";
const store = useStremit();
const pageName = computed(() => store.breadcrumb.name);
</script>
