// ops/1-assets/1-templates/vue/movies-prod/v5/react/frontend/src/components/BreadcrumbWidget.jsx
import { Fragment, memo } from "react";

//react bootstrap
import { Breadcrumb, Container, Row, Col } from "react-bootstrap";

//function
import { generateImgPath } from "../StaticData/data";

//img
const imagePath = generateImgPath("/assets/images/pages/01.webp");
// the hook
import { useTranslation } from "react-i18next";

const BreadCrumbWidget = memo((props) => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <div
        className="iq-breadcrumb"
        style={{ backgroundImage: `url(${imagePath})` }}
      >
        <Container fluid>
          <Row className="align-items-center">
            <Col sm="12">
              <nav className="text-center">
                <h2 className={`title ${props.class === false ? '' : 'text-capitalize'}`}>{t(props.title)}</h2>
                <Breadcrumb
                  className="main-bg"
                  listProps={{
                    className: "text-center justify-content-center",
                  }}
                >
                  <Breadcrumb.Item>{t("header.home")}</Breadcrumb.Item>
                  <Breadcrumb.Item active>{t(props.title)}</Breadcrumb.Item>
                </Breadcrumb>
              </nav>
            </Col>
          </Row>
        </Container>
      </div>
    </Fragment>
  );
});

BreadCrumbWidget.displayName = "BreadCrumbWidget";
export default BreadCrumbWidget;

// ops/1-assets/1-app-templates/react/movies-prod/v5/nuxt-js/components/BreadcrumbWidget.vue
<template>
  <div
    class="iq-breadcrumb"
    :style="`background-image: url(${generateImgPath(
      '/assets/images/pages/01.webp'
    )})`"
  >
    <b-container fluid>
      <b-row class="align-items-center">
        <b-col>
          <nav aria-label="breadcrumb" class="text-center">
            <h2 class="title">{{ pageName }}</h2>
            <ol class="breadcrumb justify-content-center">
              <li class="breadcrumb-item">
                <nuxt-link :to="{ name: 'index' }">{{
                  $t("header.home")
                }}</nuxt-link>
              </li>
              <li class="breadcrumb-item active">
                {{ pageName }}
              </li>
            </ol>
          </nav>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>
<script setup>
import { generateImgPath } from "../StaticData/data";
import { useStremit } from "~/store/streamit";
const store = useStremit();
const pageName = computed(() => store.breadcrumb.name);
</script>
