// ops/1-assets/1-templates/vue/movies-prod/v5/next-js/src/pages/movies/index.tsx
import { memo } from "react";

// hero slider
import MovieHeroSlider from "@/components/slider/MovieHeroSlider";

// section
import PopularMovies from "@/components/sections/PopularMovies";
import SpecialsLatestMovies from "@/components/sections/Specials&LatestMovies";
import MoviesRecommendedForYou from "@/components/sections/MoviesRecommendedForYou";

import { useEnterExit } from "@/utilities/usePage";

const Movies = memo(() => {
    useEnterExit()
    return (
        <>

            <MovieHeroSlider />
            <PopularMovies />
            <SpecialsLatestMovies />
            <MoviesRecommendedForYou />

        </>
    );
});

Movies.displayName = "Movies";
export default Movies;

// ops/1-assets/1-app-templates/vue/movies-prod/v5/nuxt-js/pages/movies/index.vue
<template>
  <MovieHeroSlider></MovieHeroSlider>

  <PopularMovies></PopularMovies>

  <SpecialsLatestMovies></SpecialsLatestMovies>

  <MoviesRecommendedForYou></MoviesRecommendedForYou>
</template>

<script setup>
// Hero Slider
import MovieHeroSlider from "../../components/slider/MovieHeroSlider.vue";

// Sections
import PopularMovies from "../../components/sections/PopularMovies.vue";
import SpecialsLatestMovies from "../../components/sections/Specials&LatestMovies.vue";
import MoviesRecommendedForYou from "../../components/sections/MoviesRecommendedForYou.vue";
import { useEnterExit } from "~/utilities/usePage";

import { onMounted } from "vue";
import { useStremit } from "~/store/streamit";

const store = useStremit();

onMounted(() => {
  store.breadcrumbSet({ show: false, name: "" });
});

useEnterExit();
</script>
