// ops/1-assets/1-app-templates/vue/movies-prod/v4/code-react/frontend/src/views/backend/show/add-show.js
import React from 'react'
import { Container, Row, Col, Form, Button} from 'react-bootstrap'
import Card  from '../../../components/Card'
import { useHistory } from 'react-router-dom'

const AddShow = () => { 
   
   let history =useHistory()
    
   return (
        <> 
            <Container fluid>
               <Row>
                  <Col sm="12">
                     <Card>
                        <Card.Header className="d-flex justify-content-between">
                           <Card.Header.Title>
                              <h4 className="card-title">Add Show</h4>
                           </Card.Header.Title>
                        </Card.Header>
                        <Card.Body>
                           <Form>
                              <Row>
                                 <Col md="6" className="form-group">
                                    <Form.Control type="text" placeholder="Title"/>
                                 </Col>
                                 <Col md="6" className="form-group">
                                    <select className="form-control" id="exampleFormControlSelect1">
                                       <option defaultValue disabled="">Choose Language</option>
                                       <option>English</option>
                                       <option>Hindi</option>
                                       <option>Tamil</option>
                                       <option>Gujarati</option>
                                    </select>                                 
                                 </Col>
                                 <Col md="6" className="form-group">
                                    <select className="form-control" id="exampleFormControlSelect2">
                                       <option defaultValue disabled="">Show Category</option>
                                       <option>Comedy</option>
                                       <option>Crime</option>
                                       <option>Drama</option>
                                       <option>Horror</option>
                                       <option>Romance</option>
                                    </select>
                                 </Col>
                                 <Col md="6" className="form-group">
                                    <select className="form-control" id="exampleFormControlSelect3">
                                       <option defaultValue disabled="">Choose quality</option>
                                       <option>Full HD</option>
                                       <option>HD</option>
                                    </select>
                                 </Col>
                                 <Col md="6" className="form_gallery form-group">
                                    <label id="gallery2" htmlFor="form_gallery-upload">Upload Image</label>
                                    <input data-name="#gallery2" id="form_gallery-upload" name="gallery"
                                       className="form_gallery-upload" type="file" accept=".png, .jpg, .jpeg"/>
                                 </Col>
                                 <Col md="6" className="form_gallery form-group">
                                    <label id="gallery3" htmlFor="show2">Upload Show Banner</label>
                                    <input data-name="#gallery3" id="show2" name="gallery" className="form_gallery-upload"
                                       type="file" accept=".png, .jpg, .jpeg"/>
                                 </Col>
                                 <Form.Group className="col-12">
                                    <Form.Control as="textarea" id="text1" name="text" rows="5" placeholder="Description"></Form.Control>
                                 </Form.Group>
                              </Row>
                              <Row>
                                 <div className="col-12">
                                    <h5 className="text-white mb-3">Add Seasons</h5>
                                 </div>
                              </Row>
                              <Row>
                                 <Col lg="7">
                                    <Row>
                                       <Col md="6" className="form-group">
                                          <select className="form-control" id="exampleFormControlSelect5">
                                             <option disabled>Select Seasons</option>
                                             <option>Season 1</option>
                                             <option>Season 2</option>
                                             <option>Season 3</option>
                                             <option>Season 4</option>
                                             <option>Season 5</option>
                                          </select>
                                       </Col>
                                       <Col md="6" className="form-group">
                                          <Form.Control type="text" placeholder="Episode No."/>
                                       </Col>
                                       <Col md="6" className="form-group">
                                          <Form.Control type="text" placeholder="Episode Name"/>
                                       </Col>
                                       <Col md="6" className="form_gallery form-group">
                                          <label id="gallery4" htmlFor="show3">Upload Image</label>
                                          <input data-name="#gallery4" id="show3" name="gallery" className="form_gallery-upload" type="file" accept=".png, .jpg, .jpeg"/>
                                       </Col>
                                       <Col md="6" className="form-group">
                                          <Form.Control type="text" placeholder="Running Time in Minutes"/>
                                       </Col>
                                       <Col md="6" className="form-group">
                                          <Form.Control className="date-input basicFlatpickr" type="text" placeholder="Selete Date"/>
                                       </Col>
                                       <Form.Group className="col-12">
                                          <Form.Control as="textarea" id="text" name="text" rows="5" placeholder="Description"></Form.Control>
                                       </Form.Group>
                                    </Row>
                                 </Col>
                                 <Col lg="5">
                                    <div className="d-block position-relative">
                                       <div className="form_video-upload">
                                          <input type="file" accept="video/mp4,video/x-m4v,video/*" multiple/>
                                          <p>Upload video</p>
                                       </div>
                                    </div>
                                 </Col>
                              </Row>
                              <Row>
                                 <Form.Group className="col-12">
                                    <Button type="button" onClick={()=> history.push('/show-list')}variant="primary">Submit</Button>{' '}
                                    <Button type="reset" variant="danger">Cancel</Button>
                                 </Form.Group>
                              </Row>
                           </Form>
                        </Card.Body>
                     </Card>
                  </Col>
               </Row>
            </Container>
         </>
   )
}
export default AddShow;

// ops/1-assets/1-templates/vue/movies-prod/v4/code-vue/src/views/BackendPages/Show/AddShow.vue
<template>
  <b-container fluid>
    <b-row class="row">
      <b-col sm="12">
        <div class="iq-card">
            <div class="iq-card-header d-flex justify-content-between">
              <div class="iq-header-title">
                  <h4 class="card-title">Add Show</h4>
              </div>
            </div>
            <div class="iq-card-body">
              <b-form @submit.prevent="processSave()">
                  <b-row class="row">
                    <b-form-group class="col-md-6">
                        <input v-model="shows.name" type="text" class="form-control" placeholder="Title" required>
                    </b-form-group>
                    <b-form-group class="col-md-6 ">
                      <b-form-select  class="form-control" v-model="shows.lang" :options="languageSelect" required>
                        <option value="">Select Language</option>
                      </b-form-select>
                    </b-form-group>
                    <b-form-group class="col-md-6 ">
                       <b-form-select v-model="shows.category"  class="form-control" required>
                          <option value="">Select Category</option>
                              <b-select-option  v-model="selectOption.name " v-for="(selectOption, indexOpt) in categoryList"  :key="indexOpt"
                               >
                                  {{ selectOption.name }}
                              </b-select-option>
                        </b-form-select>
                    </b-form-group>
                    <b-form-group class="col-md-6 " required>
                       <b-form-select class="form-control" v-model="shows.quality" :options="qualitySelect">
                         <option value="">Select Quality</option>
                       </b-form-select>
                    </b-form-group>
                      <b-form-group class="col-12 form_gallery">
                          <b-form-file
                            @change="fileUpload"
                            placeholder="Upload Image"
                            class="form_gallery-upload"
                            accept="image/jpeg, image/png, image/gif"
                          ></b-form-file>
                        </b-form-group>
                    <b-form-group class="col-md-6 form_gallery ">
                        <label id="gallery3" for="show2">Upload Show Banner</label>
                        <input data-name="#gallery3" id="show2" name="gallery" class="form_gallery-upload"
                          type="file" accept=".png, .jpg, .jpeg">
                    </b-form-group>
                    <b-form-group class="col-12 ">
                        <b-form-textarea v-model="shows.description" id="text1" name="text" rows="5" class="form-control"
                          placeholder="Description" required></b-form-textarea>
                    </b-form-group>
                  </b-row>
                  <b-row class="row">
                    <div class="col-12 form-group">
                        <button type="submit" class=" btn btn-primary mr-2">Submit</button>
                        <button type="reset" class="btn btn-danger">cancel</button>
                    </div>
                  </b-row>
              </b-form>
            </div>
        </div>
      </b-col>
    </b-row>
  </b-container>
</template>
<script>
import { core } from '../../../config/pluginInit'
import { mapGetters } from 'vuex'

export default {
  name: 'AddShow',
  mounted () {
    core.index()
    if ('id' in this.$route.params) {
      const selectedShow = this.showList.filter(item => {
        if (item.id === this.$route.params.id) {
          return item
        }
      })
      if (selectedShow) {
        this.shows = selectedShow[0]
      }
    }
  },
  computed: {
    ...mapGetters({
      categoryList: 'Category/categoryState',
      showList: 'Show/showState'
    })
  },
  data () {
    return {
      item: {},
      defultImage: require('../../../assets/images/show-thumb/01.jpg'),
      shows: {
        id: this.$route.params.id1,
        name: '',
        category: '',
        quality: '',
        lang: '',
        file: '',
        banner: '',
        description: '',
        episodes: []
      },
      selected: null,
      qualitySelect: [
        { value: null, text: 'Choose quality', disabled: true },
        { value: 'FULLHD', text: 'FULLHD' },
        { value: 'HD', text: 'HD' }
      ],
      languageSelect: [
        { value: null, text: 'Choose Language', disabled: true },
        { value: 'English', text: 'English' },
        { value: 'Hindi', text: 'Hindi' },
        { value: 'Tamil', text: 'Tamil' },
        { value: 'Gujarati', text: 'Gujarati' }
      ]
    }
  },
  methods: {
    saveShow () {
      const show = this.showList
      this.shows.id = parseInt(show[show.length - 1].id) + 1
      this.$store.dispatch('Show/addShowAction', this.shows)
      this.$router.push('/show/show-list')
    },
    updateShow () {
      this.shows.file = this.defultImage
      this.$store.dispatch('Show/updateShowAction', this.shows)
      this.$router.push('/show/show-list')
    },
    processSave () {
      if ('id' in this.$route.params) {
        this.updateShow()
      } else {
        this.saveShow()
      }
    },
    fileUpload (e) {
      const reader = new FileReader()
      reader.readAsDataURL(e.target.files[0])
      reader.onload = () => {
        this.shows.file = reader.result
      }
    }
  }
}
</script>
