// ops/1-assets/1-templates/vue/movies-prod/v5/vue/frontend/src/components/sections/SuggestedBlock.vue
<template>
  <!-- Suggested-Block start -->
  <SectionSlider :title="$t(title)" :list="suggested" :slides-per-view="6" class="suggested-block streamit-block" margin-padding="px-3 my-4">
    <template #headerLink>
      <router-link :to="{ name: 'landing-page.view-all' }" class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('ott_home.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :movie-time="data.movieTime" :watchlist-link="{ path: '/playlist' }" :link="{ path: '/movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Suggested-Block end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { suggested } from '../../StaticData/data';
const title = ref('home.suggested_block');
</script>

// ops/1-assets/1-app-templates/react/movies-prod/v5/react/frontend/src/components/sections/SuggestedBlock.jsx
import { Fragment, memo, useState } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../../components/cards/CardStyle";

//static data
import { suggested } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const SuggestedBlock = memo((props) => {
  const { t } = useTranslation();

  return (
    <Fragment>
      <SectionSlider
        title={t("home.suggested_block")}
        list={suggested}
        className="suggested-block streamit-block"
        slidesPerView="6"
        paddingY={props.paddingY}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

SuggestedBlock.DisplayName = "SuggestedBlock";
export default SuggestedBlock;
