// frontend/6-vue/5-nuxt3/2-nuxt3-client/4-pages/app1/pages/list.vue
<template>
  <div>
    <h2 class="title">상품목록</h2>
    <div>
      <div v-for="item in items" :key="item.id">
        {{ item.name }} ${{ item.price }}
        <Cart :price="item.price" />
      </div>
    </div>
  </div>
</template>

<script setup>
import Cart from '@/components/Cart.vue'

const items = [
  { id: 1, name: "토마토", price: 5 },
  { id: 2, name: "파스타", price: 30 },
  { id: 3, name: "코코넛", price: 7 }
]
</script>

<style scoped>
.title {
  font-size: 24px;
  font-weight: bold;
  color: gray;
}

.item {
  color: gray;
  font-size: 14px;
}

.item:hover {
  color: pink;
}
</style>

// frontend/4-react/2-함수형/2-next-REST/1-next-front/1-next/2-next-syntax/5-props/app1/src/app/list/page.js
import React from "react"
import styles from "./page.module.css"
import Cart from "components/Cart"

export default function List() {
  const items = [
    { id: 1, name: "토마토", price: 5 },
    { id: 2, name: "파스타", price: 30 },
    { id: 3, name: "코코넛", price: 7 },
  ]

  const render = items.map((item) => {
    return (
      <div key={item.id}>
        {item.name} ${item.price}
        <Cart price={price} />
      </div>
    )
  })

  return (
    <div>
      <h2 className={styles.title}>상품목록</h2>
      <div>{render}</div>
    </div>
  )
}
