// frontend/5-react/2-next-REST/1-next-front/1-next/2-next-syntax/6-useClient/app1/src/app/components/Cart/index.js
"use client"

import React, { useState } from "react"

export default function Cart({ price }) {
  const [count, setCount] = useState(0)

  const onIncrease = () => {
    setCount(count + 1)
  }

  const onDecrease = () => {
    count > 0 && setCount(count - 1)
  }

  return (
    <div>
      <div>수량: {count}</div>
      <div>가격: {count * price}</div>
      <button onClick={onIncrease}>+</button>
      <button onClick={onDecrease}>-</button>
    </div>
  )
}

// frontend/6-vue/2-nuxt3/2-nuxt3-client/4-pages/app1/components/Cart.vue
<template>
  <div>
    <div>수량: {{ count }}</div>
    <div>가격: {{ count * price }}</div>
    <button @click="onIncrease">+</button>
    <button @click="onDecrease">-</button>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const props = defineProps({
  price: Number
})

const count = ref(0)

const onIncrease = () => {
  count.value += 1
}

const onDecrease = () => {
  if (count.value > 0) {
    count.value -= 1
  }
}
</script>
