// start/8-Students/jung/4-vue/5-todo-app/app1/src/views/Movies.vue
<template>
<div>
    <h1>Movie App</h1>
    <div id="movies">
      <div v-for="movie in movies" :key="movie.id" class="movie">
        <a class="movieTitle" :href="movie.url">{{ movie.title }}</a>
        <img class="movieImage" :src="movie.background_image" :alt="movie.title" />
      </div>
    </div>
  </div></template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'

interface Movie {
  id: number
  title: string
  url: string
  background_image: string
}

const movies = ref<Movie[]>([])

function getMovies() {
  fetch('https://yts.mx/api/v2/list_movies.json?sort_by=rating')
    .then(res => res.json())
    .then(json => {
      movies.value = json.data.movies
    })
}

onMounted(() => {
  getMovies()
})
</script>

<style scoped>
.movieTitle {
  font-size: 20px;
  color: #1a45e1;
  text-decoration: none;
  display: block;
}
.movieImage {
  width: 200px;
  height: auto;
  margin-top: 10px;
}
</style>

// start/9-workspace/lee/2-react/1-syntax/4-newsapp/app1/src/components/Movies.js
import React, { useState, useEffect } from 'react'
import Loading from './Loading'
import './Movies.css'

export default function Movies() {
  const [movies, setMovies] = useState([])
  const [isLoading, setIsLoading] = useState(false)
  
  useEffect(() => {
    setIsLoading(true)
    // fetch('https://yts.mx/api/v2/list_movies.json?sort_by=rating')
    fetch('https://yts.mx/api/v2/list_movies.json')
      .then(res => res.json())
      .then(json => { setMovies(json.data.movies); setIsLoading(false) })
  }, [setMovies, setIsLoading])

  const render = () => {
    console.log('movies: ', movies)
    return movies.map(item => {
      return (
        <div key={item.id} className="movieContainer">
          <a className="movieTitle" href={item.url}>{item.title} ({item.year}) {item.rating >= 9 && '🔥'}</a>
          <div className="movieDetail">
            <img className="movieImage" src={item.large_cover_image} alt={item.title} />
            <div className="movieDescription">
              <div className={item.rating >= 9 ? 'good' : item.rating >=7 ? 'notBad' : 'bad'}>평점: {item.rating ? item.rating + '/ 10점' : '정보없음'} </div>
              <div>장르 : {item.genres.join(', ')}</div>
              <div>상영시간 : {item.runtime ? item.runtime + '분' : '정보없음'}</div>
              <div>요약 : {item.summary || '정보없음'}</div>
              <div>토렌트 : {item.torrents.map((tor, idx) => { return (
                <span>
                  <a href={tor.url}>#{idx + 1}</a>{' '}
                </span>
              )})}
              </div>
            </div>
          </div>
        </div>
      )
    })
  }

  return (
    <>
      <h1>Movie App</h1>
      <div>{ isLoading ? <Loading /> : render()}</div>
    </>
  )
}
