// ops/1-assets/1-templates/vue/movies-prod/v5/next-js/src/components/CustomButton.tsx
import React, { memo, Fragment } from "react";

// react-router-dom
import Link from 'next/link'

interface props{
  linkButton: string,
  link: string,
  buttonTitle: string
}

const CustomButton = memo((props : props) => {
  return (
    <Fragment>
      {props.linkButton === "true" && (
        <div className="iq-button link-button">
          <Link
            href={props.link}
            className="btn text-capitalize position-relative"
          >
            <span className="button-text">{props.buttonTitle}</span>
          </Link>
        </div>
      )}
      {props.linkButton === "false" && (
        <div className="iq-button">
          <Link
            href={props.link}
            className="btn text-uppercase position-relative"
          >
            <span className="button-text">{props.buttonTitle}</span>
            <i className="fa-solid fa-play"></i>
          </Link>
        </div>
      )}
    </Fragment>
  );
});

CustomButton.displayName = "CustomButton";
export default CustomButton;

// ops/1-assets/2-app-templates/all/movies-prod/v5/vue/frontend/src/components/CustomButton.vue
<template>
  <div v-if="linkButton === true" class="iq-button link-button">
    <router-link :to="link" class="btn text-capitalize position-relative">
      <span class="button-text">{{ buttonTitle }}</span>
    </router-link>
  </div>
  <div v-else class="iq-button">
    <router-link :to="link" class="btn text-uppercase position-relative">
      <span class="button-text">{{ buttonTitle }}</span>
      {{ '' }}
      <i class="fa-solid fa-play"></i>
    </router-link>
  </div>
</template>
<script setup>
defineProps({
  buttonTitle: { type: String, default: '' },
  link: {
    type: Object,
    default: () => {
      return { path: '' };
    },
  },
  linkButton: { type: Boolean, default: false },
});
</script>
