// frontend/5-vue/1-vue3/7-BFF/2-bff-client-미완(3부터)/old/6-client-mutation-update(teams)/app1/src/views/Teams.vue
<template>
  <div id="teams" class="component">
    <aside>
      <ApolloQuery :query="GET_TEAMS">
        <template slot-scope="{ result: { loading, error, data } }">
          <p v-if="loading" class="loading">Loading...</p>
          <p v-if="error" class="error">Error :(</p>
          <aside v-else>
            <ul>
              <li v-for="team in data.teams" :key="team.id">
                <span class="teamItemTitle" @click="selectTeam(team.id)">Team {{team.id}} : {{team.manager}}'s</span>
                <ul class="teamMembers">
                  <li v-for="member in team.members" :key="member.id">
                    {{roleIcons[member.role]}} {{member.first_name}} {{member.last_name}}
                  </li>
                </ul>
              </li>
            </ul>
          </aside>
        </template>
      </ApolloQuery>
    </aside>
    <section class="contents">
      <div v-if="selectedTeam" class="inputContainer">
        <table>
          <tr v-if="contentId !== 0">
            <td>Id</td>
            <td>{{contentId}}</td>
          </tr>
          <tr>
            <td>Manager</td>
            <td>
              <input type="text" name="manager" v-model="inputs.manager">
            </td>
          </tr>
          <tr>
            <td>Office</td>
            <td>
              <input type="text" name="office" v-model="inputs.office">
            </td>
          </tr>
          <tr>
            <td>Extension Number</td>
            <td>
              <input type="text" name="extension_number" v-model="inputs.extension_number">
            </td>
          </tr>
          <tr>
            <td>Mascot</td>
            <td>
              <input type="text" name="mascot" v-model="inputs.mascot">
            </td>
          </tr>
          <tr>
            <td>Cleaning Duty</td>
            <td>
              <input type="text" name="cleaning_duty" v-model="inputs.cleaning_duty">
            </td>
          </tr>
          <tr>
            <td>Project</td>
            <td>
              <input type="text" name="project" v-model="inputs.project">
            </td>
          </tr>
        </table>
          <div class="buttons" v-if="contentId === 0">
            <button>Submit</button>
          </div>
          <div class="buttons" v-else>
            <button v-on:click="editTeam(contentId)">Modify</button>
            <button v-on:click="deleteTeam(contentId)">Delete</button>
            <button v-on:click="resetContentId">New</button>
          </div>        
      </div>
    </section>
  </div>
</template>

<script>
import { ApolloProvider } from 'vue-apollo'
import ApolloClient from 'apollo-boost'
import gql from 'graphql-tag'

const client = new ApolloClient({
  uri: 'http://localhost:4000/', // GraphQL Server URL
})

const GET_TEAMS = gql`
  query GetTeams {
    teams {
      id
      manager
      members {
        id
        first_name
        last_name
        role
      }
    }
  }
`

const GET_TEAM = gql`
  query GetTeam($id: ID!) {
    team(id: $id) {
      id
      manager
      office
      extension_number
      mascot
      cleaning_duty
      project
    }
  }
`

const DELETE_TEAM = gql`
  mutation DeleteTeam($id: ID!) {
    deleteTeam(id: $id) {
      id
    }
  }
`

const EDIT_TEAM = gql`
  mutation EditTeam($id: ID!, $input: PostTeamInput!) {
    editTeam(id: $id, input: $input) {
      id
      manager
      office
      extension_number
      mascot
      cleaning_duty
      project
    }
  }
`

export default {
  provide: () => ({
    apolloProvider: new ApolloProvider({ defaultClient: client }),
  }),
  data () {
    return {
      contentId: 0,
      inputs: {
        manager: "",
        office: "",
        extension_number: "",
        mascot: "",
        cleaning_duty: "",
        project: "",
      },
      roleIcons: {
        developer: "💻",
        designer: "🎨",
        planner: "📝",
      },
      selectedTeam: null,
      GET_TEAMS,
      GET_TEAM,
      DELETE_TEAM,
      EDIT_TEAM,
    }
  },
  methods: {
    async selectTeam (id) {
      this.contentId = id
      const { data } = await this.$apollo.query({ query: this.GET_TEAM, variables: { id } })
      this.selectedTeam = data.team
      this.inputs = {
        manager: data.team.manager,
        office: data.team.office,
        extension_number: data.team.extension_number,
        mascot: data.team.mascot,
        cleaning_duty: data.team.cleaning_duty,
        project: data.team.project,
      }
    },
    resetContentId() {
      this.contentId = 0
      this.inputs = {
        manager: "",
        office: "",
        extension_number: "",
        mascot: "",
        cleaning_duty: "",
        project: "",
      }
    },
    async deleteTeam (id) {
      if (window.confirm('이 항목을 삭제하시겠습니까?')) {
        await this.$apollo.mutate({ 
          mutation: this.DELETE_TEAM, 
          variables: { id },
          refetchQueries: [{ query: this.GET_TEAMS }] // 삭제 후 팀 목록을 업데이트
        })
        this.resetContentId() // 삭제 후 입력 필드를 초기화
      }
    },
    async editTeam (id) {
      console.log(this.inputs)
      await this.$apollo.mutate({ 
        mutation: this.EDIT_TEAM,
        variables: {
          id,
          input: this.inputs
        },
        refetchQueries: [{ query: this.GET_TEAMS }] // 수정 후 팀 목록을 업데이트
      })
      alert(`${id} 항목이 수정되었습니다.`)
    },
  },
  created() {
    this.resetContentId(); // 초기화면 구동시, 입력 필드를 초기화
    this.selectedTeam = {}; // 초기화면 구동시, selectedTeam을 빈 객체로 초기화
  },
}
</script>

// frontend/5-react/4-react-bff/2-graphql-client/6-client-mutation-update(teams)/app1/src/components/teams.js
import "./components.css"
import { useState } from "react"
import { useQuery, useMutation, gql } from "@apollo/client"

// GraphQL 서버로부터 모든 컨텐츠를 표시하기 위한 쿼리
const GET_TEAMS = gql`
  query GetTeams {
    teams {
      id
      manager
      members {
        id
        first_name
        last_name
        role
      }
    }
  }
`

// GraphQL 서버로부터 id에 해당하는 컨텐츠 하나만 받아와서 표시하기 위한 쿼리
const GET_TEAM = gql`
  query GetTeam($id: ID!) {
    team(id: $id) {
      id
      manager
      office
      extension_number
      mascot
      cleaning_duty
      project
    }
  }
`

// GraphQL 서버로부터 id에 해당하는 컨텐츠 하나를 삭제하는 쿼리
const DELETE_TEAM = gql`
  mutation DeleteTeam($id: ID!) {
    deleteTeam(id: $id) {
      id
    }
  }
`

// GraphQL 서버로부터 id에 해당하는 컨텐츠 하나를 수정하는 쿼리
const EDIT_TEAM = gql`
  mutation EditTeam($id: ID!, $input: PostTeamInput!) {
    editTeam(id: $id, input: $input) {
      id
      manager
      office
      extension_number
      mascot
      cleaning_duty
      project
    }
  }
`

// 새로고침 변수1 : 삭제, 수정, 추가 등의 Mutation(=POST처리) 실행 후, 팀 정보를 새로고침 하기 위한 변수
let refetchTeams

export default function Teams() {
  const [contentId, setContentId] = useState(0)
  const [inputs, setInputs] = useState({
    manager: "",
    office: "",
    extension_number: "",
    mascot: "",
    cleaning_duty: "",
    project: "",
  })

  // 삭제 함수1 : 처음 버튼을 눌렀을 때, 정말 삭제할 것인지 확인함
  function execDeleteTeam() {
    if (window.confirm("이 항목을 삭제하시겠습니까?")) {
      deleteTeam({ variables: { id: contentId } })
    }
  }
  // 삭제 함수2 : useMutation을 사용해서, 먼저 GraphQL 서버로부터 id에 해당하는 컨텐츠 하나를 삭제하고, 완료 후 deleteTeamCompleted 함수를 실행
  const [deleteTeam] = useMutation(
    DELETE_TEAM, // 이걸 먼저 실행해서 삭제함
    { onCompleted: deleteTeamCompleted } // 삭제 완료 후, deleteTeamCompleted 함수를 실행
  )
  // 삭제 함수3 : 삭제 완료 후의 처리로, 콘솔로그와 알림창을 띄우고 목록을 새로고침 해주는 함수
  function deleteTeamCompleted(data) {
    console.log(data.deleteTeam)
    alert(`${data.deleteTeam.id} 항목이 삭제되었습니다.`)
    setContentId(0)
    // 새로고침 변수3 : 새로고침 함수 호출
    refetchTeams()
  }

  // 수정 함수1 : 처음 버튼을 눌렀을 때, 수정을 위한 인자값을 파라미터에 담아서 수정 함수를 호출함
  function execEditTeam() {
    editTeam({
      variables: {
        id: contentId,
        input: inputs,
      },
    })
  }
  // 수정 함수2 : useMutation을 사용해서, 먼저 GraphQL 서버로부터 id에 해당하는 컨텐츠 하나를 수정하고, 완료 후 editTeamCompleted 함수를 실행
  const [editTeam] = useMutation(EDIT_TEAM, { onCompleted: editTeamCompleted })
  // 수정 함수3 : 수정 완료 후의 처리로, 콘솔로그와 알림창을 띄우고 목록을 새로고침 해주는 함수
  function editTeamCompleted(data) {
    console.log(data.editTeam)
    alert(`${data.editTeam.id} 항목이 수정되었습니다.`)
    refetchTeams() // 새로고침
  }

  // 왼쪽 사이드바 : GraphQL로부터 모든 데이터를 받아와 목록을 렌더링하도록 작성
  function AsideItems() {
    const roleIcons = {
      developer: "💻",
      designer: "🎨",
      planner: "📝",
    }

    const { loading, error, data, refetch } = useQuery(GET_TEAMS)
    // 새로고침 변수2 : 쿼리의 "새로고침된 정보"를 담는 부분
    refetchTeams = refetch

    if (loading) return <p className="loading">Loading...</p>
    if (error) return <p className="error">Error :(</p>
    // GET_TEAMS 쿼리 응답을 콘솔로그에 찍는다.
    if (data) {
      console.log("GET_TEAMS 쿼리 응답: ", data)
    }

    return (
      <ul>
        {data.teams.map(({ id, manager, members }) => {
          return (
            <li key={id}>
              <span
                className="teamItemTitle"
                onClick={() => {
                  setContentId(id)
                }}
              >
                Team {id} : {manager}'s
              </span>
              <ul className="teamMembers">
                {members.map(({ id, first_name, last_name, role }) => {
                  return (
                    <li key={id}>
                      {roleIcons[role]} {first_name} {last_name}
                    </li>
                  )
                })}
              </ul>
            </li>
          )
        })}
      </ul>
    )
  }

  // 가운데 메인컨텐츠 : GraphQL 서버로부터 id로 한개의 컨텐츠 받아와 표시하기
  function MainContents() {
    const { loading, error, data } = useQuery(GET_TEAM, {
      variables: { id: contentId },
      onCompleted: (data) => {
        if (contentId === 0) {
          setInputs({
            manager: "",
            office: "",
            extension_number: "",
            mascot: "",
            cleaning_duty: "",
            project: "",
          })
        } else {
          setInputs({
            manager: data.team.manager,
            office: data.team.office,
            extension_number: data.team.extension_number,
            mascot: data.team.mascot,
            cleaning_duty: data.team.cleaning_duty,
            project: data.team.project,
          })
        }
      },
    })

    if (loading) return <p className="loading">Loading...</p>
    if (error) return <p className="error">Error :(</p>
    // GET_TEAM 쿼리 응답을 콘솔로그에 찍는다.
    if (data) {
      console.log("GET_TEAM 쿼리 응답: ", data)
    }

    function handleChange(e) {
      const { name, value } = e.target
      setInputs({
        ...inputs,
        [name]: value,
      })
    }

    return (
      <div className="inputContainer">
        <table>
          <tbody>
            {contentId !== 0 && (
              <tr>
                <td>Id</td>
                <td>{contentId}</td>
              </tr>
            )}
            <tr>
              <td>Manager</td>
              <td>
                <input
                  type="text"
                  name="manager"
                  value={inputs.manager}
                  onChange={handleChange}
                />
              </td>
            </tr>
            <tr>
              <td>Office</td>
              <td>
                <input
                  type="text"
                  name="office"
                  value={inputs.office}
                  onChange={handleChange}
                />
              </td>
            </tr>
            <tr>
              <td>Extension Number</td>
              <td>
                <input
                  type="text"
                  name="extension_number"
                  value={inputs.extension_number}
                  onChange={handleChange}
                />
              </td>
            </tr>
            <tr>
              <td>Mascot</td>
              <td>
                <input
                  type="text"
                  name="mascot"
                  value={inputs.mascot}
                  onChange={handleChange}
                />
              </td>
            </tr>
            <tr>
              <td>Cleaning Duty</td>
              <td>
                <input
                  type="text"
                  name="cleaning_duty"
                  value={inputs.cleaning_duty}
                  onChange={handleChange}
                />
              </td>
            </tr>
            <tr>
              <td>Project</td>
              <td>
                <input
                  type="text"
                  name="project"
                  value={inputs.project}
                  onChange={handleChange}
                />
              </td>
            </tr>
          </tbody>
        </table>
        {contentId === 0 ? (
          <div className="buttons">
            <button onClick={() => {}}>Submit</button>
          </div>
        ) : (
          <div className="buttons">
            <button onClick={execEditTeam}>Modify</button>
            <button onClick={execDeleteTeam}>Delete</button>
            <button
              onClick={() => {
                setContentId(0)
              }}
            >
              New
            </button>
          </div>
        )}
      </div>
    )
  }

  return (
    <div id="teams" className="component">
      <aside>{AsideItems()}</aside>
      <section className="contents">{MainContents()}</section>
    </div>
  )
}
