// ops/1-assets/1-templates/react/bootstrap-movies-prod/v5/nuxt-js/pages/cast/index.vue
<template>
  <section class="section-padding">
    <div class="container-fluid">
      <b-row
        class="row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 row-cols-xl-6"
      >
        <b-col v-for="data in cast.slice(0, 12)" :key="data">
          <card-cast-grid
            :title="$t(data.title)"
            :designation="data.designation"
            :image="data.profile_image"
          ></card-cast-grid>
        </b-col>
      </b-row>
      <div class="text-center">
        <div class="iq-button">
          <a href="#" class="btn text-uppercase position-relative">
            <span class="button-text">{{ $t("ott_home.load_more") }}</span
            >{{ " " }}
            <i class="fa-solid fa-play"></i>
          </a>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
//components
import CardCastGrid from "../../components/cards/CardCastGrid.vue";

//Static data
import { cast } from "../../StaticData/data";

//custom hooks
import { useBreadcrumb } from "~/utilities/usePage";

import { onMounted } from "vue";
import { useStremit } from "~/store/streamit";

const store = useStremit();

onMounted(() => {
  store.breadcrumbSet({ show: false, name: "" });
});

useBreadcrumb("Cast");
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/next-js/src/pages/cast/index.tsx
import React, { Fragment, memo } from "react";

// react-bootstrap
import { Container, Row, Col } from "react-bootstrap";

//router
import Link from "next/link";

// components
import CastCard from "../../components/cards/CastCard";

// data
import { cast } from "../../StaticData/data";

//custom hooks
import { useBreadcrumb } from "@/utilities/usePage";

export const CastPage = memo(() => {
  useBreadcrumb('Cast')
  return (
    <Fragment>
      <section className="section-padding">
        <Container fluid>
          <Row className="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 row-cols-xl-6">
            {cast.map((item, index) => (
              <Col key={index}>
                <CastCard
                  title={item.title}
                  category={item.designation}
                  image={item.profile_image}
                />
              </Col>
            ))}
          </Row>
          <div className="text-center">
            <div className="iq-button">
              <Link
                href="#"
                className="btn text-uppercase position-relative"
              >
                <span className="button-text">load more</span>{" "}
                <i className="fa-solid fa-play"></i>
              </Link>
            </div>
          </div>
        </Container>
      </section>
    </Fragment>
  );
});

CastPage.displayName = "CastPage";
export default CastPage;
