// ops/1-assets/1-app-templates/react/movies-prod/v5/next-js/src/components/cards/TagsCard.tsx
import React, { Fragment, memo } from "react";

// Next-Link
import Link from "next/link";

interface TagCardProps{
  title?:string
}

const TagsCard = memo((props:TagCardProps) => {
  return (
    <Fragment>
      <Link href="/view-all">
        <span className="iq-tag-box">{props.title}</span>
      </Link>
    </Fragment>
  );
});

TagsCard.displayName = "TagsCard";
export default TagsCard;

// ops/1-assets/1-app-templates/vue/movies-prod/v5/nuxt-js/components/cards/TagsCard.vue
<template>
  <nuxt-link :to="{ name: 'view-all' }" class="iq-tag-box">
    <span class="iq-tag">
      {{ props.title }}
    </span>
  </nuxt-link>
</template>
<script setup>
const props = defineProps({
  title: { type: String, default: "" },
  slug: { type: String, default: "" },
  type: { type: String, default: "" },
});

// params: { filter: 'tags', slug: props.slug, type: props.type }
</script>
