// ops/1-assets/1-templates/vue/movies-prod/v5/nuxt-js/components/cards/TopTenCard.vue
<template>
  <div class="iq-top-ten-block">
    <div class="block-image position-relative">
      <div class="img-box">
        <nuxt-link class="overly-images" :to="link">
          <img
            :src="imagePath"
            alt="movie-card"
            class="img-fluid object-cover"
            loading="lazy"
          />
        </nuxt-link>
        <span class="top-ten-numbers texture-text">{{ countValue }}</span>
      </div>
    </div>
  </div>
</template>
<script setup>
defineProps({
  imagePath: { type: String, default: "" },
  countValue: { type: Number, default: 0 },
  link: { type: [String, Object], default: () => "/" },
});
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/next-js/src/components/cards/TopTenCard.tsx
import { FC, Fragment, memo } from "react";
import Link from 'next/link';

interface TopTenCardProps {
  link: string;
  imagePath: string;
  countValue: number;
}

const TopTenCard: FC<TopTenCardProps> = memo(({ link, imagePath, countValue }) => {
  return (
    <Fragment>
      <div className="iq-top-ten-block">
        <div className="block-image position-relative">
          <div className="img-box">
            <Link className="overly-images" href={link}>
                <img
                  src={imagePath}
                  alt="movie-card"
                  className="img-fluid object-cover"
                />
            </Link>
            <span className="top-ten-numbers texture-text">{countValue}</span>
          </div>
        </div>
      </div>
    </Fragment> 
  );
});

TopTenCard.displayName = "TopTenCard";
export default TopTenCard;
