// start/8-Students/jung/4-vue/5-todo-app/app1/src/views/Movies.vue
<template>
<div>
    <h1>Movie App</h1>
    <div id="movies">
      <div v-for="movie in movies" :key="movie.id" class="movie">
        <a class="movieTitle" :href="movie.url">{{ movie.title }}</a>
        <img class="movieImage" :src="movie.background_image" :alt="movie.title" />
      </div>
    </div>
  </div></template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'

interface Movie {
  id: number
  title: string
  url: string
  background_image: string
}

const movies = ref<Movie[]>([])

function getMovies() {
  fetch('https://yts.mx/api/v2/list_movies.json?sort_by=rating')
    .then(res => res.json())
    .then(json => {
      movies.value = json.data.movies
    })
}

onMounted(() => {
  getMovies()
})
</script>

<style scoped>
.movieTitle {
  font-size: 20px;
  color: #1a45e1;
  text-decoration: none;
  display: block;
}
.movieImage {
  width: 200px;
  height: auto;
  margin-top: 10px;
}
</style>

// start/9-workspace/saitou/4-react/1-syntax-basic/11-router/app1/src/components/Movies.js
import React from "react";
import { useState, useEffect } from "react";
import "./Movies.css";

export default function Movies() {
  const [movies, setMovies] = useState([]);

  const movieRatingClass = (rating) => {
    return rating >= 9 ? "good" : rating >= 7 ? "soso" : "bad";
  };

  // mounted
  useEffect(() => {
    // fetch("https://yts.mx/api/v2/list_movies.json?sort_by=rating")
    fetch("https://yts.mx/api/v2/list_movies.json")
      .then((res) => res.json())
      .then((json) => {
        setMovies(json.data.movies);
      });
  }, []);

  console.log("movies: ", movies);

  const render = movies.map((movie) => {
    return (
      <div key={movie.id}>
        <a className="movieTitle" href={movie.url}>
          {movie.title} ({movie.year})
        </a>
        <div>
          評価：
          <span className={movieRatingClass(movie.rating)}>{movie.rating}</span>
          /10点
        </div>
        <div>ジャンル：{movie.genres.join(", ")}</div>
        <div>ランタイム：{movie.runtime}分</div>
        <div>ストーリー：{movie.synopsis || "情報無し"}</div>
        <img
          className="movieImg"
          src={movie.large_cover_image}
          alt={movie.title}
        ></img>
      </div>
    );
  });

  return (
    <div>
      <h1>Movies</h1>
      <div>{render}</div>
    </div>
  );
}
