// ops/1-assets/1-app-templates/react/movies-prod/v5/vue/frontend/src/views/AuthPages/SignUpPage.vue
<template>
  <section class="sign-in-page vh-100" :style="`background: url(${generateImgPath('./assets/images/pages/01.webp')}); background-size: cover; background-repeat: no-repeat; position: relative;min-height:500px;`">
    <div class="container">
      <div class="row justify-content-center align-items-center height-self-center vh-100">
        <div class="col-lg-8 col-md-12 align-self-center">
          <div class="user-login-card bg-body">
            <h4 class="text-center mb-5">
              <BrandLogo></BrandLogo>
              {{ $t('form.create_account') }}
            </h4>
            <div class="row row-cols-1 row-cols-lg-2 g-2 g-lg-5">
              <div class="col">
                <label class="text-white fw-500 mb-2">{{ $t('form.first_name') }}*</label>
                <input type="text" class="form-control rounded-0" required="" />
              </div>
              <div class="col">
                <label class="text-white fw-500 mb-2">{{ $t('form.last_name') }}*</label>
                <input type="text" class="form-control rounded-0" required="" />
              </div>
              <div class="col">
                <label class="text-white fw-500 mb-2">{{ $t('form.username') }} *</label>
                <input type="text" class="form-control rounded-0" required="" />
              </div>
              <div class="col">
                <label class="text-white fw-500 mb-2">{{ $t('form.email') }} *</label>
                <input type="email" class="form-control rounded-0" required="" />
              </div>
              <div class="col">
                <label class="text-white fw-500 mb-2">{{ $t('form.password') }} *</label>
                <input type="password" class="form-control rounded-0" required="" />
              </div>
              <div class="col">
                <label class="text-white fw-500 mb-2">{{ $t('form.confirm_password') }} *</label>
                <input type="password" class="form-control rounded-0" required="" />
              </div>
            </div>
            <label class="list-group-item d-flex align-items-center mt-5 mb-3 text-white"
              ><input class="form-check-input m-0 me-2" type="checkbox" />{{ $t('form.read_and_accept') }} <router-link to="/terms-of-use" class="ms-1"> {{ $t('form.terms_conditions') }}*</router-link></label
            >
            <div class="row text-center">
              <div class="col-lg-3"></div>
              <div class="col-lg-6">
                <div class="full-button">
                  <div class="iq-button">
                    <a href="#" class="btn text-uppercase position-relative">
                      <span class="button-text">{{ $t('form.sign_up') }}</span>
                      {{ '' }}
                      <i class="fa-solid fa-play"></i>
                    </a>
                  </div>
                  <p class="mt-2 mb-0 fw-normal">
                    {{ $t('form.already_account') }}?<router-link :to="{ name: 'landing-page.login-page' }" class="ms-1">{{ $t('shop.login') }}</router-link>
                  </p>
                </div>
              </div>
              <div class="col-lg-3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script setup>
import { generateImgPath } from '../../StaticData/data';
</script>

// ops/1-assets/1-app-templates/react/movies-prod/v5/react/frontend/src/views/AuthPages/SignUpPage.jsx
import React, { Fragment, memo } from "react";

//react-bootstrap
import { Col, Container, Form, Row } from "react-bootstrap";

//react-router-dom
import { Link } from "react-router-dom";

//hooks
import { useTranslation } from "react-i18next";

const SignUpPage = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <main className="main-content">
        <div
          className="vh-100"
          style={{
            backgroundImage: "url(assets/images/pages/01.webp)",
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            position: "relative",
            minHeight: "500px",
          }}
        >
          <Container>
            <Row className="justify-content-center align-items-center height-self-center vh-100">
              <Col lg="8" md="12" className="align-self-center">
                <div className="user-login-card bg-body">
                  <h4 className="text-center mb-5">
                    {t("form.create_account")}
                  </h4>
                  <Row lg="2" className="row-cols-1 g-2 g-lg-5">
                    <Col>
                      <Form.Label className="text-white fw-500 mb-2">
                        {t("form.first_name")}
                      </Form.Label>
                      <Form.Control
                        type="text"
                        className="rounded-0"
                        required
                      />
                    </Col>
                    <Col>
                      <Form.Label className="text-white fw-500 mb-2">
                        {t("form.last_name")}
                      </Form.Label>
                      <Form.Control
                        type="text"
                        className="rounded-0"
                        required
                      />
                    </Col>
                    <Col>
                      <Form.Label className="text-white fw-500 mb-2">
                        {t("form.username")} *
                      </Form.Label>
                      <Form.Control
                        type="text"
                        className="rounded-0"
                        required
                      />
                    </Col>
                    <Col>
                      <Form.Label className="text-white fw-500 mb-2">
                        {t("form.email")} *
                      </Form.Label>
                      <Form.Control
                        type="text"
                        className="rounded-0"
                        required
                      />
                    </Col>
                    <Col>
                      <Form.Label className="text-white fw-500 mb-2">
                        {t("form.password")} *
                      </Form.Label>
                      <Form.Control
                        type="password"
                        className="rounded-0"
                        required
                      />
                    </Col>
                    <Col>
                      <Form.Label className="text-white fw-500 mb-2">
                        {t("form.confirm_password")} *
                      </Form.Label>
                      <Form.Control
                        type="password"
                        className="rounded-0"
                        required
                      />
                    </Col>
                  </Row>
                  <Form.Label className="list-group-item d-flex align-items-center mt-5 mb-3 text-white">
                    <Form.Check.Input className="m-0 me-2" type="checkbox" />
                    {t("form.read_and_accept")}
                    <Link to="/terms-of-use" className="ms-1">
                      {t("form.terms_conditions")}
                    </Link>
                  </Form.Label>
                  <Row className="text-center">
                    <Col lg="3"></Col>
                    <Col lg="6">
                      <div className="full-button">
                        <div className="iq-button">
                          <Link
                            to="#"
                            className="btn text-uppercase position-relative"
                          >
                            <span className="button-text">
                              {t("form.sign_up")}
                            </span>
                            <i className="fa-solid fa-play"></i>
                          </Link>
                        </div>
                        <p className="mt-2 mb-0 fw-normal">
                          {t("form.already_account")}?
                          <a href="/login" className="ms-1">
                            {t("shop.login")}
                          </a>
                        </p>
                      </div>
                    </Col>
                    <Col lg="3"></Col>
                  </Row>
                </div>
              </Col>
            </Row>
          </Container>
        </div>
      </main>
    </Fragment>
  );
});

SignUpPage.displayName = "SignUpPage";
export default SignUpPage;
