// ops/1-assets/1-app-templates/react/movies-prod/v5/next-js/src/components/sections/RecommendedForYou.tsx
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";
import { Fragment, memo, useState } from "react";
import { recommendedforYou } from "../../StaticData/data";
const RecommendedForYou = memo(() => {
  const [title] = useState("Recommended For You");

  return (
    <Fragment>
      <SectionSlider
        title={title}
        list={recommendedforYou}
        className="recommended-block streamit-block"
        slidesPerView={6}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={data.title}
            movieTime={data.movieTime}
            watchlistLink="/play-list"
            link="/movies/detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
})

RecommendedForYou.displayName = 'RecommendedForYou';
export default RecommendedForYou;

// ops/1-assets/2-app-templates/all/movies-prod/v5/nuxt-js/components/sections/RecommendedForYou.vue
<template>
  <!-- Recommended For You start -->
  <SectionSlider
    :title="$t(title)"
    :list="recommendedforYou"
    :slides-per-view="6"
    class="recommended-block streamit-block"
  >
    <template #headerLink>
      <nuxt-link
        to="view-all"
        class="text-primary iq-view-all text-decoration-none flex-none"
        >{{ $t("ott_home.view_all") }}</nuxt-link
      >
    </template>
    <template #default="{ data }">
      <card-style
        :image="data.image"
        :title="$t(data.title)"
        :movie-time="data.movieTime"
        :watchlist-link="{ name: 'play-list' }"
        :link="{ name: 'movies-detail' }"
      ></card-style>
    </template>
  </SectionSlider>
  <!-- Recommended For You end -->
</template>

<script setup>
import { ref } from "vue";
import SectionSlider from "../slider/SectionSlider.vue";
import CardStyle from "../cards/CardStyle.vue";
import { recommendedforYou } from "../../StaticData/data";

const title = ref("ott_home.recommended_for_you");
</script>
