// ops/1-assets/1-app-templates/all/movies-prod/v5/react/frontend/src/views/TagsPage.jsx
import React, { Fragment, memo } from "react";

// react-bootstrap
import { Container, Row, Col } from "react-bootstrap";

// react-router
import { Link } from "react-router-dom";

// components
import TagsCard from "../components/cards/TagsCard";
import BreadcrumbWidget from "../components/BreadcrumbWidget";

// data
import { movieTags, tvShowsTags, videoTags } from "../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const TagsPage = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <BreadcrumbWidget title={t("detail_page.tags")} />
      <section className="section-padding">
        <Container fluid>
          <div className="d-flex align-items-center justify-content-between mb-4">
            <h4 className="main-title text-capitalize mb-0">
              {t("ott_home.movie_tag")}
            </h4>
          </div>
          <Row as="ul" className="mb-0 list-inline">
            {movieTags.map((item, index) => (
              <Col as="li" xl="2" lg="3" md="4" sm="6" key={index}>
                <TagsCard
                  slug={t(item.slug)}
                  title={t(item.title)}
                  type={t(item.type)}
                />
              </Col>
            ))}
          </Row>
          <div className="text-center">
            <div className="iq-button">
              <Link to="#" className="btn text-uppercase position-relative">
                <span className="button-text">{t("ott_home.load_more")}</span>{" "}
                <i className="fa-solid fa-play"></i>
              </Link>
            </div>
          </div>
        </Container>
      </section>
      <section className="section-padding-bottom">
        <Container fluid>
          <div className="d-flex align-items-center justify-content-between mb-4">
            <h4 className="main-title text-capitalize mb-0">{t("ott_home.tv_show_tag")}</h4>
          </div>
          <Row as="ul" className="row mb-0 list-inline">
            {tvShowsTags.map((item, index) => (
              <Col as="li" xl="2" lg="3" md="4" sm="6" key={index}>
                <TagsCard
                  slug={t(item.slug)}
                  title={t(item.title)}
                  type={t(item.type)}
                />
              </Col>
            ))}
          </Row>
          <div className="text-center">
            <div className="iq-button">
              <Link to="#" className="btn text-uppercase position-relative ">
                <span className="button-text">{t("ott_home.load_more")}</span>{" "}
                <i className="fa-solid fa-play"></i>
              </Link>
            </div>
          </div>
        </Container>
      </section>
      <section className="section-padding-bottom">
        <Container fluid>
          <div className="iq-main-header d-flex align-items-center justify-content-between mb-4">
            <h4 className="text-capitalize mb-0">{t("ott_home.video_tag")}</h4>
          </div>
          <Row as="ul" className="mb-0 list-inline">
            {videoTags.map((item, index) => (
              <Col as="li" xl="2" lg="3" md="4" sm="6" key={index}>
                <TagsCard
                  slug={t(item.slug)}
                  title={t(item.title)}
                  type={t(item.type)}
                />
              </Col>
            ))}
          </Row>
          <div className="text-center">
            <div className="iq-button">
              <Link to="#" className="btn text-uppercase position-relative">
                <span className="button-text">{t("ott_home.load_more")}</span>{" "}
                <i className="fa-solid fa-play"></i>
              </Link>
            </div>
          </div>
        </Container>
      </section>
    </Fragment>
  );
});

TagsPage.displayName = "TagsPage";
export default TagsPage;

// ops/1-assets/2-app-templates/all/movies-prod/v5/vue/frontend/src/views/TagsPage.vue
<template>
  <div>
    <section class="section-padding">
      <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between mb-4">
          <h4 class="main-title text-capitalize mb-0">{{ $t('ott_home.movie_tag') }}</h4>
        </div>
        <ul class="row mb-0 list-inline">
          <li v-for="data in list.slice(0, 12)" :key="data" class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
            <TagsCard :slug="data.slug" :title="$t(data.title)" :type="data.type"> </TagsCard>
          </li>
        </ul>
        <div class="text-center">
          <div class="iq-button">
            <a href="javascript:void(0)" class="btn text-uppercase position-relative">
              <span class="button-text">{{ $t('ott_home.load_more') }}</span>
              {{ '' }}
              <i class="fa-solid fa-play"></i>
            </a>
          </div>
        </div>
      </div>
    </section>
    <section class="section-padding-bottom">
      <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between mb-4">
          <h4 class="main-title text-capitalize mb-0">{{ $t('ott_home.tv_show_tag') }}</h4>
        </div>
        <ul class="row mb-0 list-inline">
          <li v-for="data in tvShowsList" :key="data" class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
            <TagsCard :slug="data.slug" :title="$t(data.title)" :type="data.type"> </TagsCard>
          </li>
        </ul>
        <div class="text-center">
          <div class="iq-button">
            <a href="javascript:void(0)" class="btn text-uppercase position-relative">
              <span class="button-text">{{ $t('ott_home.load_more') }}</span>
              {{ '' }}
              <i class="fa-solid fa-play"></i>
            </a>
          </div>
        </div>
      </div>
    </section>
    <section class="section-padding-bottom">
      <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between mb-4">
          <h4 class="main-title text-capitalize mb-0">{{ $t('ott_home.video_tag') }}</h4>
        </div>
        <ul class="row mb-0 list-inline">
          <li v-for="data in videoList" :key="data" class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
            <router-link :to="{ name: 'landing-page.blogs' }">
              <TagsCard :slug="data.slug" :title="$t(data.title)" :type="data.type"></TagsCard>
            </router-link>
          </li>
        </ul>
        <div class="text-center">
          <div class="iq-button">
            <a href="javascript:void(0)" class="btn text-uppercase position-relative">
              <span class="button-text">{{ $t('ott_home.load_more') }}</span>
              {{ '' }}
              <i class="fa-solid fa-play"></i>
            </a>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>
<script setup>
import TagsCard from '../components/cards/TagsCard.vue';
import { movieTags, tvShowsTags, videoTags } from '../StaticData/data';
const list = movieTags.slice(0, 12);
const tvShowsList = tvShowsTags;
const videoList = videoTags;
</script>
