// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/components/blog/sidebar/CategoriesWidget.jsx
import React, { Fragment, memo } from "react";

//react-router-dom
import { Link } from "react-router-dom";

//static data
import { blogCategories } from "../../../StaticData/blogs";

// the hook
import { useTranslation } from "react-i18next";

const CategoriesWidget = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <div id="categories-2" className="widget widget_categories">
        <h5 className="widget-title position-relative">
          {t("form.categories")}
        </h5>
        <ul className="p-0 m-0 list-unstyled">
          {blogCategories.map((item, index) => {
            return (
              <li className="text-capitalize" key={index}>
                <Link to="/blogs-category" className="position-relative">
                  {t(item.title)}
                </Link>
                <span className="post_count">({item.post_count})</span>
              </li>
            );
          })}
        </ul>
      </div>
    </Fragment>
  );
});

CategoriesWidget.displayName = "CategoriesWidget";
export default CategoriesWidget;

// ops/1-assets/1-app-templates/vue/movies-prod/v5/vue/frontend/src/components/blog/sidebar/CategoriesWidget.vue
<template>
  <div id="categories-2" class="widget widget_categories">
    <h5 class="widget-title position-relative">{{ $t('form.categories') }}</h5>
    <ul class="p-0 m-0 list-unstyled">
      <li v-for="category in props.categories" :key="category" class="text-capitalize">
        <router-link to="/blogs-category" class="position-relative">{{ $t(category) }}</router-link>
        <span class="post_count">(4)</span>
      </li>
    </ul>
  </div>
</template>
<script setup>
const props = defineProps({
  categories: {
    type: Array,
    default: () => ['blogs.dramas', 'blogs.history', 'header.movie', 'blogs.movie_trailers', 'home.trailers', 'blogs.tv_comedies', 'blogs.tv_rumors', 'blogs.tv_series'],
  },
});
</script>
