// ops/1-assets/1-templates/vue/movies-prod/v5/nuxt-js/pages/genres/index.vue
<template>
  <section class="section-padding">
    <div class="container-fluid">
      <div class="d-flex align-items-center justify-content-between mb-4">
        <h4 class="main-title text-capitalize mb-0">
          {{ $t("ott_home.movie_geners") }}
        </h4>
      </div>
      <b-row class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
        <b-col v-for="data in list.slice(0, 7)" :key="data" class="col mb-4">
          <card-genres-grid
            :slug="data.slug"
            :title="data.title"
            :image="data.thumbnail"
            :type="data.type"
          ></card-genres-grid>
        </b-col>
      </b-row>
      <div class="text-center">
        <div class="iq-button">
          <a
            href="javascript:void(0)"
            class="btn text-uppercase position-relative"
          >
            <span class="button-text">{{ $t("ott_home.load_more") }}</span>
            <i class="fa-solid fa-play"></i>
          </a>
        </div>
      </div>
    </div>
  </section>
  <section class="section-padding-bottom">
    <div class="container-fluid">
      <div class="d-flex align-items-center justify-content-between mb-4">
        <h4 class="main-title text-capitalize mb-0">
          {{ $t("ott_home.tv_show_genres") }}
        </h4>
      </div>
      <b-row class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
        <b-col
          v-for="data in tvShowList.slice(0, 7)"
          :key="data"
          class="col mb-4"
        >
          <card-genres-grid
            :slug="data.slug"
            :title="data.title"
            :image="data.thumbnail"
            :type="data.type"
          ></card-genres-grid>
        </b-col>
      </b-row>
      <div class="text-center">
        <div class="iq-button">
          <a
            href="javascript:void(0)"
            class="btn text-uppercase position-relative"
          >
            <span class="button-text">{{ $t("ott_home.load_more") }}</span>
            <i class="fa-solid fa-play"></i>
          </a>
        </div>
      </div>
    </div>
  </section>
  <section class="section-padding-bottom">
    <div class="container-fluid">
      <div class="d-flex align-items-center justify-content-between mb-4">
        <h4 class="main-title text-capitalize mb-0">
          {{ $t("ott_home.video_genres") }}
        </h4>
      </div>
      <b-row class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
        <b-col
          v-for="data in videoList.slice(0, 7)"
          :key="data"
          class="col mb-4"
        >
          <card-genres-grid
            :slug="data.slug"
            :title="data.title"
            :image="data.thumbnail"
            :type="data.type"
          ></card-genres-grid>
        </b-col>
      </b-row>
      <div class="text-center">
        <div class="iq-button">
          <a
            href="javascript:void(0)"
            class="btn text-uppercase position-relative"
          >
            <span class="button-text">{{ $t("ott_home.load_more") }}</span>
            <i class="fa-solid fa-play"></i>
          </a>
        </div>
      </div>
    </div>
  </section>
</template>
<script setup>
//components
import CardGenresGrid from "../components/cards/CardGenresGrid.vue";

//data
import { geners, tvShowGenres, videoGenres } from "../StaticData/data";

//custom hooks
import { useBreadcrumb } from "~/utilities/usePage";

useBreadcrumb("Genres");

const list = geners;
const tvShowList = tvShowGenres;
const videoList = videoGenres;
</script>

// ops/1-assets/1-templates/react/bootstrap-movies-prod/v5/next-js/src/pages/genres/index.tsx
import { memo, Fragment } from "react";

//react-bootstrap
import { Row, Col } from "react-bootstrap";

//router
import Link from "next/link";

// components
import GenersCard from "@/components/cards/GanresCard";

// data
import { geners, tvShowGenres, videoGenres } from "@/StaticData/data";

//custom hooks
import { useBreadcrumb } from "@/utilities/usePage";

const GenresPage = memo(() => {
  useBreadcrumb('Genres')
  return (
    <Fragment>
      <section className="section-padding">
        <div className="container-fluid">
          <div className="d-flex align-items-center justify-content-between mb-4">
            <h4 className="main-title text-capitalize mb-0">Movie Genres</h4>
          </div>
          <Row className="row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            {geners.map((item, index) => (
              <Col key={index} className="mb-4">
                <GenersCard
                  slug={item.slug}
                  title={item.title}
                  image={item.thumbnail}
                  type={item.type}
                />
              </Col>
            ))}
          </Row>
          <div className="text-center">
            <div className="iq-button">
              <Link
                href="#"
                className="btn text-uppercase position-relative"
              >
                <span className="button-text">load more</span>
                <i className="fa-solid fa-play"></i>
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section className="section-padding-bottom">
        <div className="container-fluid">
          <div className="d-flex align-items-center justify-content-between mb-4">
            <h4 className="main-title text-capitalize mb-0">Tv-Show Genres</h4>
          </div>
          <Row className="row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            {tvShowGenres.map((item, index) => (
              <Col key={index} className="mb-4">
                <GenersCard
                  slug={item.slug}
                  title={item.title}
                  image={item.thumbnail}
                  type={item.type}
                />
              </Col>
            ))}
          </Row>
          <div className="text-center">
            <div className="iq-button">
              <Link
                href="#"
                className="btn text-uppercase position-relative"
              >
                <span className="button-text">load more</span>
                <i className="fa-solid fa-play"></i>
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section className="section-padding-bottom">
        <div className="container-fluid">
          <div className="d-flex align-items-center justify-content-between mb-4">
            <h4 className="main-title text-capitalize mb-0">Video Genres</h4>
          </div>
          <Row className="row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            {videoGenres.map((item, index) => (
              <Col key={index} className="mb-4">
                <GenersCard
                  slug={item.slug}
                  title={item.title}
                  image={item.thumbnail}
                  type={item.type}
                />
              </Col>
            ))}
          </Row>
          <div className="text-center">
            <div className="iq-button">
              <Link
                href="#"
                className="btn text-uppercase position-relative"
              >
                <span className="button-text">load more</span>
                <i className="fa-solid fa-play"></i>
              </Link>
            </div>
          </div>
        </div>
      </section>
    </Fragment>
  );
});

GenresPage.displayName = "GenresPage";
export default GenresPage;
