// ops/1-assets/2-app-templates/all/movies-prod/v5/vue/dashboard/src/views/extra/PrivacyPolicy.vue
<template>
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="header-title">
            <h4 class="card-title">{{$t('movielist.what_is_lorem_ipsum')}}?</h4>
          </div>
        </div>
        <div class="card-body">
          <p>{{$t('movielist.privacydesc1')}}</p>
        </div>
      </div>
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="header-title">
            <h4 class="card-title">{{$t('movielist.why_do_we_use_it')}}?</h4>
          </div>
        </div>
        <div class="card-body">
          <p>{{$t('movielist.privacydesc2')}}</p>
        </div>
      </div>
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="header-title">
            <h4 class="card-title">{{$t('movielist.where_does')}}?</h4>
          </div>
        </div>
        <div class="card-body">
          <p>{{$t('movielist.privacydesc2')}}</p>
        </div>
      </div>
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="header-title">
            <h4 class="card-title">{{$t('movielist.where_can_i_get_some')}}?</h4>
          </div>
        </div>
        <div class="card-body">
          <p>{{$t('movielist.privacydesc2')}}</p>
        </div>
      </div>
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="header-title">
            <h4 class="card-title">{{$t('movielist.why_do_we_use_it')}}?</h4>
          </div>
        </div>
        <div class="card-body">
          <p>{{$t('movielist.privacydesc2')}}</p>
        </div>
      </div>
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="header-title">
            <h4 class="card-title">{{$t('movielist.why_do_we_use_it')}}?</h4>
          </div>
        </div>
        <div class="card-body">
          <p>{{$t('movielist.privacydesc2')}}</p>
        </div>
      </div>
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="header-title">
            <h4 class="card-title">{{$t('movielist.why_do_we_use_it')}}?</h4>
          </div>
        </div>
        <div class="card-body">
          <p>{{$t('movielist.privacydesc2')}}</p>
        </div>
      </div>
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="header-title">
            <h4 class="card-title">{{$t('movielist.why_do_we_use_it')}}?</h4>
          </div>
        </div>
        <div class="card-body">
          <p>{{$t('movielist.privacydesc2')}}</p>
        </div>
      </div>
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="header-title">
            <h4 class="card-title">{{$t('movielist.why_do_we_use_it')}}?</h4>
          </div>
        </div>
        <div class="card-body">
          <p>{{$t('movielist.privacydesc2')}}</p>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  name: 'PrivacyPolicy',
};
</script>

// ops/1-assets/1-app-templates/vue/movies-prod/v5/react/dashboard/src/views/dashboard/extra/privacy-policy.jsx
import React from "react";

//react-bootstrap
import { Container, Row, Col, Card } from "react-bootstrap";
// the hook
import { useTranslation } from "react-i18next";

const PrivacyPolicy = () => {
  const { t } = useTranslation();
  return (
    <Row>
      <Col lg={12}>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.what_lorem")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line1")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.where_it")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.get_some")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
        <Card>
          <Card.Header className="d-flex justify-content-between">
            <div className="header-title">
              <h4 className="card-title">{t("privacy_policy.we_use")}</h4>
            </div>
          </Card.Header>
          <Card.Body>
            <p>{t("privacy_policy.line2")}</p>
          </Card.Body>
        </Card>
      </Col>
    </Row>
  );
};

export default PrivacyPolicy;
