// ops/1-assets/1-app-templates/vue/movies-prod/v5/nuxt-js/pages/blogs/sidebar/[type].vue
<template>
  <div class="section-padding">
    <div class="container">
      <b-row>
        <b-col lg="8" sm="12" :class="order">
          <div v-for="data in blogsGrid" :key="data">
            <CardBlogList
              :title="$t(data.title)"
              :slug="data.slug"
              :thumbnail="data.thumbnail"
              :tags="data.tags"
              :username="$t(data.username)"
              :description="data.description"
              :date="data.blogDate"
              :categories="$t(data.categories)"
            ></CardBlogList>
          </div>
        </b-col>
        <b-col lg="4" sm="12">
          <DetailMetaList></DetailMetaList>
        </b-col>
      </b-row>
    </div>
  </div>
</template>

<script setup>
import { watch, computed, ref } from "vue";

import { onUnmounted, onMounted } from "vue";
import { useStremit } from "~/store/streamit";
import { useRoute } from "vue-router";
import CardBlogList from "../../components/cards/CardBlogList.vue";
import { blogsGrid } from "../../StaticData/blogs";
import DetailMetaList from "../../components/blog/DetailMetaList.vue";
const route = useRoute();

const type = computed(() => route.params.type);
const order = ref("");
//breadcrumb
const store = useStremit();
const checkType = () => {
  switch (type.value) {
    case "left":
      order.value = "order-1";
      store.breadcrumbSet({ show: true, name: "Left Sidebar" });
      break;
    case "right":
      order.value = "";
      store.breadcrumbSet({ show: true, name: "Right Sidebar" });
      break;
    default:
      break;
  }
};
watch(
  type,
  () => {
    checkType();
  },
  { deep: true }
);
onMounted(() => {
  checkType();
});
onUnmounted(() => {
  store.breadcrumbSet({ show: false, name: "" });
});
</script>

// ops/1-assets/1-templates/react/bootstrap-movies-prod/v5/next-js/src/pages/blogs/sidebar/[type].tsx

import React, { Fragment, memo, useEffect } from 'react'

// react-bootstrap
import { Container, Row, Col } from 'react-bootstrap'

//router
import { useRouter } from 'next/router'

// Components
import DetailMetaList from '@/components/blog/DetailMetaList';
// import CardBlogGrid from '@/components/cards/CardBlogGrid';
import CardBlogList from "@/components/cards/CardBlogList";
import SidebarBreadcrumb from '@/components/blog/SidebarBreadcrumb';
//components

//static data
import { blogsGrid } from '@/StaticData/blogs';

const LeftSidebarPage = memo(() => {
  const router = useRouter()
  const type = router.query.type;
  let _class;
  switch (type) {
    case 'left':
      _class = 'order-1'
      break;
    case 'right':
      _class = ''
      break;
    default:
      break;
  }
  return (
    <Fragment>
      <SidebarBreadcrumb type={type} />
      <div className='section-padding'>
        <Container>
          <Row>
            <Col lg="8" sm="12" className={_class}>
              {blogsGrid.slice(0, 10).map((item, index) => {
                return (
                  <CardBlogList
                  key={index}
                  title={item.title}
                  thumbnail={item.thumbnail}
                  blogDate={item.blogDate}
                  username={item.username}
                  categories={item.categories}
                  tags={item.tags}
                  description={item.description}
                  />
                  
                  // <CardBlogGrid key={index} title={item.title} thumbnail={item.thumbnail} tags={item.tags} username={item.username} description={item.description} date={item.blogDate} categories={item.categories}>
                  // </CardBlogGrid>
                  
                )
              })}

            </Col>
            <Col lg="4" sm="12">
              <DetailMetaList></DetailMetaList>
            </Col>
          </Row>
        </Container>
      </div>
    </Fragment>
  );
});

LeftSidebarPage.displayName = "LeftSidebarPage";
export default LeftSidebarPage;
