// ops/1-assets/2-app-templates/all/movies-prod/v5/nuxt-js/pages/blogs/filter/[type].vue
<template>
  <div class="section-padding">
    <div class="container">
      <b-row>
        <b-col lg="8" sm="12">
          <div v-for="data in blogs" :key="data">
            <card-blog-list
              :title="$t(data.title)"
              :slug="data.slug"
              :thumbnail="data.thumbnail"
              :tags="data.tags"
              :username="data.username"
              :description="data.description"
              :date="data.blogDate"
              :categories="data.categories"
            ></card-blog-list>
          </div>
        </b-col>
        <b-col lg="4" sm="12">
          <detail-meta-list></detail-meta-list>
        </b-col>
      </b-row>
    </div>
  </div>
</template>
<script setup>
import { onUnmounted } from "vue";

//components
import CardBlogList from "../../components/cards/CardBlogList.vue";
import DetailMetaList from "../../components/blog/DetailMetaList.vue";

//static data
import { blogs } from "../../StaticData/blogs";

//store
import { useStremit } from "~/store/streamit";
const store = useStremit();

//route
const route = useRoute();
const params = computed(() => route.params.type);

const changeTitle = (gridType) => {
  switch (gridType) {
    case "author":
      store.breadcrumbSet({ show: true, name: "Author: Goldenmace" });
      break;
    case "date":
      store.breadcrumbSet({ show: true, name: "Day: September 23, 2022" });
      break;
    case "category":
      store.breadcrumbSet({ show: true, name: "Drama" });
      break;
    case "tags":
      store.breadcrumbSet({ show: true, name: "Comedy" });
      break;

    default:
      break;
  }
};

onUnmounted(() => {
  store.breadcrumbSet({ show: false, name: "" });
});

changeTitle(params.value);

watch(params, (value) => {
  changeTitle(value);
});
</script>

// ops/1-assets/1-templates/react/bootstrap-movies-prod/v5/next-js/src/pages/blogs/sidebar/[type].tsx

import React, { Fragment, memo, useEffect } from 'react'

// react-bootstrap
import { Container, Row, Col } from 'react-bootstrap'

//router
import { useRouter } from 'next/router'

// Components
import DetailMetaList from '@/components/blog/DetailMetaList';
// import CardBlogGrid from '@/components/cards/CardBlogGrid';
import CardBlogList from "@/components/cards/CardBlogList";
import SidebarBreadcrumb from '@/components/blog/SidebarBreadcrumb';
//components

//static data
import { blogsGrid } from '@/StaticData/blogs';

const LeftSidebarPage = memo(() => {
  const router = useRouter()
  const type = router.query.type;
  let _class;
  switch (type) {
    case 'left':
      _class = 'order-1'
      break;
    case 'right':
      _class = ''
      break;
    default:
      break;
  }
  return (
    <Fragment>
      <SidebarBreadcrumb type={type} />
      <div className='section-padding'>
        <Container>
          <Row>
            <Col lg="8" sm="12" className={_class}>
              {blogsGrid.slice(0, 10).map((item, index) => {
                return (
                  <CardBlogList
                  key={index}
                  title={item.title}
                  thumbnail={item.thumbnail}
                  blogDate={item.blogDate}
                  username={item.username}
                  categories={item.categories}
                  tags={item.tags}
                  description={item.description}
                  />
                  
                  // <CardBlogGrid key={index} title={item.title} thumbnail={item.thumbnail} tags={item.tags} username={item.username} description={item.description} date={item.blogDate} categories={item.categories}>
                  // </CardBlogGrid>
                  
                )
              })}

            </Col>
            <Col lg="4" sm="12">
              <DetailMetaList></DetailMetaList>
            </Col>
          </Row>
        </Container>
      </div>
    </Fragment>
  );
});

LeftSidebarPage.displayName = "LeftSidebarPage";
export default LeftSidebarPage;
