// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/views/MainPages/TvShowsPage.jsx
import { Fragment } from "react";

//hero-slider
import TvShowHeroSlider from "../../components/slider/TvShowHeroSlider";

//sections
import TVPopularShows from "../../components/sections/TVPopularShows";
import BestOfInternationalShows from "../../components/sections/BestOfInternationalShows";
import ShowsWeRecommend from "../../components/sections/ShowsWeRecommend";

const TvShowsPage = () => {
  return (
    <Fragment>
      <TvShowHeroSlider />
      <TVPopularShows slideMedium={2} paddingY="my-4" />
      <BestOfInternationalShows slideMedium={2} paddingY="my-4" />
      <ShowsWeRecommend slideMedium={2} paddingY="my-4" />
    </Fragment>
  );
};

TvShowsPage.DisplayName = TvShowsPage;
export default TvShowsPage;

// ops/1-assets/1-templates/react/bootstrap-movies-prod/v5/vue/frontend/src/views/MainPages/TvShowsPage.vue
<template>
  <TvShowHeroSlider></TvShowHeroSlider>

  <TVPopularShows></TVPopularShows>

  <BestOfInternationalShows></BestOfInternationalShows>

  <ShowsWeRecommend></ShowsWeRecommend>
</template>
<script setup>
// Hero Slider
import TvShowHeroSlider from '../../components/slider/TvShowHeroSlider.vue';

// sections
import TVPopularShows from '../../components/sections/TVPopularShows.vue';
import BestOfInternationalShows from '../../components/sections/BestOfInternationalShows.vue';
import ShowsWeRecommend from '../../components/sections/ShowsWeRecommend.vue';
</script>
