// ops/1-assets/1-app-templates/vue/movies-prod/v5/nuxt-js/components/sections/Specials&LatestMovies.vue
<template>
  <!-- Specials & Latest Movies start -->
  <SectionSlider
    :title="$t(title)"
    :list="spacialLatestMovie"
    :slides-per-view="6"
    class="recommended-block streamit-block"
  >
    <template #headerLink>
      <nuxt-link
        :to="{ name: 'view-all' }"
        class="text-primary iq-view-all text-decoration-none flex-none"
        >{{ $t("ott_home.view_all") }}</nuxt-link
      >
    </template>
    <template #default="{ data }">
      <card-style
        :image="data.image"
        :title="$t(data.title)"
        :movie-time="data.movieTime"
        :watchlist-link="{ name: 'play-list' }"
        :link="{ name: 'movies-detail' }"
      ></card-style>
    </template>
  </SectionSlider>
  <!-- Specials & Latest Movies end -->
</template>

<script setup>
import { ref } from "vue";
import SectionSlider from "../slider/SectionSlider.vue";
import CardStyle from "../cards/CardStyle.vue";
import { spacialLatestMovie } from "../../StaticData/data";
const title = ref("home.specials_latest_movies");
</script>

// ops/1-assets/1-app-templates/all/movies-prod/v5/react/frontend/src/components/sections/Specials&LatestMovies.jsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { spacialLatestMovie } from "../../StaticData/data";
// the hook
import { useTranslation } from "react-i18next";

const SpecialsLatestMovies = memo((props) => {
  const { t } = useTranslation();
  const [title] = useState(t("home.specials_latest_movies"));

  return (
    <Fragment>
      <SectionSlider
        title={title}
        list={spacialLatestMovie}
        className="recommended-block streamit-block"
        paddingY={props.paddingY}
      // loop={true}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={data.title}
            movieTime={data.movieTime}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

SpecialsLatestMovies.displayName = "SpecialsLatestMovies";
export default SpecialsLatestMovies;
