// ops/1-assets/1-app-templates/all/movies-prod/v5/react/frontend/src/components/blog/sidebar/RecentPost.jsx
import React, { Fragment, memo } from "react";

//react-router-dom
import { Link } from "react-router-dom";

//static data
import { blogRecent } from "../../../StaticData/blogs";

// the hook
import { useTranslation } from "react-i18next";
import { generateImgPath } from "../../../StaticData/data";

const RecentPost = memo(() => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <div className="widget iq-widget-blog">
        <h5 className="widget-title position-relative">
          {t("blogs.recent_post")}
        </h5>
        <ul className="list-inline p-0 m-0">
          {blogRecent.length === 0
            ? shimmerData.map((item, index) => <RecentShimmer key={index} />)
            : blogRecent.map((item, index) => {
              return (
                <li key={index} className="d-flex align-items-center gap-4">
                  <div className="img-holder">
                    <Link to="/blogs-detail">
                      {index === 0 ? <img
                        src={generateImgPath("/assets/images/blog/blog1.webp")}
                        className="img-fluid h-100 w-100 object-cover"
                        alt=""
                        loading="lazy"
                      /> : <img
                        src={item.thumbnail}
                        className="img-fluid h-100 w-100 object-cover"
                        alt=""
                        loading="lazy"
                      />}
                    </Link>
                  </div>
                  <div className="post-blog">
                    <Link to="/blogs-detail" className="new-link">
                      <h6 className="post-title">{t(item.title)}</h6>
                    </Link>
                    <ul className="list-inline mb-2">
                      <li className="list-inline-item border-0 mb-0 pb-0">
                        <Link className="blog-data" to="#">
                          <i
                            className="far fa-calendar-alt me-1"
                            aria-hidden="true"
                          ></i>
                          {item.blogDate}
                        </Link>
                      </li>
                    </ul>
                  </div>
                </li>
              );
            })}
        </ul>
      </div>
    </Fragment>
  );
});

RecentPost.displayName = "RecentPost";
export default RecentPost;

// ops/1-assets/1-app-templates/react/movies-prod/v5/vue/frontend/src/components/blog/sidebar/RecentPost.vue
<template>
  <div id="recent-posts-2" class="widget iq-widget-blog">
    <h5 class="widget-title position-relative">{{ $t('blogs.recent_post') }}</h5>
    <ul class="list-inline p-0 m-0">
      <li v-for="(post, index) in posts" :key="index" class="d-flex align-items-center gap-4">
        <div class="img-holder">
          <router-link :to="post.dateLink">
            <b-img :src="post.imageSrc" alt="" class="img-fluid h-100 w-100 object-cover"></b-img>
          </router-link>
        </div>
        <div class="post-blog">
          <router-link :to="{ name: 'landing-page.blogs.detail', params: { slug: 'the-most-anticipated-movies' } }">
            <h6 class="post-title">{{ $t(post.title) }}</h6>
          </router-link>
          <ul class="list-inline mb-2">
            <li class="list-inline-item border-0 mb-0 pb-0">
              <router-link :to="post.dateLink" class="blog-data"> <i class="far fa-calendar-alt me-1" aria-hidden="true"></i>{{ post.date }} </router-link>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</template>

<script setup>
import { ref } from 'vue';
const generateImgPath = (path) => {
  return window.origin + import.meta.env.BASE_URL + path;
};

const posts = ref([
  {
    title: 'blogs.anticipated_movies',
    imageSrc: generateImgPath('/assets/images/blog/blog1.webp'),
    link: '../blog/blog-detail.html',
    date: 'September 23, 2022',
    dateLink: '#',
  },
  {
    title: 'blogs.always_dreamed',
    imageSrc: generateImgPath('/assets/images/blog/blog2.webp'),
    link: '../blog/blog-detail.html',
    date: 'September 23, 2022',
    dateLink: '#',
  },
  {
    title: 'blogs.wanda_vision',
    imageSrc: generateImgPath('/assets/images/blog/blog3.webp'),
    link: '../blog/blog-detail.html',
    date: 'September 23, 2022',
    dateLink: '#',
  },
]);
</script>
