// ops/1-assets/2-app-templates/all/movies-prod/v5/next-js/src/pages/merchandise/checkout.tsx
import { memo } from "react";


// react-bootstrap
import { Container, Form, Row, Col, Table } from 'react-bootstrap';

// Custom Hook
import { useBreadcrumb } from "@/utilities/usePage";

// Next-Link
import Link from 'next/link'

// Next-Image
import Image from 'next/image'

// components
import CustomButton from '../../components/CustomButton';


// img
import img1 from '../../../public/assets/images/shop/product/01.webp';
import img2 from '../../../public/assets/images/shop/product/07.webp';
import img3 from '../../../public/assets/images/shop/product/05.webp'

const CheckoutPage = () => {
    useBreadcrumb('Checkout')
    return (
        <>
            <div className="checkout-page  section-padding">
                <Container>
                    <div className="main-cart mb-3 mb-md-5 pb-0 pb-md-5">
                        <ul className="cart-page-items d-flex justify-content-center list-inline align-items-center gap-3 gap-md-5 flex-wrap">
                            <li className="cart-page-item">
                                <span className=" cart-pre-number  border-radius rounded-circle me-1"> 1 </span>
                                <span className="cart-page-link ">
                                    Shopping Cart </span>
                            </li>
                            <li className="cart-page-item">
                                <svg width="25" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path fillRule="evenodd" clipRule="evenodd"
                                        d="M12 21.2498C17.108 21.2498 21.25 17.1088 21.25 11.9998C21.25 6.89176 17.108 2.74976 12 2.74976C6.892 2.74976 2.75 6.89176 2.75 11.9998C2.75 17.1088 6.892 21.2498 12 21.2498Z"
                                        stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                                    </path>
                                    <path d="M10.5576 15.4709L14.0436 11.9999L10.5576 8.52895" stroke="currentColor"
                                        strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"></path>
                                </svg>
                            </li>
                            <li className="cart-page-item  active">
                                <span className="cart-pre-heading badge cart-pre-number bg-primary border-radius rounded-circle me-1">
                                    2 </span>
                                <span className="cart-page-link ">
                                    Checkout </span>
                            </li>
                            <li className="cart-page-item">
                                <svg width="25" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path fillRule="evenodd" clipRule="evenodd"
                                        d="M12 21.2498C17.108 21.2498 21.25 17.1088 21.25 11.9998C21.25 6.89176 17.108 2.74976 12 2.74976C6.892 2.74976 2.75 6.89176 2.75 11.9998C2.75 17.1088 6.892 21.2498 12 21.2498Z"
                                        stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                                    </path>
                                    <path d="M10.5576 15.4709L14.0436 11.9999L10.5576 8.52895" stroke="currentColor"
                                        strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"></path>
                                </svg>
                            </li>
                            <li className="cart-page-item ">
                                <span className=" cart-pre-number  border-radius rounded-circle me-1"> 3 </span>
                                <span className="cart-page-link ">
                                    Order Summary </span>
                            </li>
                        </ul>
                    </div>
                    <div className="mb-5">
                        <div className="d-flex align-items-center justify-content-center gap-3 flex-wrap">
                            <div className="woocommerce-info">
                                <span className="text-primary"><i className="fa-solid fa-percent"></i></span>
                                <span className="text-body ps-2">Have a coupon?</span>
                                <Link href="#" data-bs-toggle="collapse" data-bs-target="#apply-coupon" className="text-white">Click here
                                    to enter your code</Link>
                            </div>
                        </div>
                        <div id="apply-coupon" className="collapse mt-5">
                            <Form className="checkout-coupon">
                                <p className="mt-0">If you have a coupon code, please apply it below.</p>
                                <div className="iq-checkout-coupon">
                                    <input name="coupon-code" type="text" required placeholder="Coupon code" className="form-control" />
                                    <CustomButton buttonTitle="apply coupon" link="#" linkButton="false" />
                                </div>
                            </Form>
                        </div>
                    </div>
                    <Row>
                        <Col lg="8" md="7">
                            <Form action="">
                                <h5 className="mb-4">Billing details</h5>
                                <div className="mb-4">
                                    <input name="first-name" type="text" required placeholder="First Name" className="form-control" />
                                </div>
                                <div className="mb-4">
                                    <input name="last-name" type="text" required placeholder="Last Name" className="form-control" />
                                </div>
                                <div className="mb-4">
                                    <input name="billing-company" type="text" required placeholder="Company" className="form-control" />
                                </div>
                                <div className="mb-4">
                                    <select className="select2-basic-single js-states form-control" aria-label="Default select example">
                                        <option defaultValue="">India</option>
                                        <option value="1">United Kingdom</option>
                                        <option value="2">United States</option>
                                        <option value="3">Australia</option>
                                        <option value="1">North Corea</option>
                                    </select>
                                </div>
                                <div className="mb-4">
                                    <input name="billing-address" type="text" required placeholder="House number and street name" className="form-control" />
                                </div>
                                <div className="mb-4">
                                    <input name="billing-address2" type="text" required placeholder="Apartment, suite, unit, etc. (optional)" className="form-control" />
                                </div>
                                <div className="mb-4">
                                    <input name="city" type="text" required placeholder="Town / City" className="form-control" />
                                </div>
                                <div className="mb-4">
                                    <select className="select2-basic-single js-states form-control" aria-label="Default select example">
                                        <option defaultValue="">Colorado</option>
                                        <option value="2">Alaska</option>
                                        <option value="1">Hawai</option>
                                        <option value="3">Texas</option>
                                        <option value="1">Washington</option>
                                    </select>
                                </div>
                                <div className="mb-4">
                                    <input name="postcode" type="text" required placeholder="ZIP Code" className="form-control" />
                                </div>
                                <div className="mb-4">
                                    <input name="phone" type="tel" required placeholder="Phone Number" className="form-control" />
                                </div>
                                <div className="mb-4">
                                    <input name="billing-company" type="email" required placeholder="E-mail Address" className="form-control rounded-0 mb-5" />
                                </div>
                                <h5 className="mb-4">Additional Information</h5>
                                <div className="mb-4">
                                    <label className="mb-2">Order notes (optional)</label>
                                    <textarea name="your-message" placeholder="Notes about your order, e.g. special notes for delivery." className="form-control mb-5" required></textarea>
                                </div>
                            </Form>
                        </Col>
                        <Col lg="4" md="5">
                            <div className="order_review-box border p-4">
                                <h5 className="mb-3 mt-0 mt-md-2">Product</h5>
                                <div className="checkout-review-order">
                                    <Table className="table w-100" responsive>
                                        <tbody>
                                            <tr className="cart_item">
                                                <td className="product-name">
                                                    <div className="product-image"><Image width="300" height="400" src={img1} className="cartimg" alt="image" loading="lazy" /></div>
                                                    <div className="text">
                                                        <span className="fw-500 text-body">Bag Pack</span><br /><strong className="text-white font-size-12 fw-bold">QTY:&nbsp;1</strong>
                                                    </div>
                                                </td>
                                                <td className="product-total">
                                                    <span className="Price-amount"><bdi className="fw-500 text-body"><span>$</span>28.00</bdi></span>
                                                </td>
                                            </tr>
                                            <tr className="cart_item">
                                                <td className="product-name">
                                                    <div className="product-image"><Image width="300" height="400" src={img2} className="cartimg" alt="image" loading="lazy" /></div>
                                                    <div className="text">
                                                        <span className="fw-500 text-body">cartoon-character</span><br /><strong className="text-white font-size-12 fw-bold">QTY:&nbsp;1</strong>
                                                    </div>
                                                </td>
                                                <td className="product-total">
                                                    <span className="Price-amount"><bdi className="fw-500 text-body"><span>$</span>25.00</bdi></span>
                                                </td>
                                            </tr>
                                            <tr className="cart_item">
                                                <td className="product-name">
                                                    <div className="product-image"><Image width="300" height="400" src={img3} className="cartimg" alt="image" loading="lazy" /></div>
                                                    <div className="text">
                                                        <span className="fw-500 text-body">Boxing Gloves</span><br /><strong className="text-white font-size-12 fw-bold">QTY:&nbsp;1</strong>
                                                    </div>
                                                </td>
                                                <td className="product-total">
                                                    <span className="Price-amount"><bdi className="fw-500 text-body"><span>$</span>18.00</bdi></span>
                                                </td>
                                            </tr>

                                        </tbody>
                                        <tfoot>
                                            <tr className="border-bottom">
                                                <td className="ps-0 p-3 fw-500 font-size-18">Subtotal</td>
                                                <td className="pe-0 p-3 fw-500 text-end">
                                                    <span className="mb-0 text-body">$71.00</span>
                                                </td>
                                            </tr>
                                            <tr className="border-bottom">
                                                <td className="ps-0 p-3 fw-500 font-size-18">Total</td>
                                                <td className="pe-0 p-3 fw-500 text-end">
                                                    <span className="text-primary mb-0">$71.00</span>
                                                </td>
                                            </tr>
                                        </tfoot>
                                    </Table>
                                    <div className="checkout-payment mt-4 pt-3 pb-2">
                                        <div className="payment-box border-bottom mb-5 pb-4">
                                            <div className="accordion" id="accordionPayment">
                                                <div className="accordion-item-payment">
                                                    <h6 className="accordion-header" id="payment-1">
                                                        <div className="accordion-button-payment" data-bs-toggle="collapse" data-bs-target="#collapseOnepayment" aria-expanded="true" aria-controls="collapseOnepayment">
                                                            <span className="form-check">
                                                                <input className="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" defaultChecked />
                                                                <label className="form-check-label" htmlFor="flexRadioDefault1">
                                                                    Direct bank transfer
                                                                </label>
                                                            </span>
                                                        </div>
                                                    </h6>
                                                    <div id="collapseOnepayment" className="accordion-collapse collapse show" data-bs-parent="#accordionPayment">
                                                        <div className="accordion-body">
                                                            Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account.
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className="accordion-item-payment">
                                                    <h6 className="accordion-header" id="payment-2">
                                                        <div className="accordion-button-payment collapsed" data-bs-toggle="collapse" data-bs-target="#collapseTwopayment" aria-expanded="false" aria-controls="collapseTwopayment">
                                                            <span className="form-check">
                                                                <input className="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" />
                                                                <label className="form-check-label" htmlFor="flexRadioDefault2">
                                                                    Check payments
                                                                </label>
                                                            </span>
                                                        </div>
                                                    </h6>
                                                    <div id="collapseTwopayment" className="accordion-collapse collapse" aria-labelledby="payment-2" data-bs-parent="#accordionPayment">
                                                        <div className="accordion-body">
                                                            Please send a check to Store Name, Store Street, Store Town, Store State / County, Store Postcode.
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className="accordion-item-payment">
                                                    <h6 className="accordion-header" id="payment-3">
                                                        <div className="accordion-button-payment collapsed" data-bs-toggle="collapse" data-bs-target="#collapseThreepayment" aria-expanded="false" aria-controls="collapseThreepayment">
                                                            <span className="form-check">
                                                                <input className="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault3" />
                                                                <label className="form-check-label" htmlFor="flexRadioDefault3">
                                                                    Cash on delivery
                                                                </label>
                                                            </span>
                                                        </div>
                                                    </h6>
                                                    <div id="collapseThreepayment" className="accordion-collapse collapse" aria-labelledby="payment-3" data-bs-parent="#accordionPayment">
                                                        <div className="accordion-body">
                                                            Pay with cash upon delivery.
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <p className="mt-3 mb-5">
                                            Your personal data will be used to process your order, support your experience
                                            throughout this website, and for other purposes described in our <Link href="/extra/privacy-policy">privacy policy</Link>
                                            .</p>
                                        <CustomButton buttonTitle="Place Order" link="/merchandise/track-order" linkButton="false" />
                                    </div>
                                </div>
                            </div>
                        </Col>
                    </Row>
                </Container>
            </div>
        </>
    );
};

export default CheckoutPage;

// ops/1-assets/1-templates/vue/movies-prod/v5/nuxt-js/pages/merchandise/checkout.vue
<template>
  <div class="checkout-page section-padding">
    <b-container>
      <div class="main-cart mb-3 mb-md-5 pb-0 pb-md-5">
        <ul
          class="cart-page-items d-flex justify-content-center list-inline align-items-center gap-3 gap-md-5 flex-wrap"
        >
          <li class="cart-page-item">
            <span class="cart-pre-number border-radius rounded-circle me-1">
              1
            </span>
            <span class="cart-page-link"> {{ $t("shop.shopping_cart") }} </span>
          </li>
          <li class="cart-page-item">
            <svg
              width="25"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M12 21.2498C17.108 21.2498 21.25 17.1088 21.25 11.9998C21.25 6.89176 17.108 2.74976 12 2.74976C6.892 2.74976 2.75 6.89176 2.75 11.9998C2.75 17.1088 6.892 21.2498 12 21.2498Z"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              ></path>
              <path
                d="M10.5576 15.4709L14.0436 11.9999L10.5576 8.52895"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              ></path>
            </svg>
          </li>
          <li class="cart-page-item active">
            <span
              class="cart-pre-heading badge cart-pre-number bg-primary border-radius rounded-circle me-1"
            >
              2
            </span>
            <span class="cart-page-link"> {{ $t("shop.checkout") }} </span>
          </li>
          <li class="cart-page-item">
            <svg
              width="25"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M12 21.2498C17.108 21.2498 21.25 17.1088 21.25 11.9998C21.25 6.89176 17.108 2.74976 12 2.74976C6.892 2.74976 2.75 6.89176 2.75 11.9998C2.75 17.1088 6.892 21.2498 12 21.2498Z"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              ></path>
              <path
                d="M10.5576 15.4709L14.0436 11.9999L10.5576 8.52895"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              ></path>
            </svg>
          </li>
          <li class="cart-page-item">
            <span class="cart-pre-number border-radius rounded-circle me-1">
              3
            </span>
            <span class="cart-page-link"> {{ $t("shop.order_summary") }} </span>
          </li>
        </ul>
      </div>
      <div class="mb-5">
        <div
          class="d-flex align-items-center justify-content-center gap-3 flex-wrap"
        >
          <div class="woocommerce-info">
            <span class="text-primary"
              ><i class="fa-solid fa-percent"></i
            ></span>
            <span class="text-body ps-2">{{ $t("shop.have_a_coupon") }}</span>
            <a
              href="#"
              data-bs-toggle="collapse"
              data-bs-target="#apply-coupon"
              class="text-white"
              >{{ $t("shop.enter_code") }}</a
            >
          </div>
        </div>
        <div id="apply-coupon" class="collapse mt-5">
          <form class="checkout-coupon">
            <p class="mt-0">
              {{ $t("shop.apply_coupon_code") }}
            </p>
            <div class="iq-checkout-coupon">
              <input
                name="coupon-code"
                type="text"
                required="required"
                placeholder="Coupon code"
                class="form-control"
              />
              <div class="iq-button">
                <a href="#" class="btn text-uppercase position-relative">
                  <span class="button-text">{{ $t("shop.apply_coupon") }}</span>
                  <i class="fa-solid fa-play"></i>
                </a>
              </div>
            </div>
          </form>
        </div>
      </div>
      <b-row>
        <div class="col-lg-8 col-md-7">
          <form action="#">
            <h5 class="mb-4">{{ $t("shop.billing_details") }}</h5>
            <div class="mb-4">
              <input
                name="first-name"
                type="text"
                required="required"
                placeholder="shop.first_name"
                class="form-control"
              />
            </div>
            <div class="mb-4">
              <input
                name="last-name"
                type="text"
                required="required"
                placeholder="shop.last_name"
                class="form-control"
              />
            </div>
            <div class="mb-4">
              <input
                name="billing-company"
                type="text"
                required="required"
                placeholder="shop.company_name"
                class="form-control"
              />
            </div>
            <div class="mb-4">
              <select class="form-control">
                <option selected="">{{ $t("shop.india") }}</option>
                <option value="1">{{ $t("shop.united_kindom") }}</option>
                <option value="2">{{ $t("shop.united_states") }}</option>
                <option value="3">{{ $t("shop.australia") }}</option>
                <option value="1">{{ $t("shop.north_corea") }}</option>
              </select>
            </div>
            <div class="mb-4">
              <input
                name="billing-address"
                type="text"
                required="required"
                placeholder="shop.billing_address"
                class="form-control"
              />
            </div>
            <div class="mb-4">
              <input
                name="billing-address2"
                type="text"
                required="required"
                placeholder="shop.apartment"
                class="form-control"
              />
            </div>
            <div class="mb-4">
              <input
                name="city"
                type="text"
                required="required"
                placeholder="Town / City"
                class="form-control"
              />
            </div>
            <div class="mb-4">
              <select class="form-control">
                <option selected="">{{ $t("shop.colorado") }}</option>
                <option value="2">{{ $t("shop.alaska") }}</option>
                <option value="1">{{ $t("shop.hawai") }}</option>
                <option value="3">{{ $t("shop.texas") }}</option>
                <option value="1">{{ $t("shop.washington") }}</option>
              </select>
            </div>
            <div class="mb-4">
              <input
                name="postcode"
                type="text"
                required="required"
                placeholder="ZIP Code"
                class="form-control"
              />
            </div>
            <div class="mb-4">
              <input
                name="phone"
                type="tel"
                required="required"
                placeholder="Phone Number"
                class="form-control"
              />
            </div>
            <div class="mb-4">
              <input
                name="billing-company"
                type="email"
                required="required"
                placeholder="E-mail Address"
                class="form-control rounded-0 mb-5"
              />
            </div>
            <h5 class="mb-4">{{ $t("shop.additional_information") }}</h5>
            <div class="mb-4">
              <label class="mb-2">{{ $t("shop.order_notes") }}</label>
              <textarea
                name="your-message"
                placeholder="Notes about your order, e.g. special notes for delivery."
                class="form-control mb-5"
                required=""
              ></textarea>
            </div>
          </form>
        </div>
        <b-col lg="4" md="5">
          <div class="order_review-box border p-4">
            <h5 class="mb-3 mt-0 mt-md-2">{{ $t("shop.product") }}</h5>
            <div
              v-for="data in myCart"
              :key="data"
              class="checkout-review-order"
            >
              <div class="table-responsive">
                <checkout-card
                  :thumbnail="data.thumbnail"
                  :slug="data.slug"
                  :product-name="$t(data.product_name)"
                  :final-price="data.final_price"
                />
                <div id="payment" class="checkout-payment mt-4 pt-3 pb-2">
                  <div class="payment-box border-bottom mb-5 pb-4">
                    <div class="payli">
                      <div class="form-check">
                        <input
                          id="directradio1"
                          class="form-check-input"
                          type="radio"
                          name="directradio"
                        />
                        <label class="form-check-label" for="directradio1">
                          {{ $t("shop.bank_transfer") }}
                        </label>
                      </div>
                      <div class="bank">
                        <p>
                          {{ $t("shop.make_direct_payment") }}
                        </p>
                      </div>
                    </div>
                    <div class="payli">
                      <div class="form-check">
                        <input
                          id="checkradio1"
                          class="form-check-input"
                          type="radio"
                          name="checkradio"
                        />
                        <label class="form-check-label" for="checkradio1">
                          {{ $t("shop.cheque_payments") }}
                        </label>
                      </div>
                      <div class="rpay">
                        <p>
                          {{ $t("shop.cheque_to_store") }}
                        </p>
                      </div>
                    </div>
                    <div class="payli">
                      <div class="form-check">
                        <input
                          id="cashradio1"
                          class="form-check-input"
                          type="radio"
                          name="cashradio"
                        />
                        <label class="form-cash-label" for="cashradio1">
                          {{ $t("shop.cod") }}
                        </label>
                      </div>
                      <div class="rpay">
                        <p>{{ $t("shop.pay_with_cash") }}</p>
                      </div>
                    </div>
                  </div>
                  <div class="place-order">
                    <p class="">
                      {{ $t("shop.your_personal_data") }}
                      <nuxt-link
                        :to="{ name: 'extra-privacy-policy' }"
                        class="final text-primary"
                        target="_blank"
                      >
                        {{ $t("shop.privacy_policy") }}</nuxt-link
                      >.
                    </p>
                    <div class="iq-button">
                      <nuxt-link
                        :to="{ name: 'merchandise-track-order' }"
                        class="btn text-uppercase position-relative"
                      >
                        <span class="button-text">{{
                          $t("shop.place_order")
                        }}</span>
                        <i class="fa-solid fa-play"></i>
                      </nuxt-link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script setup>
//components
import CheckoutCard from "../../components/merchandise/CheckoutCard.vue";

//data
import { myCart } from "../../StaticData/shop";

//custom hooks
import { useBreadcrumb } from "~/utilities/usePage";

useBreadcrumb("Checkout");
</script>
