// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/components/sections/ShowsWeRecommend.jsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { recommendedforYou } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const ShowsWeRecommend = memo((props) => {
  const { t } = useTranslation();

  return (
    <Fragment>
      <SectionSlider
        title={t("form.shows_recommend")}
        list={recommendedforYou}
        className="recommended-block streamit-block"
        slideMedium={props.slideMedium}
        paddingY={props.paddingY}
      // loop={true}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

ShowsWeRecommend.displayName = "ShowsWeRecommend";
export default ShowsWeRecommend;

// ops/1-assets/1-app-templates/all/movies-prod/v5/nuxt-js/components/sections/ShowsWeRecommend.vue
<template>
  <!-- Shows We Recommend start -->
  <SectionSlider
    :title="$t(title)"
    :list="recommendedforYou"
    :slides-per-view="6"
    class="recommended-block streamit-block"
  >
    <template #headerLink>
      <nuxt-link
        :to="{ name: 'view-all' }"
        class="text-primary iq-view-all text-decoration-none flex-none"
        >{{ $t("ott_home.view_all") }}</nuxt-link
      >
    </template>
    <template #default="{ data }">
      <card-style
        :image="data.image"
        :title="$t(data.title)"
        :movie-time="data.movieTime"
        :watchlist-link="{ name: 'play-list' }"
        :link="{ name: 'movies-detail' }"
      ></card-style>
    </template>
  </SectionSlider>
  <!-- Shows We Recommend end -->
</template>

<script setup>
import { ref } from "vue";
import SectionSlider from "../slider/SectionSlider.vue";
import CardStyle from "../cards/CardStyle.vue";
import { recommendedforYou } from "../../StaticData/data";
const title = ref("form.shows_recommend");
</script>
