// frontend/7-svelte/1-svelteKit-mpa/2-svelteKit-syntax(초급-기초)/9-general-app/app1/src/routes/news/+page.svelte
<NavBar />
<TitleLabel title="News App" />

{#if news.length <= 0}
  <p>Loading...</p>
{:else}
  <ul>
    {#each news as item}
      <li><a class="newsItem" href={item.url} target="_blank">{item.title} / {item.user}</a></li>
    {/each}
  </ul>
{/if}

<script>
import NavBar from 'src/components/models/NavBar/index.svelte';
import TitleLabel from 'src/components/atoms/TitleLabel/index.svelte';

import { onMount } from 'svelte'

let news = [];

const fetchNews = async () => {
  const res = await fetch('https://api.hnpwa.com/v0/news.json');
  news = await res.json();
  console.log(news);
}

onMount(() => {
  fetchNews();
});
</script>

<style>
.newsItem {
  display: block;
  text-decoration: none;
  color: black;
}
.newsItem:hover {
  text-decoration: underline;
  color: gray;
}
</style>

// start/9-workspace/saitou/4-react/1-syntax-basic/9-newsapp/app1/src/components/News.js
import React from "react";
import { useState, useEffect } from "react";
import "./News.css";

export default function News() {
  const [news, setNews] = useState([]);

  // mounted
  useEffect(() => {
    fetch("https://api.hnpwa.com/v0/news.json")
      .then((res) => res.json())
      .then((json) => {
        setNews(json);
      });
  }, []);

  console.log("news: ", news);

  const render = news.map((item) => {
    return (
      <div key={item.id}>
        <a className="newsTitle" target="_blank" href={item.url}>
          {item.title}
        </a>
        <span> / ID: {item.user}</span>
      </div>
    );
  });

  return (
    <div>
      <h1>News</h1>
      <div>{render}</div>
    </div>
  );
}
