// ops/1-assets/1-app-templates/react/movies-prod/v5/vue/frontend/src/components/cards/EpisodeCard.vue
<template>
  <div class="episode-block">
    <div class="block-image position-relative">
      <router-link :to="link">
        <img :src="image" class="img-fluid img-zoom" loading="lazy" />
      </router-link>
      <div class="episode-number">{{ showEpisod }}</div>
      <div class="episode-play">
        <router-link :to="{ name: 'landing-page.episode' }" tabindex="0">
          <i class="fa-solid fa-play"></i>
          {{ '' }}
        </router-link>
      </div>
    </div>
    <div class="epi-desc p-3">
      <div class="d-flex align-items-center justify-content-between mb-3">
        <span class="border-gredient-left text-white rel-date">{{ episodDate }}</span>
        <span class="text-primary run-time">{{ episodTime }}</span>
      </div>
      <router-link :to="{ name: 'landing-page.episode' }">
        <h5 class="epi-name text-white mb-0">{{ $t(episodTitle) }}</h5>
      </router-link>
    </div>
  </div>
</template>
<script setup>
defineProps({
  image: { type: String, default: '' },
  link: { type: String, default: '/' },
  showEpisod: { type: String, default: '' },
  episodDate: { type: String, default: '' },
  episodTime: { type: String, default: '' },
  episodTitle: { type: String, default: '' },
});
</script>

// ops/1-assets/1-templates/react/bootstrap-movies-prod/v5/react/frontend/src/components/cards/EpisodeCard.jsx
import { Fragment, memo } from "react";

//react-router-dom
import { Link } from "react-router-dom";

//hook
import { useTranslation } from "react-i18next";

const EpisodeCard = memo(
  ({ image, link, showEpisod, episodDate, episodTime, episodTitle }) => {
    const { t } = useTranslation();
    return (
      <Fragment>
        <div className="episode-block">
          <div className="block-image position-relative">
            <Link to={link}>
              <img
                src={image}
                className="img-fluid img-zoom"
                loading="lazy"
                alt=""
              />
            </Link>
            <div className="episode-number">{showEpisod}</div>
            <div className="episode-play">
              <Link to="/episodes" tabIndex="0">
                <i className="fa-solid fa-play"></i>
              </Link>
            </div>
          </div>
          <div className="epi-desc p-3">
            <div className="d-flex align-items-center justify-content-between mb-3">
              <span className="border-gredient-left text-white rel-date">
                {t(episodDate)}
              </span>
              <span className="text-primary run-time">{t(episodTime)}</span>
            </div>
            <Link to="/episodes">
              <h5 className="epi-name text-white mb-0">{t(episodTitle)}</h5>
            </Link>
          </div>
        </div>
      </Fragment>
    );
  }
);

EpisodeCard.displayName = "EpisodeCard";
export default EpisodeCard;
