// ops/1-assets/1-app-templates/all/movies-prod/v5/next-js/src/pages/extra/AboutSections/TeamSection.tsx
import { Fragment, memo, useState } from "react";

//react bootstrap
import { Col, Container, Row } from "react-bootstrap";

//components
import ProfileCard from "../../../components/cards/ProfileCard";

//function
import { generateImgPath } from "../../../StaticData/data";

const TeamSection = memo(() => {
  const [lists] = useState([
    {
      image: generateImgPath("/assets/images/pages/team1.webp"),
      designation: "CEO",
      name: "Tonny Smith",
    },
    {
      image: generateImgPath("/assets/images/pages/team2.webp"),
      designation: "Designer",
      name: "Barry Tech",
    },
    {
      image: generateImgPath("/assets/images/pages/team3.webp"),
      designation: "Developer",
      name: "kep John",
    },
    {
      image: generateImgPath("/assets/images/pages/team4.webp"),
      designation: "Designer",
      name: "Monty Rock",
    },
  ]);
  return (
    <Fragment>
      <section className="section-padding">
        <Container>
          <Row className="align-items-center">
            <Col lg="3"></Col>
            <Col lg="6" md="12">
              <div className="title-box text-center">
                <h2>Masterminds Team</h2>
                <p className="mb-0">
                  Your Streamit is build by one of the best and well experienced
                  web developers and an awarded Envato Elite Author.
                </p>
              </div>
            </Col>
            <Col lg="3"></Col>
          </Row>
          <Row className="about-us-detail">
            {lists.map((data, index) => (
              <Col md="3" className="mb-4" key={index} >
                <ProfileCard
                  name={data.name}
                  designation={data.designation}
                  image={data.image}
                ></ProfileCard>
              </Col>
            ))}
          </Row>
        </Container>
      </section>
    </Fragment>
  );
});

TeamSection.displayName = "TeamSection";
export default TeamSection;

// ops/1-assets/1-app-templates/all/movies-prod/v5/nuxt-js/pages/extra/AboutSections/TeamSection.vue
<template>
  <b-container>
    <b-row class="align-items-center">
      <b-col lg="3"></b-col>
      <b-col lg="6" md="12">
        <div class="title-box text-center">
          <h2 class="">{{ $t("about_us.mastermind_team") }}</h2>
          <p class="mb-0">
            {{ $t("about_us.streamit_build") }} <br />{{
              $t("about_us.envato_author")
            }}
          </p>
        </div>
      </b-col>
      <b-col lg="3"></b-col>
    </b-row>
    <div class="row about-us-detail">
      <div v-for="(data, index) of lists" :key="index" class="col-md-3 mb-4">
        <ProfileCard
          :name="$t(data.name)"
          :designation="$t(data.designation)"
          :image="data.image"
        ></ProfileCard>
      </div>
    </div>
  </b-container>
</template>
<script setup>
import { reactive } from "vue";
import ProfileCard from "../../../components/cards/ProfileCard.vue";
import { generateImgPath } from "../../../StaticData/data";
const lists = reactive([
  {
    image: generateImgPath("/assets/images/pages/team1.webp"),
    designation: "about_us.ceo",
    name: "about_us.tonny_smith",
  },
  {
    image: generateImgPath("/assets/images/pages/team2.webp"),
    designation: "about_us.designer",
    name: "about_us.barry_tech",
  },
  {
    image: generateImgPath("/assets/images/pages/team3.webp"),
    designation: "about_us.developer",
    name: "about_us.kep_john",
  },
  {
    image: generateImgPath("/assets/images/pages/team4.webp"),
    designation: "about_us.designer",
    name: "about_us.monty_rock",
  },
]);
</script>
