// frontend/6-vue/1-vue3/7-BFF/2-bff-client/old/3-client-query-select(roles)/app1/src/views/Teams.vue
<template>
  <div id="teams" class="component">
    <aside>
      <aside-items/>
    </aside>
    <section class="contents">
      <main-contents/>
    </section>
  </div>
</template>

<script>
export default {
  name: 'Teams',
  components: {
    AsideItems: {
      render: function(createElement) {
        return createElement('div')
      }
    },
    MainContents: {
      render: function(createElement) {
        return createElement('div')
      }
    }
  }
}
</script>

// apps/apps/react/app-basic-template/app1/src/components/teams.js
import "./components.css"

export default function Teams() {
  // 메인화면 왼쪽의 사이드 섹션 리스트가 나타날 곳
  function AsideItems() {
    return <div></div>
  }

  // 메인화면	리스트 각 항목의 내용부가 표시될 곳
  function MainContents() {
    return <div></div>
  }

  return (
    <div id="teams" className="component">
      <aside>{AsideItems()}</aside>
      <section className="contents">{MainContents()}</section>
    </div>
  )
}
