// frontend/6-vue/2-vue3/1-vue-syntax/2-vue-syntax(초급)/12-ec-app/1-Login-Products/app1/src/views/Login.vue
<template>
  <div>
    <h1>Login</h1>

    <NoLogin v-if="!isLogin" />

    <form @submit="onSubmit">
      <input v-if="!isLogin" class="input" type="email" v-model="id" placeholder="email를 입력해주세요."/>
      <input v-if="!isLogin" class="input" type="password" v-model="pw" placeholder="password를 입력해주세요." />
      <input v-if="!isLogin" type="submit" value="로그인" />
      <input v-if="isLogin" type="submit" value="로그아웃" />
    </form>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import NoLogin from '@/components/NoLogin.vue'

const id = ref('')
const pw = ref('')
const isLogin = ref(localStorage.getItem('isAuth') === 'true')

function onSubmit (e) {
  e.preventDefault()
  if (isLogin.value === false) {
    if (id.value && id.value === "admin@admin.com" && pw.value && pw.value === "admin") {
      localStorage.setItem('isAuth', 'true')
      isLogin.value = localStorage.getItem('isAuth') === 'true'
    } else {
      alert("아이디와 비밀번호를 확인해주세요.")
    }
  } else {
    localStorage.setItem('isAuth', 'false')
    isLogin.value = localStorage.getItem('isAuth') === 'true'
  }
}
</script>

<style scoped>
.input {
  display: block;
}
</style>

// start/8-workspace/7-kang-dh/react/2-typescript/react-ts3/src/Components/Login/index.tsx
import React, { useState } from 'react'

type LoginProps = {
  onSubmit: (form: { id: string, pw: string }) => void
}

export default function Login({ onSubmit }: LoginProps) {
  const [form, setForm] = useState({
    id: '',
    pw: ''
  })
  const [isLogin, setLogin] = useState<boolean>(false)
  const [user, setUser] = useState<string>('')

  const { id, pw } = form

  const onChange = (e: { target: { name: any; value: any } }) => {
    const { name, value } = e.target
    setForm({
      ...form,
      [name]: value
    })
  }

  const handleSumit = (e: { preventDefault: () => void }) => {
    e.preventDefault()
    onSubmit(form)
    setLogin(true)
    setUser(id)
    setForm({
      id: '',
      pw: ''
    })
  }

  return (
    <div>
      {!isLogin && (
        <form onSubmit={handleSumit}>
          <input name="id" type="text" placeholder='id 입력해주세요' value={id} onChange={onChange} />
          <input name="pw" type="password" placeholder='pw 입력해주세요' value={pw} onChange={onChange} />
          <button type="submit">로그인</button>
        </form>
      )}

      {isLogin && (
        <div>{user}님, 환영합니다.</div>
      )}
    </div>
  )
}
