// ops/1-assets/1-app-templates/vue/movies-prod/v5/nuxt-js/components/sections/BestOfInternationalShows.vue
<template>
  <!-- Best Of International Shows start -->
  <SectionSlider
    :title="$t(title)"
    :list="latestMovie"
    :slides-per-view="6"
    class="recommended-block section-top-spacing streamit-block"
  >
    <template #headerLink>
      <nuxt-link
        :to="{ name: 'view-all' }"
        class="text-primary iq-view-all text-decoration-none flex-none"
        >V{{ $t("ott_home.view_all") }}</nuxt-link
      >
    </template>
    <template #default="{ data }">
      <card-style
        :image="data.image"
        :title="$t(data.title)"
        :movie-time="data.movieTime"
        :watchlist-link="{ name: 'play-list' }"
        :link="{ name: 'movies-detail' }"
      ></card-style>
    </template>
  </SectionSlider>
  <!-- Best Of International Shows end -->
</template>

<script setup>
import { ref } from "vue";
import SectionSlider from "../slider/SectionSlider.vue";
import CardStyle from "../cards/CardStyle.vue";
import { latestMovie } from "../../StaticData/data";
const title = ref("form.international_shows");
</script>

// ops/1-assets/1-app-templates/react/movies-prod/v5/next-js/src/components/sections/BestOfInternationalShows.tsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { latestMovie } from "../../StaticData/data";

const BestOfInternationalShows = memo(()=> {
  const [title] = useState("Best Of InternationalShows");

  return (
    <Fragment>
      <SectionSlider
        title={title}
        list={latestMovie}
        className="recommended-block section-top-spacing streamit-block"
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={data.title}
            movieTime={data.movieTime}
            watchlistLink="/play-list"
            link="/movies/detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
})

BestOfInternationalShows.displayName = 'BestOfInternationalShows';
export default BestOfInternationalShows;
