// start/8-workspace/4-kim-jy-shin-kh/7-react-ts/4-ts-loginapp/app1/src/Login.tsx
import React, { useState } from 'react'

type formProps = {
  id: string,
  pw: string
}

type LoginProps = {
  onSubmit: (form: formProps) => void,
}

export default function Login({ onSubmit }: LoginProps) {
  const [form, setForm] = useState({
    id: '',
    pw: ''
  })

  const { id, pw } = form

  const handleSubmit = (e: { preventDefault: () => void }) => {
    e.preventDefault()
    onSubmit(form)
    setForm({
      id: '',
      pw: ''
    })
  }

  const onChange = (e: { preventDefault: () => void; target: { name: string; value: string } }) => {
    e.preventDefault()
    const { name, value } = e.target
    setForm({
      ...form,
      [name]: value
    })
  }

  return (
    <div className="inputs">
      <form onSubmit={handleSubmit}>
        <input name="id" type="text" value={id} placeholder='id를 입력해주세요' onChange={onChange}></input>
        <input name="pw" type="password" value={pw} placeholder='pw를 입력해주세요' onChange={onChange}></input>
        <input type="submit" value="로그인"></input>
      </form>
    </div>
  )
}

// frontend/6-vue/2-vue3/1-vue-syntax/2-vue-syntax(초급)/12-ec-app/1-Login-Products/app1/src/views/Login.vue
<template>
  <div>
    <h1>Login</h1>

    <NoLogin v-if="!isLogin" />

    <form @submit="onSubmit">
      <input v-if="!isLogin" class="input" type="email" v-model="id" placeholder="email를 입력해주세요."/>
      <input v-if="!isLogin" class="input" type="password" v-model="pw" placeholder="password를 입력해주세요." />
      <input v-if="!isLogin" type="submit" value="로그인" />
      <input v-if="isLogin" type="submit" value="로그아웃" />
    </form>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import NoLogin from '@/components/NoLogin.vue'

const id = ref('')
const pw = ref('')
const isLogin = ref(localStorage.getItem('isAuth') === 'true')

function onSubmit (e) {
  e.preventDefault()
  if (isLogin.value === false) {
    if (id.value && id.value === "admin@admin.com" && pw.value && pw.value === "admin") {
      localStorage.setItem('isAuth', 'true')
      isLogin.value = localStorage.getItem('isAuth') === 'true'
    } else {
      alert("아이디와 비밀번호를 확인해주세요.")
    }
  } else {
    localStorage.setItem('isAuth', 'false')
    isLogin.value = localStorage.getItem('isAuth') === 'true'
  }
}
</script>

<style scoped>
.input {
  display: block;
}
</style>
