// ops/1-assets/1-app-templates/react/movies-prod/v5/nuxt-js/components/partials/FooterDefault.vue
<template>
  <footer class="footer footer-default">
    <div class="container-fluid">
      <div class="footer-top">
        <div class="row">
          <div class="col-xl-3 col-lg-6 mb-5 mb-lg-0">
            <div class="footer-logo">
              <BrandLogo></BrandLogo>
            </div>
            <p class="mb-4 font-size-14">
              {{ $t("footer.email_us") }}:
              <span class="text-white">customer@streamit.com</span>
            </p>
            <p class="text-uppercase letter-spacing-1 font-size-14 mb-1">
              {{ $t("footer.customer_services") }}
            </p>
            <p class="mb-0 contact text-white">+ (480) 555-0103</p>
          </div>
          <div class="col-xl-2 col-lg-6 mb-5 mb-lg-0">
            <h4 class="footer-link-title">{{ $t("footer.quick_links") }}</h4>
            <ul class="list-unstyled footer-menu">
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'extra-about-us' }">
                  {{ $t("header.about_us") }}
                </nuxt-link>
              </li>
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'blogs' }">
                  {{ $t("header.blog") }}
                </nuxt-link>
              </li>
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'pricing-plan' }">
                  {{ $t("header.pricing_plan") }}
                </nuxt-link>
              </li>
              <li>
                <nuxt-link class="ms-3" :to="{ name: 'extra-faq' }">
                  {{ $t("header.faq") }}
                </nuxt-link>
              </li>
            </ul>
          </div>
          <div class="col-xl-2 col-lg-6 mb-5 mb-lg-0">
            <h4 class="footer-link-title">
              {{ $t("footer.movies_to_watch") }}
            </h4>
            <ul class="list-unstyled footer-menu">
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'view-all' }">
                  {{ $t("footer.top_trending") }}</nuxt-link>
              </li>
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'view-all' }">
                  {{ $t("footer.recommended") }}
                </nuxt-link>
              </li>
              <li>
                <nuxt-link class="ms-3" :to="{ name: 'view-all' }">
                  {{ $t("footer.popular") }}
                </nuxt-link>
              </li>
            </ul>
          </div>
          <div class="col-xl-2 col-lg-6 mb-5 mb-lg-0">
            <h4 class="footer-link-title">{{ $t("footer.about_company") }}</h4>
            <ul class="list-unstyled footer-menu">
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'extra-contact-us' }">{{ $t("header.contact_us") }}
                </nuxt-link>
              </li>
              <li class="mb-3">
                <nuxt-link class="ms-3" :to="{ name: 'extra-privacy-policy' }">
                  {{ $t("header.privacy_policy") }}
                </nuxt-link>
              </li>
              <li>
                <nuxt-link class="ms-3" :to="{ name: 'extra-terms-of-use' }">
                  {{ $t("footer.terms_of_use") }}
                </nuxt-link>
              </li>
            </ul>
          </div>
          <div class="col-xl-3 col-lg-6">
            <h4 class="footer-link-title">
              {{ $t("footer.subscribe_newsletter") }}
            </h4>
            <div class="mailchimp mailchimp-dark">
              <div class="input-group mb-3 mt-4">
                <input type="text" class="form-control mb-0 font-size-14" :placeholder="$t('footer.email')"
                  aria-describedby="button-addon2" />
                <div class="iq-button">
                  <button id="button-addon2" type="submit" class="btn btn-sm">
                    {{ $t("footer.subscribe") }}
                  </button>
                </div>
              </div>
            </div>
            <div class="d-flex align-items-center mt-5">
              <span class="font-size-14 me-2">{{
                $t("footer.follow_us")
              }}</span>
              <ul class="p-0 m-0 list-unstyled widget_social_media">
                <li class="">
                  <a href="https://www.facebook.com/" class="position-relative">
                    <i class="fab fa-facebook"></i>
                  </a>
                </li>
                {{
                  " "
                }}
                <li class="">
                  <a href="https://twitter.com/" class="position-relative">
                    <i class="fab fa-twitter"></i>
                  </a>
                </li>
                {{
                  " "
                }}
                <li class="">
                  <a href="https://github.com/" class="position-relative">
                    <i class="fab fa-github"></i>
                  </a>
                </li>
                {{
                  " "
                }}
                <li class="">
                  <a href="https://www.instagram.com/" class="position-relative">
                    <i class="fab fa-instagram"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-bottom border-top">
        <div class="row align-items-center">
          <div class="col-md-6">
            <ul class="menu list-inline p-0 d-flex flex-wrap align-items-center">
              <li class="menu-item">
                <nuxt-link :to="{ name: 'extra-terms-of-use' }">{{ $t("footer.terms_of_use") }}
                </nuxt-link>
              </li>
              <li id="menu-item-7316" class="menu-item">
                <nuxt-link :to="{ name: 'extra-privacy-policy' }">{{ $t("footer.privacy-policy") }}
                </nuxt-link>
              </li>
              <li class="menu-item">
                <nuxt-link :to="{ name: 'extra-faq' }">{{ $t("header.faq") }}
                </nuxt-link>
              </li>
              <li class="menu-item">
                <nuxt-link :to="{ name: 'play-list' }">{{ $t("footer.watch_list") }}
                </nuxt-link>
              </li>
            </ul>
            <p class="font-size-14">
              © <span class="currentYear">2024 </span>
              <span class="text-primary">STREAMIT</span>.{{ $t("footer.desc") }}
            </p>
          </div>
          <div class="col-md-3"></div>
          <div class="col-md-3">
            <h6 class="font-size-14 pb-1">
              {{ $t("footer.download_app") }}
            </h6>
            <div class="d-flex align-items-center">
              <a class="app-image" href="#">
                <img src="/assets/images/footer/google-play.webp" loading="lazy" alt="play-store" />
              </a>
              <br />
              <a class="ms-3 app-image" href="#">
                <img src="/assets/images/footer/apple.webp" loading="lazy" alt="app-store" />
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <div id="back-to-top" style="display: none" class="animate__animated" :class="animationClass" @click="scrollToTop">
    <a id="top" class="p-0 btn bg-primary btn-sm position-fixed top border-0 rounded-circle" href="#top">
      <i class="fa-solid fa-chevron-up"></i>
    </a>
  </div>
</template>
<script setup>
import { ref, watch, onMounted, onBeforeUnmount } from "vue";
import BrandLogo from "../brand/BrandLogo.vue";
import { useRoute } from "vue-router";

const animationClass = ref("animate__fadeIn");

const scrollToTop = () => {
  window.scrollTo({ top: 0, behavior: "smooth" });
};

const handleScroll = () => {
  if (document.documentElement.scrollTop > 250) {
    animationClass.value = "animate__fadeIn";
  } else {
    animationClass.value = "animate__fadeOut";
  }
};
handleScroll();
onBeforeUnmount(() => {
  window.removeEventListener("scroll", handleScroll);
});

onMounted(() => {
  window.addEventListener("scroll", handleScroll);
});

const route = useRoute();
watch(
  () => route.name,
  () => {
    scrollToTop();
  }
);
</script>

// ops/1-assets/1-app-templates/vue/movies-prod/v5/react/frontend/src/components/merchandise/partials/FooterDefault.jsx
import React, { Fragment, memo } from "react";

//react-bootstrap
import { Button, Col, Container, Form, Row } from "react-bootstrap";

//react-router-dom
import { Link } from "react-router-dom";

//components
import Logo from "../../logo";

// the hook
import { useTranslation } from "react-i18next";
import { generateImgPath } from "../../../StaticData/data";

const MerchandiseFooter = memo(() => {
  const { t } = useTranslation();
  const currentYear = new Date().getFullYear();
  return (
    <Fragment>
      <footer className="footer-merchandise">
        <div className="footer-top">
          <Container fluid>
            <Row>
              <Col lg="4" sm="6">
                <div className="footer-inner">
                  <p className="text-uppercase letter-spacing-1 font-size-14 mb-1">
                    {t("footer.customer_services")}
                  </p>
                  <h4 className="mb-0 contact text-white fw-bold">
                    <Link to="tel:+4805550103"> + (480) 555-0103</Link>
                  </h4>
                  <span className="d-inline-block mt-4 mb-0 font-size-14">
                    {" "}
                    {t("footer.email_us")}:{" "}
                    <Link to="maito:customer@streamit.com">
                      {t("footer.customer@stremit")}
                    </Link>
                  </span>
                  <div className="mt-5">
                    <p className="letter-spacing-1 font-size-14 mb-1 text-uppercase">
                      {t("footer.stay_connected")}:
                    </p>
                    <ul className="p-0 mt-4 mb-0 list-unstyled widget_social_media d-flex gap-1">
                      <li className="">
                        <Link
                          to="https://www.facebook.com/"
                          target="_blank"
                          className="position-relative"
                        >
                          <i className="fab fa-facebook"></i>
                        </Link>
                      </li>
                      <li className="">
                        <Link
                          to="https://twitter.com/"
                          target="_blank"
                          className="position-relative"
                        >
                          <i className="fab fa-twitter"></i>
                        </Link>
                      </li>
                      <li className="">
                        <Link
                          to="https://github.com/"
                          target="_blank"
                          className="position-relative"
                        >
                          <i className="fab fa-github"></i>
                        </Link>
                      </li>
                      <li className="">
                        <Link
                          to="https://www.instagram.com/"
                          target="_blank"
                          className="position-relative"
                        >
                          <i className="fab fa-instagram"></i>
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </Col>
              <Col lg="4" sm="6" className="mt-sm-0 mt-5">
                <div className="footer-inner position-relative text-center px-xl-5 px-3">
                  <div className="vr text-dark opacity-100 h-100 position-absolute end-0 top-0 d-lg-inline-block d-none"></div>
                  <div className="footer-logo">
                    <Logo />
                  </div>
                  <p className="mt-lg-5 mt-4 mb-3 text-uppercase letter-spacing-1 font-size-14 mb-1">
                    {t("footer.best_deals")}
                  </p>
                  <div className="mailchimp mailchimp-dark">
                    <div className="input-group mb-3 mt-4">
                      <Form.Control
                        type="text"
                        className="mb-0 font-size-14"
                        placeholder={t("footer.email")}
                      />
                      <div className="iq-button">
                        <Button
                          type="submit"
                          className="btn btn-sm"
                          id="button-addon2"
                        >
                          {t("footer.subscribe")}
                        </Button>
                      </div>
                    </div>
                    <span className="d-inline-block font-size-14">
                      * {t("footer.email_anyone")}
                    </span>
                  </div>
                  <div className="vr text-dark opacity-100 h-100 position-absolute start-0 top-0 d-lg-inline-block d-none"></div>
                </div>
              </Col>
              <Col lg="4" sm="12" className="mt-lg-0 mt-5">
                <div className="footer-inner">
                  <h5 className="footer-link-title mb-3">
                    {t("footer.quick_links")}
                  </h5>
                  <Row>
                    <Col lg="6">
                      <ul className="list-unstyled footer-menu mb-0">
                        <li className="mb-2">
                          <Link to="/contact-us" className="ms-3">
                            {t("header.contact_us")}
                          </Link>
                        </li>
                        <li>
                          <Link to="/PrivacyPolicy" className="ms-3">
                            {t("header.privacy_policy")}
                          </Link>
                        </li>
                      </ul>
                    </Col>
                    <div className="col-lg-6 mt-lg-0 mt-2">
                      <ul className="list-unstyled footer-menu mb-0">
                        <li>
                          <Link to="/terms-of-use" className="ms-3">
                            {t("footer.terms_of_use")}
                          </Link>
                        </li>
                      </ul>
                    </div>
                  </Row>
                  <div className="mt-5">
                    <p className="pt-3 mb-3 text-uppercase">
                      {t("footer.payments")}
                    </p>
                    <ul className="list-inline d-flex align-items-center flex-wrap gap-3 m-0">
                      <li>
                        <img src={generateImgPath("/assets/images/footer/01.webp")} alt="visa" />
                      </li>
                      <li>
                        <img src={generateImgPath("/assets/images/footer/02.webp")} alt="visa" />
                      </li>
                      <li>
                        <img src={generateImgPath("/assets/images/footer/03.webp")} alt="visa" />
                      </li>
                      <li>
                        <img src={generateImgPath("/assets/images/footer/04.webp")} alt="visa" />
                      </li>
                    </ul>
                  </div>
                </div>
              </Col>
            </Row>
          </Container>
        </div>
        <div className="footer-bottom bg-body py-3">
          <Container fluid>
            <Row className="align-items-center">
              <Col md="6" className="text-md-start text-center">
                <p className="m-0 font-size-14 text-capitalize">
                  © <span className="currentYear">{currentYear}</span>
                  <Link to="/"> STREAMIT </Link>{" "}
                  {t("footer.all_right_reserved")}.
                </p>
              </Col>
              <Col md="6" className="text-md-end text-center">
                <p className="m-0 font-size-14">
                  {t("footer.powered_by")}{" "}
                  <Link to="https://iqonic.design/" target="_blank">
                    IQONIC DESIGN
                  </Link>
                </p>
              </Col>
            </Row>
          </Container>
        </div>
      </footer>
    </Fragment>
  );
});

MerchandiseFooter.displayName = "MerchandiseFooter";
export default MerchandiseFooter;
