// start/6-workspace/choo/1-frontend/14-react-고급/3-redux/1-counter/app1/src/Counter.js
// 6. Presentational 컴포넌트 만들기
import React from "react"

export default function Counter({ count, onIncrease, onDecrease }) {
  return (
    <div>
      <h2>{count}</h2>
      <div>
        <button onClick={onIncrease}>+</button>
        <button onClick={onDecrease}>-</button>
      </div>
    </div>
  )
}

// start/8-workspace/saitou/5-vue/1-vue3/6-ref-reactive/app1/src/components/Counter.vue
<template>
  <div>
    <h1>Counter</h1>
    <p>Count: {{ count }}</p>
    <button @click="plus">+</button>
    <button @click="minus">-</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)

const plus = () => {
  count.value = count.value + 1
}
const minus = () => {
  count.value = count.value - 1
}
</script>

<style scoped>
</style>
