// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/components/sections/RecommendedForYou.jsx
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../../components/cards/CardStyle";
import { Fragment, memo, useState } from "react";
import { recommendedforYou } from "../../StaticData/data";
// the hook
import { useTranslation } from "react-i18next";

const RecommendedForYou = memo((props) => {
  const { t } = useTranslation();

  return (
    <Fragment>
      <SectionSlider
        title={t("ott_home.recommended_for_you")}
        list={recommendedforYou}
        className="recommended-block streamit-block"
        slidesPerView="6"
        // loop={true}
        paddingY={props.paddingY}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={t(data.title)}
            movieTime={data.movieTime}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

RecommendedForYou.displayName = "RecommendedForYou";
export default RecommendedForYou;

// ops/1-assets/1-templates/react/bootstrap-movies-prod/v5/vue/frontend/src/components/sections/RecommendedForYou.vue
<template>
  <!-- Recommended For You start -->
  <SectionSlider :title="$t(title)" :list="recommendedforYou" :slides-per-view="6" class="recommended-block streamit-block" margin-padding="px-md-3 px-1 my-4">
    <template #headerLink>
      <router-link to="/view-all" class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('ott_home.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :movie-time="data.movieTime" :watchlist-link="{ path: 'playlist' }" :link="{ path: '/movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Recommended For You end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { recommendedforYou } from '../../StaticData/data';

const title = ref('ott_home.recommended_for_you');
</script>
