// ops/1-assets/2-app-templates/all/movies-prod/v5/next-js/src/components/sections/TopPicsForYou.tsx
import { Fragment, memo, useState } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { topPics } from "../../StaticData/data";

const TopPicsForYou = memo(() => {
  const [title] = useState("Top Pics For You");
  const [topTen] = useState(topPics);

  return (
    <Fragment>
      <SectionSlider
        title={title}
        list={topTen}
        className="recommended-block streamit-block"
        slidesPerView={6}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={data.title}
            movieTime={data.movieTime}
            watchlistLink="/play-list"
            link="/movies/detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
})

TopPicsForYou.displayName = 'TopPicsForYou';
export default TopPicsForYou;

// ops/1-assets/1-templates/react/bootstrap-movies-prod/v5/vue/frontend/src/components/sections/TopPicsForYou.vue
<template>
  <!-- Top Pics For You start -->
  <SectionSlider :title="$t(title)" :list="topTen" :slides-per-view="6" class="top-pics-block streamit-block" margin-padding="px-md-3 px-1 my-4">
    <template #headerLink>
      <router-link to="/view-all" class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('ott_home.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" movie-time="data.movieTime" :watchlist-link="{ path: '/playlist' }" :link="{ path: '/movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Top Pics For You end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { topPics } from '../../StaticData/data';
const title = ref('ott_home.top_pics');
const topTen = ref(topPics);
</script>
