// ops/1-assets/1-app-templates/all/movies-prod/v5/nuxt-js/pages/blogs/index.vue
<template>
  <div class="section-padding">
    <div class="container">
      <b-row>
        <b-col lg="8" sm="12">
          <div v-for="data in blogs" :key="data">
            <card-blog-list
              :title="$t(data.title)"
              :slug="data.slug"
              :thumbnail="data.thumbnail"
              :tags="data.tags"
              :username="$t(data.username)"
              :description="$t(data.description)"
              :date="data.blogDate"
              :categories="$t(data.categories)"
            ></card-blog-list>
          </div>
        </b-col>
        <b-col lg="4" sm="12">
          <detail-meta-list></detail-meta-list>
        </b-col>
      </b-row>
    </div>
  </div>
</template>

<script setup>
//components
import CardBlogList from "../../components/cards/CardBlogList.vue";
import DetailMetaList from "~/components/blog/DetailMetaList.vue";

//static data
import { blogs } from "../../StaticData/blogs";

//custom hooks
import { useBreadcrumb } from "~/utilities/usePage";

useBreadcrumb("Blog Listing");
</script>

// ops/1-assets/1-app-templates/all/movies-prod/v5/next-js/src/pages/blogs/index.tsx
import React, { Fragment, memo } from "react";

//react bootstrap
import { Container, Row, Col } from "react-bootstrap";

//components
import CardBlogList from "../../components/cards/CardBlogList";
import DetailMetaList from "../../components/blog/DetailMetaList";

//static data
import { blogs } from "../../StaticData/blogs";

//custom hook
import { useBreadcrumb } from "@/utilities/usePage";

const BLogs = memo(() => {

    useBreadcrumb('Blog List')
    return (
        <Fragment>
            <div className="section-padding">
                <Container>
                    <Row>
                        <Col lg="8" sm="12">
                            {blogs.slice(0, 7).map((item, index) => {
                                return (
                                    <CardBlogList
                                        key={index}
                                        title={item.title}
                                        thumbnail={item.thumbnail}
                                        blogDate={item.blogDate}
                                        username={item.username}
                                        categories={item.categories}
                                        tags={item.tags}
                                        description={item.description}
                                    />
                                )
                            })}
                        </Col>
                        <Col lg="4" sm="12">
                            <DetailMetaList></DetailMetaList>
                        </Col>
                    </Row>
                </Container>
            </div>
        </Fragment>
    );
});

BLogs.displayName = "BLogs";
export default BLogs;
