// ops/1-assets/1-app-templates/react/movies-prod/v5/next-js/src/components/cards/CastCard.tsx
import React, { Fragment, memo } from "react";

//react-router-dom
import Link from "next/link";

interface Props {
  image: string,
  title: string,
  category: string
}

const CastCard = memo((props: Props) => {
  return (
    <Fragment>
      <div className="iq-cast">
        <img src={props.image} alt={`cast-${props.title}`} loading="lazy" />
        <div className="card-img-overlay iq-cast-body">
          <h6 className="cast-title fw-500">
            <Link href="/cast/detail">{props.title}</Link>
          </h6>
          <span className="cast-subtitle">{props.category}</span>
        </div>
      </div>
    </Fragment>
  );
});

CastCard.displayName = "CastCard";
export default CastCard;

// ops/1-assets/1-app-templates/all/movies-prod/v5/vue/frontend/src/components/cards/CastCard.vue
<template>
  <img :src="image" :alt="`cast-${title}`" loading="lazy" class="img-fluid object-cover mb-4 rounded" />
  <div className="text-center">
    <h6 className="mb-0">
      <router-link :to="{ name: 'landing-page.cast-detail' }" class="font-size-14 text-decoration-none cast-title text-capitalize">{{ title }}</router-link>
    </h6>
    <router-link to="#" class="font-size-14 text-decoration-none text-capitalize text-body">{{ designation }}</router-link>
  </div>
</template>

<script setup>
defineProps({
  title: { type: String, default: '' },
  image: { type: String, default: '' },
  designation: { type: String, default: '' },
});
</script>
