// start/8-workspace/saitou/4-react/4-custom-hooks/3-utils/1-useDateUtil/app1/src/pages/Home/index.js
import React from "react"
import Label from "../../components/Atoms/Label"
import useDateUtil from "../../utils/useDateUtil"

export default function Home() {
  const dateUtil = useDateUtil()
  const formattedDate = dateUtil.formatDate(
    dateUtil.currentDate,
    "YYYY-MM-DD HH:mm"
  )

  return (
    <div>
      <Label text="Home" />
      <h2>現在の時刻：{formattedDate}</h2>
    </div>
  )
}

// frontend/6-vue/1-vue3/1-vue-syntax/3-vue-syntax(중급)/4-globalStates(stores)/1-vuex/1-useCounterStore/app1/src/views/Home.vue
<template>
  <div>
    <h1>Home</h1>
    <p>현재 날짜: {{ formattedDate }}</p>
    <p>현재 카운트: {{ counterStore.count }}</p>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue"
import { useDateUtil } from "@/utils/useDateUtil"
import { useCounterStore } from "@/stores/counter/useCounterStore"

// Variables
const formattedDate = ref("")

// Hooks
const dateUtil = useDateUtil()
const counterStore = useCounterStore()

// Lifecycle Hooks
onMounted(() => {
  formattedDate.value = dateUtil.formatDate(dateUtil.currentDate.value)
})
</script>
