// frontend/7-library/vue/5-vue3-syntax(중급-crud)/7-todo-app-props/app1/src/components/TodoList.vue
<template>
    <div>
        <Todo
            v-for="todo in todos"
            :key="todo.id"
            :todo="todo"
        />
    </div>
</template>

<script>
import Todo from '@/components/Todo.vue'
export default {
    components: {
        Todo
    },
    computed: {
        todos() {
            return this.$store.state.todos
        }
    },
}
</script>

<style>
</style>

// frontend/5-react/1-react/6-tdd/1-react-unit-jest/6-tdd-todoapp-todoList/app1/src/TodoList.js
import React from 'react'
import TodoItem from './TodoItem'

export default function TodoList ({ todos, onToggle, onRemove }) {
  return (
    <ul>
      {todos.map(todo => (
        <TodoItem
          todo={todo}
          key={todo.id}
          onToggle={onToggle}
          onRemove={onRemove}
        />
      ))}
    </ul>
  )
}
