// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/components/merchandise/cart-total.jsx
import React, { Fragment, memo } from "react";

// the hook
import { useTranslation } from "react-i18next";

const CartTotal = memo((props) => {
  const { t } = useTranslation();
  return (
    <Fragment>
      <tbody>
        <tr className="cart-subtotal">
          <th>{t("shop.subtotal")}</th>
          <td data-title="Subtotal">
            <span className="">
              <bdi>
                <span className=""></span>
                {props.final_price}
              </bdi>
            </span>
          </td>
        </tr>
        <tr className="order-total">
          <th>{t("shop.total_")}</th>
          {/* <!-- <td data-title="Total"><strong><span className="amount"><bdi className="final text-primary"><span className="">$</span>{ data.final_price }</bdi></span></strong></td> --> */}
          <td data-title="Total">
            <strong>
              <span className="amount">
                <bdi className="final text-primary">
                  <span className=""></span> {props.final_price}{" "}
                </bdi>
              </span>
            </strong>
          </td>
        </tr>
      </tbody>
    </Fragment>
  );
});

CartTotal.displayName = "CartTotal";
export default CartTotal;

// ops/1-assets/1-app-templates/react/movies-prod/v5/vue/frontend/src/components/merchandise/cart/CartTotal.vue
<template>
  <tbody>
    <tr class="cart-subtotal">
      <th class="border-0"><span class="fw-500">{{ $t("shop.subtotal") }}</span></th>
      <td class="border-0">
        <span>{{ props.finalPrice }}</span>
      </td>
    </tr>
    <tr class="order-total">
      <th class="border-0">
        <span class="fw-500"> Total </span>
      </th>
      <td class="border-0">
        <span class="fw-500 text-primary">{{ props.finalPrice }}</span>
      </td>
    </tr>
  </tbody>
</template>
<script setup>
const props = defineProps({
  finalPrice: { type: String, default: '' },
});
</script>
