// ops/1-assets/1-app-templates/react/movies-prod/v5/react/dashboard/src/components/setting/sections/menu-active-style.jsx
import {memo,Fragment}from 'react'
import RadioBtn from '../elements/radio-btn'

const MenuActiveStyle = memo((props) => {
    return (
        <Fragment>
            <h5 className="mt-4 mb-3">Active Menu Style</h5>
            <div className="d-grid gap-3 grid-cols-2">
                <RadioBtn btnName="sidebar_menu_style" imgComponent={true}  label="Rounded One Side" className="text-center" inputclassName="btn-check" labelclassName="btn btn-border btn-setting-panel d-block overflow-hidden" id="navs-rounded" defaultChecked={props.sidebarMenuStyle} value="sidebar-default navs-rounded" >
                    Rounded One
                </RadioBtn>
                <RadioBtn btnName="sidebar_menu_style" imgComponent={true} label="Rounded All" className="text-center" inputclassName="btn-check" labelclassName="btn btn-border btn-setting-panel d-block overflow-hidden" id="navs-rounded-all" defaultChecked={props.sidebarMenuStyle} value="sidebar-default navs-rounded-all" >
                    Rounded All
                </RadioBtn>
                <RadioBtn btnName="sidebar_menu_style" imgComponent={true} label="Pill One Side" className="text-center" inputclassName="btn-check" labelclassName="btn btn-border btn-setting-panel d-block overflow-hidden" id="navs-pill" defaultChecked={props.sidebarMenuStyle} value="sidebar-default navs-pill" >
                    Pill One Side
                </RadioBtn>
                <RadioBtn btnName="sidebar_menu_style" imgComponent={true} label="Pill All" className="text-center" inputclassName="btn-check" labelclassName="btn btn-border btn-setting-panel d-block overflow-hidden" id="navs-pill-all" defaultChecked={props.sidebarMenuStyle} value="sidebar-default navs-pill-all" >
                    Pill All
                </RadioBtn>
            </div>
        </Fragment>
    )
}
)

MenuActiveStyle.displayName="MenuActiveStyle"
export default MenuActiveStyle

// ops/1-assets/1-app-templates/react/movies-prod/v5/vue/dashboard/src/components/setting/sections/MenuActiveStyle.vue
<template>
  <div class="mb-4">
    <h5 class="mt-4 mb-3">Active Menu Style</h5>
    <div class="d-grid gap-3 grid-cols-2">
      <radio-input
id="navs-rounded" btn-name="sidebar_menu_style" :img-component="true" class-name="text-center"
        input-class="btn-check" label-class="btn btn-border btn-setting-panel d-block overflow-hidden"
        label-title="Rounded One Side" :default-checked="sidebarMenuStyle" value="sidebar-default navs-rounded"
        @on-change="store.sidebar_menu_style"> Rounded One </radio-input>
      <radio-input
id="navs-rounded-all" btn-name="sidebar_menu_style" :img-component="true" label-title="Rounded All"
        class-name="text-center" input-class="btn-check"
        label-class="btn btn-border btn-setting-panel d-block overflow-hidden" :default-checked="sidebarMenuStyle"
        value="sidebar-default navs-rounded-all" @on-change="store.sidebar_menu_style"> Rounded All </radio-input>
      <radio-input
id="navs-pill" btn-name="sidebar_menu_style" :img-component="true" label-title="Pill One Side"
        class-name="text-center" input-class="btn-check"
        label-class="btn btn-border btn-setting-panel d-block overflow-hidden" :default-checked="sidebarMenuStyle"
        value="sidebar-default navs-pill" @on-change="store.sidebar_menu_style"> Pill One Side </radio-input>
      <radio-input
id="navs-pill-all" btn-name="sidebar_menu_style" :img-component="true" label-title="Pill All"
        class-name="text-center" input-class="btn-check"
        label-class="btn btn-border btn-setting-panel d-block overflow-hidden" :default-checked="sidebarMenuStyle"
        value="sidebar-default navs-pill-all" @on-change="store.sidebar_menu_style"> Pill All </radio-input>
    </div>
  </div>
</template>
<script>
import { computed } from 'vue';

//pinia store
import { useSetting } from '@/store/pinia';

import RadioInput from '../../custom/elements/RadioInput.vue';
export default {
  name: 'MenuActiveStyle',
  components: {
    RadioInput,
  },
  setup() {
    const store = useSetting();
    const sidebarMenuStyle = computed(() => store.sidebar_menu_style_value)

    return {
      sidebarMenuStyle,
      store
    };
  },
};
</script>
