// ops/1-assets/1-templates/vue/movies-prod/v5/nuxt-js/pages/extra/error-page-one.vue
<template>
  <div class="section-padding vh-100">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
          <img
            src="/assets/images/pages/404.webp"
            class=""
            alt="404"
            loading="lazy"
          />
          <div
            class="py-3 text-center mt-5 mb-4"
            style="
              background: url('/assets/images/pages/404-bg-patten.webp');
              background-repeat: no-repeat;
              background-position: center center;
              background-size: 68% auto;
            "
          >
            <h4 class="fw-semibold mb-0">
              {{ $t("error.something_wrong") }}
            </h4>
          </div>
          <p class="text-center">{{ $t("error.looking_for") }}</p>
          <div class="text-center mt-4 pt-3">
            <div class="iq-bu tton">
              <nuxt-link
                :to="{ name: 'home' }"
                class="btn text-uppercase position-relative"
              >
                <span class="button-text">{{ $t("error.back_home") }}</span>
                <i class="fa-solid fa-play"></i>
              </nuxt-link>
            </div>
          </div>
        </div>
        <div class="col-lg-2"></div>
      </div>
    </div>
  </div>
</template>

<script>
//layout
definePageMeta({
  layout: "blank",
});
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/next-js/src/pages/extra/error-page-one.tsx
import React, { Fragment} from "react";

//react bootstrap
import { Col, Container, Row } from "react-bootstrap";

// next link
import Link from "next/link";

//function
import { generateImgPath } from "../../StaticData/data";

const ErrorPage1 = () => {
  return (
    <Fragment>
      <div className="section-padding vh-100">
        <Container className="">
          <Row className="h-100 align-items-center">
            <Col lg="2"></Col>
            <Col lg="8">
              <img
                src="/assets/images/pages/404.webp"
                alt="404"
                loading="lazy"
              />
              <div
                className="py-3 text-center mt-5 mb-4"
                style={{
                  background: `url(${generateImgPath(
                    "/assets/images/pages/404-bg-patten.webp"
                  )})`,
                  backgroundRepeat: "no-repeat",
                  backgroundPosition: "center center",
                  backgroundSize: "68% auto",
                }}
              >
                <h4 className="fw-semibold mb-0">Oops! something went wrong</h4>
              </div>
              <p className="text-center">
                We’re sorry, it looks like the page you’re looking for isn’t in
                our system
              </p>
              <div className="text-center mt-4 pt-3">
                <div className="iq-button">
                  <Link href="/" className="btn text-uppercase position-relative">
                    <span className="button-text">Back to home</span>
                    <i className="fa-solid fa-play"></i>
                  </Link>
                </div>
              </div>
            </Col>
            <Col lg="2"></Col>
          </Row>
        </Container>
      </div>
    </Fragment>
  );
};

ErrorPage1.layout = "Blank";
export default ErrorPage1;
