// ops/1-assets/1-app-templates/react/movies-prod/v5/vue/dashboard/src/views/auth/default/SignUp.vue
<template>
  <section class="sign-in-page" :style="{ 'background-image': 'url(' + generateImgPath('/assets/images/login/login.webp') + ')' }">
    <b-container>
      <b-row class="justify-content-center align-items-center height-self-center">
        <div class="align-self-center col-md-12 col-lg-7 form-padding">
          <div class="sign-user_card">
            <div class="sign-in-page-data">
              <div class="sign-in-from w-100 m-auto">
                <form action="/" class="">
                  <div class="row">
                    <div class="col-md-6">
                      <div class="mb-3">
                        <label class="form-label">{{ $t('authentication.username') }}</label
                        ><input id="exampleInputEmail2" :placeholder="$t('authentication.enter_full_name')" autocomplete="off" required="" type="text" class="mb-0 form-control" />
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="mb-3">
                        <label class="form-label">{{ $t('authentication.e_mail') }}</label
                        ><input id="exampleInputEmail3" :placeholder="$t('authentication.enter_email')" autocomplete="off" required="" type="email" class="mb-0 form-control" />
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="mb-3">
                        <label class="form-label">{{ $t('authentication.first_name') }}</label
                        ><input id="exampleInputEmail4" :placeholder="$t('authentication.first_name')" autocomplete="off" required="" type="text" class="mb-0 form-control" />
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="mb-3">
                        <label class="form-label">{{ $t('authentication.last_name') }}</label
                        ><input id="exampleInputEmail5" :placeholder="$t('authentication.last_name')" autocomplete="off" required="" type="email" class="mb-0 form-control" />
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="mb-3">
                        <label class="form-label">{{ $t('authentication.password') }}</label
                        ><input id="exampleInputPassword6" :placeholder="$t('authentication.password')" required="" type="password" class="mb-0 form-control" />
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="mb-3">
                        <label class="form-label">{{ $t('authentication.repeat_password') }}</label
                        ><input id="exampleInputPassword7" :placeholder="$t('authentication.password')" required="" type="password" class="mb-0 form-control" />
                      </div>
                    </div>
                  </div>
                  <div class="form-check my-2">
                    <input id="customRadio1" type="radio" name="customRadio" class="form-check-input" /><label class="form-check-label" for="customRadio1">{{ $t('authentication.premium') }}</label>
                  </div>
                  <div class="form-check">
                    <input id="customRadio2" type="radio" name="customRadio" class="form-check-input" /><label class="form-check-label" for="customRadio2">{{ $t('authentication.basic') }}</label>
                  </div>
                  <div class="form-check">
                    <input id="customRadio3" type="radio" name="customRadio" class="form-check-input" /><label class="form-check-label" for="customRadio3">{{ $t('authentication.free-free') }}</label>
                  </div>
                  <button type="button" class="btn btn-btn btn-primary my-2">{{ $t('authentication.sign_up') }}</button>
                </form>
              </div>
            </div>
            <div class="mt-3">
              <div class="d-flex justify-content-center links">
                {{ $t('authentication.already_have_an_account') }} <router-link to="/auth/login" class="text-primary ms-2">{{ $t('authentication.sign_in') }}</router-link>
              </div>
            </div>
          </div>
        </div>
      </b-row>
      <!-- Sign in END -->
    </b-container>
  </section>
</template>
<script setup>
const generateImgPath = (path) => {
  return window.origin + import.meta.env.BASE_URL + path;
};
</script>

<style lang="scss" scoped></style>

// ops/1-assets/1-app-templates/vue/movies-prod/v5/react/dashboard/src/views/dashboard/auth/signup.jsx
import React, { memo, Fragment } from "react";

// react-bootstrap
import { Container, Col, Row, Form, Button } from "react-bootstrap";

// react-router
import { Link, useNavigate } from "react-router-dom";

// the hook
import { useTranslation } from "react-i18next";

const SignUp = memo(() => {
  const { t } = useTranslation();
  let history = useNavigate();

  return (
    <Fragment>
      <section className="sign-in-page">
        <Container>
          <Row className="justify-content-center align-items-center height-self-center">
            <Col lg="7" md="12" className="align-self-center">
              <div className="sign-user_card ">
                <div className="sign-in-page-data">
                  <div className="sign-in-from w-100 m-auto">
                    <Form className="" action="/">
                      <Row>
                        <Col md="6">
                          <Form.Group className="mb-3">
                            <Form.Label>
                              {t("authentication.username")}
                            </Form.Label>
                            <Form.Control
                              type="text"
                              className="mb-0"
                              id="exampleInputEmail2"
                              placeholder={t("authentication.enter_full_name")}
                              autoComplete="off"
                              required
                            />
                          </Form.Group>
                        </Col>
                        <Col md="6">
                          <Form.Group className="mb-3">
                            <Form.Label>
                              {t("authentication.e_mail")}
                            </Form.Label>
                            <Form.Control
                              type="email"
                              className="mb-0"
                              id="exampleInputEmail3"
                              placeholder={t("authentication.enter_email")}
                              autoComplete="off"
                              required
                            />
                          </Form.Group>
                        </Col>
                        <Col md="6">
                          <Form.Group className="mb-3">
                            <Form.Label>
                              {t("authentication.first_name")}
                            </Form.Label>
                            <Form.Control
                              type="text"
                              className="mb-0"
                              id="exampleInputEmail4"
                              placeholder={t("authentication.first_name")}
                              autoComplete="off"
                              required
                            />
                          </Form.Group>
                        </Col>
                        <Col md="6">
                          <Form.Group className="mb-3">
                            <Form.Label>
                              {t("authentication.last_name")}
                            </Form.Label>
                            <Form.Control
                              type="email"
                              className="mb-0"
                              id="exampleInputEmail5"
                              placeholder={t("authentication.last_name")}
                              autoComplete="off"
                              required
                            />
                          </Form.Group>
                        </Col>
                        <Col md="6">
                          <Form.Group className="mb-3">
                            <Form.Label>
                              {t("authentication.password")}
                            </Form.Label>
                            <Form.Control
                              type="password"
                              className="mb-0"
                              id="exampleInputPassword6"
                              placeholder={t("authentication.password")}
                              required
                            />
                          </Form.Group>
                        </Col>
                        <Col md="6">
                          <Form.Group className="mb-3">
                            <Form.Label>
                              {t("authentication.repeat_password")}
                            </Form.Label>
                            <Form.Control
                              type="password"
                              className="mb-0"
                              id="exampleInputPassword7"
                              placeholder={t("authentication.password")}
                              required
                            />
                          </Form.Group>
                        </Col>
                      </Row>
                      <div className="form-check my-2">
                        <input
                          type="radio"
                          id="customRadio1"
                          name="customRadio"
                          className="form-check-input"
                        />
                        <label
                          className="form-check-label"
                          htmlFor="customRadio1"
                        >
                          {t("authentication.premium")}
                        </label>
                      </div>
                      <div className="form-check">
                        <input
                          type="radio"
                          id="customRadio2"
                          name="customRadio"
                          className="form-check-input"
                        />
                        <label
                          className="form-check-label"
                          htmlFor="customRadio2"
                        >
                          {" "}
                          {t("authentication.basic")}
                        </label>
                      </div>
                      <div className="form-check">
                        <input
                          type="radio"
                          id="customRadio3"
                          name="customRadio"
                          className="form-check-input"
                        />
                        <label
                          className="form-check-label"
                          htmlFor="customRadio3"
                        >
                          {t("authentication.free-free")}
                        </label>
                      </div>
                      <Button
                        type="button"
                        onClick={() => history.push("/")}
                        variant="btn btn-primary my-2"
                      >
                        {t("authentication.sign_up")}
                      </Button>
                    </Form>
                  </div>
                </div>
                <div className="mt-3">
                  <div className="d-flex justify-content-center links">
                    {t("authentication.already_have_an_account")}{" "}
                    <Link to="/auth/sign-in" className="text-primary ms-2">
                      {t("authentication.sign_in")}
                    </Link>{" "}
                  </div>
                </div>
              </div>
            </Col>
          </Row>
        </Container>
      </section>
    </Fragment>
  );
});

SignUp.displayName = "SignUp";
export default SignUp;
