// ops/1-assets/1-templates/vue/movies-prod/v5/vue/frontend/src/components/blog/sidebar/TagsWidget.vue
<template>
  <div id="tag_cloud-2" class="widget">
    <h5 class="widget-title position-relative">{{ $t('form.tags') }}</h5>

    <ul class="p-0 m-0 list-unstyled gap-2 widget_tags">
      <li v-for="tag in props.tags" :key="tag">
        <router-link to="/blogs-tag" class="position-relative"> {{ $t(tag.name) }} </router-link>
      </li>
    </ul>
  </div>
</template>
<script setup>
const props = defineProps({
  tags: { type: Array, default: () => [] },
});
</script>

// ops/1-assets/1-templates/react/bootstrap-movies-prod/v5/next-js/src/components/blog/sidebar/TagsWidget.tsx
import React, { Fragment, memo } from 'react'

//react-router-dom
import Link from "next/link";

//static data
import { blogTags } from '../../../StaticData/blogs'

const TagsWidget = memo(() => {
  return (
    <Fragment>
      <div id="tag_cloud-2" className="widget">
        <h5 className="widget-title position-relative">Tags</h5>
        <div className="tagcloud">
          <ul className="p-0 m-0 list-unstyled gap-2 widget_tags">
            {blogTags.map((tags, index) => {
              return (
                <li key={index}>
                  <Link href="/blogs/filter/tags" className="position-relative">{tags.name}</Link>
                </li>
              )
            })}
          </ul>
        </div>
      </div>
    </Fragment>
  )
})

TagsWidget.displayName = "TagsWidget"
export default TagsWidget
