// ops/1-assets/2-app-templates/all/movies-prod/v5/nuxt-js/pages/genres/all-genre.vue
<template>
  <div class="section-padding">
    <b-container fluid>
      <div class="row">
        <div class="col-sm-12 my-4">
          <div class="d-flex align-items-center justify-content-between">
            <h5 class="main-title text-capitalize mb-0">geners</h5>
          </div>
        </div>
      </div>
      <div
        class="row row-cols-xl-5 row-cols-md-2 row-cols-1 geners-card geners-style-grid"
      >
        <div class="col slide-items">
          <div class="iq-card-geners card-hover-style-two">
            <div class="block-images position-relative w-100">
              <div class="img-box rounded position-relative">
                <img
                  src="/assets/images/genre/01.webp"
                  alt="geners-img"
                  class="img-fluid object-cover w-100 rounded"
                />
                <div class="blog-description">
                  <h6 class="mb-0 iq-title">
                    <a
                      href=""
                      class="text-decoration-none text-capitalize line-count-2 p-2"
                      >action</a
                    >
                  </h6>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col slide-items">
          <div class="iq-card-geners card-hover-style-two">
            <div class="block-images position-relative w-100">
              <div class="img-box rounded position-relative">
                <img
                  src="/assets/images/genre/02.webp"
                  alt="geners-img"
                  class="img-fluid object-cover w-100 rounded"
                />
                <div class="blog-description">
                  <h6 class="mb-0 iq-title">
                    <a
                      href=""
                      class="text-decoration-none text-capitalize line-count-2 p-2"
                      >action</a
                    >
                  </h6>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col slide-items">
          <div class="iq-card-geners card-hover-style-two">
            <div class="block-images position-relative w-100">
              <div class="img-box rounded position-relative">
                <img
                  src="/assets/images/genre/03.webp"
                  alt="geners-img"
                  class="img-fluid object-cover w-100 rounded"
                />
                <div class="blog-description">
                  <h6 class="mb-0 iq-title">
                    <a
                      href=""
                      class="text-decoration-none text-capitalize line-count-2 p-2"
                      >action</a
                    >
                  </h6>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col slide-items">
          <div class="iq-card-geners card-hover-style-two">
            <div class="block-images position-relative w-100">
              <div class="img-box rounded position-relative">
                <img
                  src="/assets/images/genre/04.webp"
                  alt="geners-img"
                  class="img-fluid object-cover w-100 rounded"
                />
                <div class="blog-description">
                  <h6 class="mb-0 iq-title">
                    <a
                      href=""
                      class="text-decoration-none text-capitalize line-count-2 p-2"
                      >action</a
                    >
                  </h6>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col slide-items">
          <div class="iq-card-geners card-hover-style-two">
            <div class="block-images position-relative w-100">
              <div class="img-box rounded position-relative">
                <img
                  src="/assets/images/genre/05.webp"
                  alt="geners-img"
                  class="img-fluid object-cover w-100 rounded"
                />
                <div class="blog-description">
                  <h6 class="mb-0 iq-title">
                    <a
                      href=""
                      class="text-decoration-none text-capitalize line-count-2 p-2"
                      >action</a
                    >
                  </h6>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col slide-items">
          <div class="iq-card-geners card-hover-style-two">
            <div class="block-images position-relative w-100">
              <div class="img-box rounded position-relative">
                <img
                  src="/assets/images/genre/06.webp"
                  alt="geners-img"
                  class="img-fluid object-cover w-100 rounded"
                />
                <div class="blog-description">
                  <h6 class="mb-0 iq-title">
                    <a
                      href=""
                      class="text-decoration-none text-capitalize line-count-2 p-2"
                      >action</a
                    >
                  </h6>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col slide-items">
          <div class="iq-card-geners card-hover-style-two">
            <div class="block-images position-relative w-100">
              <div class="img-box rounded position-relative">
                <img
                  src="/assets/images/genre/07.webp"
                  alt="geners-img"
                  class="img-fluid object-cover w-100 rounded"
                />
                <div class="blog-description">
                  <h6 class="mb-0 iq-title">
                    <a
                      href=""
                      class="text-decoration-none text-capitalize line-count-2 p-2"
                      >action</a
                    >
                  </h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </b-container>
  </div>
</template>
<script setup>
import { useBreadcrumb } from "~/utilities/usePage";

useBreadcrumb("View All");
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/next-js/src/pages/genres/all-genre.tsx
import React, { Fragment, memo } from 'react'

//router
import Link from 'next/link'

//react-bootstrap
import { Col, Container, Row } from 'react-bootstrap'

// data
import { geners } from "@/StaticData/data"

//components
import GenersCard from '@/components/cards/GanresCard'

//custom hooks
import { useBreadcrumb } from '@/utilities/usePage'

const AllGenres = memo(() => {
  useBreadcrumb('View All')
  return (
    <Fragment>
      <section className="section-padding">
        <Container fluid>
          <Row>
            <Col sm="12" className='my-4'>
              <div className="d-flex align-items-center justify-content-between">
                <h5 className="main-title text-capitalize mb-0">Geners</h5>
              </div>
            </Col>
          </Row>
          <Row xl="5" md="2" className="row-cols-1 geners-card geners-style-grid">
            {geners.map((item, index) => (
              <Col key={index} className="slide-items">
                <GenersCard
                  slug={item.slug}
                  title={item.title}
                  image={item.thumbnail}
                  type={item.type}
                />
              </Col>
            ))}
          </Row>
        </Container>
      </section>
    </Fragment>
  )
})

AllGenres.displayName = 'AllGenres'
export default AllGenres
