// ops/1-assets/1-templates/react/bootstrap-movies-prod/v5/nuxt-js/pages/home.vue
<template>
  <HomeHeroSlider></HomeHeroSlider>

  <ContinueWatching slides-per-view="4"></ContinueWatching>

  <UpcomingMovies></UpcomingMovies>

  <LatestMovies :slider-data="latestMovie"></LatestMovies>

  <VerticalSectionSlider
    :slider-data="verticleLatestMovies"
  ></VerticalSectionSlider>

  <SuggestedBlock></SuggestedBlock>

  <ParallexSection></ParallexSection>

  <TrendingSlider></TrendingSlider>

  <RecommendedTVShow></RecommendedTVShow>
</template>

<script setup>
// Hero Slider
import HomeHeroSlider from "../../components/slider/HomeHeroSlider.vue";

// Sections
import TrendingSlider from "../../components/sections/TrendingSection.vue";
import ContinueWatching from "../../components/sections/ContinueWatching.vue";
import UpcomingMovies from "../../components/sections/UpcomingMovies.vue";
import LatestMovies from "../../components/sections/LatestMovies.vue";
import SuggestedBlock from "../../components/sections/SuggestedBlock.vue";
import RecommendedTVShow from "../../components/sections/RecommendedTVShow.vue";
import ParallexSection from "../../components/sections/ParallexSection.vue";
import VerticalSectionSlider from "../../components/slider/VerticalSectionSlider.vue";

import { verticleLatestMovies, latestMovie } from "../../StaticData/data";
import { useEnterExit } from "~/utilities/usePage";

import { onMounted } from "vue";
import { useStremit } from "~/store/streamit";

const store = useStremit();

onMounted(() => {
  store.breadcrumbSet({ show: false, name: "" });
});

useEnterExit();
</script>

// ops/1-assets/1-app-templates/all/movies-prod/v5/next-js/src/pages/home.tsx
import { memo } from "react";

// hero slider
import HomeHeroSlider from "@/components/slider/HomeHeroSlider";

// sections
import ContinueWatching from "@/components/sections/ContinueWatching";
import UpcomingMovies from "@/components/sections/UpcomingMovies";
import LatestMovies from "@/components/sections/LatestMovies";
import VerticalSectionSlider from "@/components/slider/VerticalSectionSlider";
import TrendingSlider from "@/components/sections/Trending";
import SuggestedBlock from "@/components/sections/SuggestedBlock";
import RecommendedTVShow from "@/components/sections/RecommendedTVShow";
import ParallexSection from "@/components/sections/ParallexSection";

//static data
import { verticleLatestMovies } from "@/StaticData/data";

import { useEnterExit } from "@/utilities/usePage";

const Home = memo(() => {
  useEnterExit()
  return (
    <>

      <HomeHeroSlider />
      <ContinueWatching />
      <UpcomingMovies />
      <LatestMovies />
      <VerticalSectionSlider sliderData={verticleLatestMovies} />
      <SuggestedBlock />
      <ParallexSection />
      <TrendingSlider />
      <RecommendedTVShow />

    </>
  );
});

Home.displayName = "Home";
export default Home;
