// ops/1-assets/1-app-templates/react/movies-prod/v4/code-nuxt/pages/backend/core/UiBadges.vue
<template>
  <b-container fluid>
    <b-row>
      <b-col lg="6" sm="12">
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">
              Badges
            </h4>
          </template>
          <template v-slot:headerAction>
            <a v-b-toggle.collapse-1 class="text-primary float-right" role="button">
              <i class="ri-code-s-slash-line" />
            </a>
          </template>
          <template v-slot:body>
            <p>Badges scale to match the size of the immediate parent element by using relative font sizing and <code>em</code> units.</p>
            <b-collapse id="collapse-1" class="mb-2">
              <div class="card">
                <kbd class="bg-dark">
                  <pre id="badges" class="text-white">
                    <code>
&lt;h1 class="mb-3"&gt;Example heading &lt;b-badge variant="primary"&gt;New&lt;/b-badge&gt;&lt;/h1&gt;
&lt;h2 class="mb-3"&gt;Example heading &lt;b-badge variant="secondary"&gt;New&lt;/b-badge&gt;&lt;/h2&gt;
&lt;h3 class="mb-3"&gt;Example heading &lt;b-button variant="success"&gt;
  Notifications &lt;b-badge variant="light" class="ml-2"&gt;4&lt;/b-badge&gt;
&lt;/b-button&gt;&lt;/h3&gt;
&lt;h4 class="mb-3"&gt;Example heading &lt;b-badge variant="danger"&gt;New&lt;/b-badge&gt;&lt;/h4&gt;
&lt;h5 class="mb-3"&gt;Example heading &lt;b-badge variant="warning"&gt;New&lt;/b-badge&gt;&lt;/h5&gt;
&lt;h6 class="mb-0"&gt;Example heading &lt;b-badge variant="info"&gt;New&lt;/b-badge&gt;&lt;/h6&gt;
</code></pre>
                </kbd>
              </div>
            </b-collapse>
            <h1 class="mb-3">
              Example heading <b-badge variant="primary">
                New
              </b-badge>
            </h1>
            <h2 class="mb-3">
              Example heading <b-badge variant="secondary">
                New
              </b-badge>
            </h2>
            <h3 class="mb-3">
              Example heading <b-button variant="success">
                Notifications <b-badge variant="light" class="ml-2">
                  4
                </b-badge>
              </b-button>
            </h3>
            <h4 class="mb-3">
              Example heading <b-badge variant="danger">
                New
              </b-badge>
            </h4>
            <h5 class="mb-3">
              Example heading <b-badge variant="warning">
                New
              </b-badge>
            </h5>
            <h6 class="mb-0">
              Example heading <b-badge variant="info">
                New
              </b-badge>
            </h6>
          </template>
        </iq-card>
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">
              Button Badges
            </h4>
          </template>
          <template v-slot:headerAction>
            <a v-b-toggle.collapse-2 class="text-primary float-right" role="button">
              <i class="ri-code-s-slash-line" />
            </a>
          </template>
          <template v-slot:body>
            <p>Badges can be used as part of buttons to provide a counter.</p>
            <b-collapse id="collapse-2" class="mb-2">
              <div class="card">
                <kbd class="bg-dark">
                  <pre id="button-badges" class="text-white">
                    <code>
&lt;b-button variant="primary" class="mb-1"&gt;
  Notifications &lt;b-badge variant="light" class="ml-2"&gt;4&lt;/b-badge&gt;
&lt;/b-button&gt;
&lt;b-button variant="success" class="mb-1"&gt;
  Notifications&lt;b-badge variant="light" class="ml-2"&gt;4&lt;/b-badge&gt;
&lt;/b-button&gt;
&lt;b-button variant="danger" class="mb-1"&gt;
  Notifications&lt;b-badge variant="light" class="ml-2"&gt;4&lt;/b-badge&gt;
&lt;/b-button&gt;
</code></pre>
                </kbd>
              </div>
            </b-collapse>
            <b-button variant="primary" class="mb-1 mr-1">
              Notifications <b-badge variant="light" class="ml-2">
                4
              </b-badge>
            </b-button>
            <b-button variant="success" class="mb-1 mr-1">
              Notifications<b-badge variant="light" class="ml-2">
                4
              </b-badge>
            </b-button>
            <b-button variant="danger" class="mb-1 mr-1">
              Notifications<b-badge variant="light" class="ml-2">
                4
              </b-badge>
            </b-button>
          </template>
        </iq-card>
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">
              Button Light background Badges
            </h4>
          </template>
          <template v-slot:headerAction>
            <a v-b-toggle.collapse-3 class="text-primary float-right" role="button">
              <i class="ri-code-s-slash-line" />
            </a>
          </template>
          <template v-slot:body>
            <p>Badges can be used as part of buttons to provide a counter.</p>
            <b-collapse id="collapse-3" class="mb-2">
              <div class="card">
                <kbd class="bg-dark">
                  <pre id="button-light-background-badges" class="text-white">
                    <code>
&lt;b-button variant="outline-primary" class="mb-1"&gt;
  Notifications &lt;b-badge variant="primary" class="ml-2"&gt;4&lt;/b-badge&gt;
&lt;/b-button&gt;
&lt;b-button variant="outline-success" class="mb-1"&gt;
  Notifications&lt;b-badge variant="success" class="ml-2"&gt;4&lt;/b-badge&gt;
&lt;/b-button&gt;
&lt;b-button variant="outline-danger" class="mb-1"&gt;
  Notifications&lt;b-badge variant="danger" class="ml-2"&gt;4&lt;/b-badge&gt;
&lt;/b-button&gt;
</code></pre>
                </kbd>
              </div>
            </b-collapse>
            <b-button variant="outline-primary" class="mb-1 mr-1">
              Notifications <b-badge variant="primary" class="ml-2">
                4
              </b-badge>
            </b-button>
            <b-button variant="outline-success" class="mb-1 mr-1">
              Notifications<b-badge variant="success" class="ml-2">
                4
              </b-badge>
            </b-button>
            <b-button variant="outline-danger" class="mb-1 mr-1">
              Notifications<b-badge variant="danger" class="ml-2">
                4
              </b-badge>
            </b-button>
          </template>
        </iq-card>
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">
              Button Border Badges
            </h4>
          </template>
          <template v-slot:headerAction>
            <a v-b-toggle.collapse-4 class="text-primary float-right" role="button">
              <i class="ri-code-s-slash-line" />
            </a>
          </template>
          <template v-slot:body>
            <p>Badges can be used as part of buttons to provide a counter.</p>
            <b-collapse id="collapse-4" class="mb-2">
              <div class="card">
                <kbd class="bg-dark">
                  <pre id="button-border-badges" class="text-white">
                    <code>
&lt;b-button variant="none" class="iq-bg-primary mb-1"&gt;
  Notifications &lt;b-badge variant="primary" class="ml-2"&gt;4&lt;/b-badge&gt;
&lt;/b-button&gt;
&lt;b-button variant="none" class="iq-bg-success mb-1"&gt;
  Notifications&lt;b-badge variant="success" class="ml-2"&gt;4&lt;/b-badge&gt;
&lt;/b-button&gt;
&lt;b-button variant="none" class="iq-bg-danger mb-1"&gt;
  Notifications&lt;b-badge variant="danger" class="ml-2"&gt;4&lt;/b-badge&gt;
&lt;/b-button&gt;
</code></pre>
                </kbd>
              </div>
            </b-collapse>
            <b-button variant="none" class="iq-bg-primary mb-1 mr-1">
              Notifications <b-badge variant="primary" class="ml-2">
                4
              </b-badge>
            </b-button>
            <b-button variant="none" class="iq-bg-success mb-1 mr-1">
              Notifications<b-badge variant="success" class="ml-2">
                4
              </b-badge>
            </b-button>
            <b-button variant="none" class="iq-bg-danger mb-1 mr-1">
              Notifications<b-badge variant="danger" class="ml-2">
                4
              </b-badge>
            </b-button>
          </template>
        </iq-card>
      </b-col>
      <b-col lg="6" sm="12">
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">
              Contextual variations
            </h4>
          </template>
          <template v-slot:headerAction>
            <a v-b-toggle.collapse-5 class="text-primary float-right" role="button">
              <i class="ri-code-s-slash-line" />
            </a>
          </template>
          <template v-slot:body>
            <p>Add any of the below mentioned modifier classes to change the appearance of a badge.</p>
            <b-collapse id="collapse-5" class="mb-2">
              <div class="card">
                <kbd class="bg-dark">
                  <pre id="contextual-variations" class="text-white">
                    <code>
&lt;b-badge variant="primary"&gt;Primary&lt;/b-badge&gt;
&lt;b-badge variant="secondary"&gt;Secondary&lt;/b-badge&gt;
&lt;b-badge variant="success"&gt;Success&lt;/b-badge&gt;
&lt;b-badge variant="danger"&gt;Danger&lt;/b-badge&gt;
&lt;b-badge variant="warning"&gt;Warning&lt;/b-badge&gt;
&lt;b-badge variant="info"&gt;Info&lt;/b-badge&gt;
&lt;b-badge variant="light"&gt;Light&lt;/b-badge&gt;
&lt;b-badge variant="dark"&gt;Dark&lt;/b-badge&gt;

&lt;h5 class="card-title mt-4"&gt;Pill badges&lt;/h5&gt;
&lt;p&gt;Use the &lt;code&gt;.badge-pill&lt;/code&gt; modifier class to make badges more rounded (with a larger &lt;code&gt;border-radius&lt;/code&gt; and additional horizontal &lt;code&gt;padding&lt;/code&gt;). Useful if you miss the badges from v3.&lt;/p&gt;

&lt;b-badge pill variant="primary"&gt;Primary&lt;/b-badge&gt;
&lt;b-badge pill variant="secondary"&gt;Secondary&lt;/b-badge&gt;
&lt;b-badge pill variant="success"&gt;Success&lt;/b-badge&gt;
&lt;b-badge pill variant="danger"&gt;Danger&lt;/b-badge&gt;
&lt;b-badge pill variant="warning"&gt;Warning&lt;/b-badge&gt;
&lt;b-badge pill variant="info"&gt;Info&lt;/b-badge&gt;
&lt;b-badge pill variant="light"&gt;Light&lt;/b-badge&gt;
&lt;b-badge pill variant="dark"&gt;Dark&lt;/b-badge&gt;

&lt;h5 class="card-title mt-4"&gt;Links&lt;/h5&gt;
&lt;p&gt;Using the contextual &lt;code&gt;.badge-*&lt;/code&gt; classes on an &lt;code&gt;&amp;lt;a&amp;gt;&lt;/code&gt; element quickly provide &lt;em&gt;actionable&lt;/em&gt; badges with hover and focus states.&lt;/p&gt;

&lt;b-badge href="#" variant="primary"&gt;Primary&lt;/b-badge&gt;
&lt;b-badge href="#" variant="secondary"&gt;Secondary&lt;/b-badge&gt;
&lt;b-badge href="#" variant="success"&gt;Success&lt;/b-badge&gt;
&lt;b-badge href="#" variant="danger"&gt;Danger&lt;/b-badge&gt;
&lt;b-badge href="#" variant="warning"&gt;Warning&lt;/b-badge&gt;
&lt;b-badge href="#" variant="info"&gt;Info&lt;/b-badge&gt;
&lt;b-badge href="#" variant="light"&gt;Light&lt;/b-badge&gt;
&lt;b-badge href="#" variant="dark"&gt;Dark&lt;/b-badge&gt;
</code></pre>
                </kbd>
              </div>
            </b-collapse>
            <b-badge variant="primary" class="mr-1">
              Primary
            </b-badge>
            <b-badge variant="secondary" class="mr-1">
              Secondary
            </b-badge>
            <b-badge variant="success" class="mr-1">
              Success
            </b-badge>
            <b-badge variant="danger" class="mr-1">
              Danger
            </b-badge>
            <b-badge variant="warning" class="mr-1">
              Warning
            </b-badge>
            <b-badge variant="info" class="mr-1">
              Info
            </b-badge>
            <b-badge variant="light" class="mr-1">
              Light
            </b-badge>
            <b-badge variant="dark" class="mr-1">
              Dark
            </b-badge>
            <h5 class="card-title mt-4">
              Pill badges
            </h5>
            <p>Use the <code>.badge-pill</code> modifier class to make badges more rounded (with a larger <code>border-radius</code> and additional horizontal <code>padding</code>). Useful if you miss the badges from v3.</p>
            <b-badge pill variant="primary" class="mr-1">
              Primary
            </b-badge>
            <b-badge pill variant="secondary" class="mr-1">
              Secondary
            </b-badge>
            <b-badge pill variant="success" class="mr-1">
              Success
            </b-badge>
            <b-badge pill variant="danger" class="mr-1">
              Danger
            </b-badge>
            <b-badge pill variant="warning" class="mr-1">
              Warning
            </b-badge>
            <b-badge pill variant="info" class="mr-1">
              Info
            </b-badge>
            <b-badge pill variant="light" class="mr-1">
              Light
            </b-badge>
            <b-badge pill variant="dark" class="mr-1">
              Dark
            </b-badge>
            <h5 class="card-title mt-4">
              Links
            </h5>
            <p>Using the contextual <code>.badge-*</code> classes on an <code>&lt;a&gt;</code> element quickly provide <em>actionable</em> badges with hover and focus states.</p>
            <b-badge href="#" variant="primary" class="mr-1">
              Primary
            </b-badge>
            <b-badge href="#" variant="secondary" class="mr-1">
              Secondary
            </b-badge>
            <b-badge href="#" variant="success" class="mr-1">
              Success
            </b-badge>
            <b-badge href="#" variant="danger" class="mr-1">
              Danger
            </b-badge>
            <b-badge href="#" variant="warning" class="mr-1">
              Warning
            </b-badge>
            <b-badge href="#" variant="info" class="mr-1">
              Info
            </b-badge>
            <b-badge href="#" variant="light" class="mr-1">
              Light
            </b-badge>
            <b-badge href="#" variant="dark" class="mr-1">
              Dark
            </b-badge>
          </template>
        </iq-card>
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">
              Contextual variations Border
            </h4>
          </template>
          <template v-slot:headerAction>
            <a v-b-toggle.collapse-6 class="text-primary float-right" role="button">
              <i class="ri-code-s-slash-line" />
            </a>
          </template>
          <template v-slot:body>
            <p>Add any of the below mentioned modifier classes to change the appearance of a badge.</p>
            <b-collapse id="collapse-6" class="mb-2">
              <div class="card">
                <kbd class="bg-dark">
                  <pre id="contextual-variations-border" class="text-white">
                    <code>
&lt;b-badge class="border border-primary text-primary" variant="none"&gt;Primary&lt;/b-badge&gt;
&lt;b-badge class="border border-secondary text-secondary" variant="none"&gt;Secondary&lt;/b-badge&gt;
&lt;b-badge class="border border-success text-success" variant="none"&gt;Success&lt;/b-badge&gt;
&lt;b-badge class="border border-danger text-danger" variant="none"&gt;Danger&lt;/b-badge&gt;
&lt;b-badge class="border border-warning text-warning" variant="none"&gt;Warning&lt;/b-badge&gt;
&lt;b-badge class="border border-info text-info" variant="none"&gt;Info&lt;/b-badge&gt;
&lt;b-badge class="border border-light text-light" variant="none"&gt;Light&lt;/b-badge&gt;
&lt;b-badge class="border border-dark text-dark" variant="none"&gt;Dark&lt;/b-badge&gt;

&lt;h5 class="card-title mt-4"&gt;Pill badges&lt;/h5&gt;
&lt;p&gt;Use the &lt;code&gt;.badge-pill&lt;/code&gt; modifier class to make badges more rounded (with a larger &lt;code&gt;border-radius&lt;/code&gt; and additional horizontal &lt;code&gt;padding&lt;/code&gt;). Useful if you miss the badges from v3.&lt;/p&gt;
&lt;b-badge class="border border-primary text-primary" pill variant="none"&gt;Primary&lt;/b-badge&gt;
&lt;b-badge class="border border-secondary text-secondary" pill variant="none"&gt;Secondary&lt;/b-badge&gt;
&lt;b-badge class="border border-success text-success" pill variant="none"&gt;Success&lt;/b-badge&gt;
&lt;b-badge class="border border-danger text-danger" pill variant="none"&gt;Danger&lt;/b-badge&gt;
&lt;b-badge class="border border-warning text-warning" pill variant="none"&gt;Warning&lt;/b-badge&gt;
&lt;b-badge class="border border-info text-info" pill variant="none"&gt;Info&lt;/b-badge&gt;
&lt;b-badge class="border border-light text-light" pill variant="none"&gt;Light&lt;/b-badge&gt;
&lt;b-badge class="border border-dark text-dark" pill variant="none"&gt;Dark&lt;/b-badge&gt;

&lt;h5 class="card-title mt-4"&gt;Links&lt;/h5&gt;
&lt;p&gt;Using the contextual &lt;code&gt;.badge-*&lt;/code&gt; classes on an &lt;code&gt;&amp;lt;a&amp;gt;&lt;/code&gt; element quickly provide &lt;em&gt;actionable&lt;/em&gt; badges with hover and focus states.&lt;/p&gt;
&lt;b-badge href="#" class="border border-primary text-primary" variant="none"&gt;Primary&lt;/b-badge&gt;
&lt;b-badge href="#" class="border border-secondary text-secondary" variant="none"&gt;Secondary&lt;/b-badge&gt;
&lt;b-badge href="#" class="border border-success text-success" variant="none"&gt;Success&lt;/b-badge&gt;
&lt;b-badge href="#" class="border border-danger text-danger" variant="none"&gt;Danger&lt;/b-badge&gt;
&lt;b-badge href="#" class="border border-warning text-warning" variant="none"&gt;Warning&lt;/b-badge&gt;
&lt;b-badge href="#" class="border border-info text-info" variant="none"&gt;Info&lt;/b-badge&gt;
&lt;b-badge href="#" class="border border-light text-light" variant="none"&gt;Light&lt;/b-badge&gt;
&lt;b-badge href="#" class="border border-dark text-dark" variant="none"&gt;Dark&lt;/b-badge&gt;
</code></pre>
                </kbd>
              </div>
            </b-collapse>
            <b-badge class="border border-primary text-primary mr-1" variant="none">
              Primary
            </b-badge>
            <b-badge class="border border-secondary text-secondary mr-1" variant="none">
              Secondary
            </b-badge>
            <b-badge class="border border-success text-success mr-1" variant="none">
              Success
            </b-badge>
            <b-badge class="border border-danger text-danger mr-1" variant="none">
              Danger
            </b-badge>
            <b-badge class="border border-warning text-warning mr-1" variant="none">
              Warning
            </b-badge>
            <b-badge class="border border-info text-info mr-1" variant="none">
              Info
            </b-badge>
            <b-badge class="border border-light text-light mr-1" variant="none">
              Light
            </b-badge>
            <b-badge class="border border-dark text-dark mr-1" variant="none">
              Dark
            </b-badge>
            <h5 class="card-title mt-4">
              Pill badges
            </h5>
            <p>Use the <code>.badge-pill</code> modifier class to make badges more rounded (with a larger <code>border-radius</code> and additional horizontal <code>padding</code>). Useful if you miss the badges from v3.</p>
            <b-badge class="border border-primary text-primary mr-1" pill variant="none">
              Primary
            </b-badge>
            <b-badge class="border border-secondary text-secondary mr-1" pill variant="none">
              Secondary
            </b-badge>
            <b-badge class="border border-success text-success mr-1" pill variant="none">
              Success
            </b-badge>
            <b-badge class="border border-danger text-danger mr-1" pill variant="none">
              Danger
            </b-badge>
            <b-badge class="border border-warning text-warning mr-1" pill variant="none">
              Warning
            </b-badge>
            <b-badge class="border border-info text-info mr-1" pill variant="none">
              Info
            </b-badge>
            <b-badge class="border border-light text-light mr-1" pill variant="none">
              Light
            </b-badge>
            <b-badge class="border border-dark text-dark mr-1" pill variant="none">
              Dark
            </b-badge>
            <h5 class="card-title mt-4">
              Links
            </h5>
            <p>Using the contextual <code>.badge-*</code> classes on an <code>&lt;a&gt;</code> element quickly provide <em>actionable</em> badges with hover and focus states.</p>
            <b-badge href="#" class="border border-primary text-primary mr-1" variant="none">
              Primary
            </b-badge>
            <b-badge href="#" class="border border-secondary text-secondary mr-1" variant="none">
              Secondary
            </b-badge>
            <b-badge href="#" class="border border-success text-success mr-1" variant="none">
              Success
            </b-badge>
            <b-badge href="#" class="border border-danger text-danger mr-1" variant="none">
              Danger
            </b-badge>
            <b-badge href="#" class="border border-warning text-warning mr-1" variant="none">
              Warning
            </b-badge>
            <b-badge href="#" class="border border-info text-info mr-1" variant="none">
              Info
            </b-badge>
            <b-badge href="#" class="border border-light text-light mr-1" variant="none">
              Light
            </b-badge>
            <b-badge href="#" class="border border-dark text-dark mr-1" variant="none">
              Dark
            </b-badge>
          </template>
        </iq-card>
      </b-col>
    </b-row>
  </b-container>
</template>
<script>
import { core } from '../../../assets/app/app'

export default {
  layout: 'BackendLayout',
  name: 'UiBadges',
  mounted () {
    core.index()
  }
}
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v4/code-react/dashboard/src/views/backend/ui/UiBadges.js
import React,{ useState } from 'react'
import { Container, Row, Col, Badge, Collapse, Button} from 'react-bootstrap'
import { Link } from 'react-router-dom'
import  Card from '../../../components/Card'

const UiBadges = () =>{

    //Collapse state
    const[open,setOpen]=useState(false)
    const[open1,setOpen1]=useState(false)
    const[open2,setOpen2]=useState(false)
    const[open3,setOpen3]=useState(false)
    const[open4,setOpen4]=useState(false)
    const[open5,setOpen5]=useState(false)
    
    return(
        <>
            <Container fluid >
                <Row>
                    <Container fluid>
                        <Row>
                            <Col sm="12" lg="6">
                                <Card>
                                    <Card.Header>
                                        <Card.Header.Title>
                                            <h4 className="card-title">Badge</h4>
                                        </Card.Header.Title>
                                        <Card.Header.Action>
                                            <i type="button" onClick={() =>setOpen(!open)}>
                                                <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                                                </svg>
                                            </i>
                                        </Card.Header.Action>
                                    </Card.Header>
                                    <Card.Body>
                                        <Collapse in={open}>
                                            <div>
                                                <Card>
                                                    <kbd className="bg-dark"><pre className="text-white"><code>
{`<h1 className="mt-2">Example heading <Badge variant="primary">New</Badge></h1>
                                                `}
                                                    </code></pre></kbd>
                                                </Card>
                                            </div>
                                        </Collapse>
                                        <p>Badges scale to match the size of the immediate parent element by using relative font sizing and <code>em</code> units.</p>
                                        <h1 className="mt-2">Example heading <Badge variant="primary">New</Badge></h1>
                                        <h2 className="mt-2">Example heading <Badge variant="secondary">New</Badge></h2>
                                        <h3 className="mt-2">Example heading <Badge variant="success">New</Badge></h3>
                                        <h4 className="mt-2">Example heading <Badge variant="danger">New</Badge></h4>
                                        <h5 className="mt-2">Example heading <Badge variant="warning">New</Badge></h5>
                                        <h6 className="mb-0">Example heading <Badge variant="info">New</Badge></h6>
                                    </Card.Body>
                                </Card>
                                <Card>
                                    <Card.Header>
                                        <Card.Header.Title>
                                            <h4 className="card-title">Button Badges</h4>
                                        </Card.Header.Title>
                                        <Card.Header.Action>
                                                <i type="button" onClick={() =>setOpen1(!open1)}>
                                                    <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                                                    </svg>
                                                </i>
                                        </Card.Header.Action>
                                    </Card.Header>
                                    <Card.Body>
                                        <Collapse in={open1}>
                                            <div>
                                                <Card>
                                                    <kbd className="bg-dark"><pre className="text-white"><code>
{`<Button  variant="primary mb-1 mr-2" >
    Notifications <Badge variant="light ml-2">4</Badge>
</Button>
                                            `}
                                                    </code></pre></kbd>
                                                </Card>
                                            </div>
                                        </Collapse>
                                        <p>Badges can be used as part of buttons to provide a counter.</p>
                                        <Button  variant="primary mb-1 mr-2" >
                                            Notifications <Badge variant="light ml-2">4</Badge>
                                        </Button>
                                        <Button  variant="success mb-1 mr-2">
                                            Notifications <Badge variant="light ml-2">4</Badge>
                                        </Button>
                                        <Button variant="danger mb-1 mr-2">
                                            Notifications <Badge variant="light ml-2">4</Badge>
                                        </Button>
                                    </Card.Body>
                                </Card>
                                <Card>
                                    <Card.Header>
                                        <Card.Header.Title>
                                            <h4 className="card-title">Button Light background Badges</h4>
                                        </Card.Header.Title>
                                        <Card.Header.Action>
                                                <i type="button"  onClick={() =>setOpen2(!open2)}>
                                                    <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                                                    </svg>
                                                </i>
                                        </Card.Header.Action>
                                    </Card.Header>
                                    <Card.Body>
                                        <Collapse in={open2}>
                                            <div>
                                                <Card>
                                                    <kbd className="bg-dark"><pre className="text-white"><code>
{`<Button variant="outline-primary  mb-1 mr-2">
    Notifications <Badge variant="primary ml-2">4</Badge>
</Button>
                                                `}
                                                    </code></pre></kbd>
                                                </Card>
                                            </div>
                                        </Collapse>
                                        <p>Badges can be used as part of buttons to provide a counter.</p>
                                        <Button variant="outline-primary  mb-1 mr-2">
                                            Notifications <Badge variant="primary ml-2">4</Badge>
                                        </Button>
                                        <Button variant="outline-success mb-1 mr-2">
                                            Notifications <Badge variant="success ml-2">4</Badge>
                                        </Button>
                                        <Button variant="outline-danger mb-1 mr-2">
                                            Notifications <Badge variant="danger ml-2">4</Badge>
                                        </Button>
                                    </Card.Body>
                                </Card>
                                <Card>
                                    <Card.Header>
                                        <Card.Header.Title>
                                            <h4 className="card-title">Button Border Badges</h4>
                                        </Card.Header.Title>
                                        <Card.Header.Action>
                                            <i type="button" onClick={() =>setOpen3(!open3)}>
                                                <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                                                </svg>
                                            </i>
                                        </Card.Header.Action>
                                    </Card.Header>
                                    <Card.Body>
                                        <Collapse in={open3}>
                                            <div>
                                                <Card>
                                                    <kbd className="bg-dark"><pre className="text-white"><code>
{`<Button  variant=" bg-primary-light mb-1 mr-2">
    Notifications <Badge variant="primary ml-2">4</Badge>
</Button>
                                                `}
                                                    </code></pre></kbd>
                                                </Card>
                                            </div>
                                        </Collapse>
                                        <p>Badges can be used as part of buttons to provide a counter.</p>
                                        <Button  variant=" bg-primary-light mb-1 mr-2">
                                            Notifications <Badge variant="primary ml-2">4</Badge>
                                        </Button>
                                        <Button  variant=" bg-success-light mb-1 mr-2">
                                            Notifications <Badge variant="success ml-2">4</Badge>
                                        </Button>
                                        <Button  variant=" bg-danger-light mb-1 mr-2">
                                            Notifications <Badge variant="danger ml-2">4</Badge>
                                        </Button>
                                    </Card.Body>
                                </Card>
                            </Col>
                            <Col sm="12" lg="6">
                                <Card>
                                    <Card.Header>
                                        <Card.Header.Title>
                                            <h4 className="card-title">Contextual variations</h4>
                                        </Card.Header.Title>
                                        <Card.Header.Action>
                                            <i type="button" onClick={() =>setOpen4(!open4)}>
                                                <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                                                </svg>
                                            </i>
                                        </Card.Header.Action>
                                    </Card.Header>
                                    <Card.Body>
                                        <Collapse in={open4}>
                                            <div>
                                                <Card>
                                                    <kbd className="bg-dark"><pre className="text-white"><code>
{`<Badge variant="primary mt-2 mr-1">Primary</Badge>
<Badge pill variant="primary mt-2 mr-1">Primary</Badge>
<Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge badge-primary mr-1">Primary</Link>
                                            `}
                                                    </code></pre></kbd>
                                                </Card>
                                            </div>
                                        </Collapse>
                                        <p className="mb-2">Add any of the below mentioned modifier classes to change the appearance of a badge.</p>
                                        <Badge variant="primary mt-2 mr-1">Primary</Badge>
                                        <Badge variant="secondary mt-2 mr-1">Secondary</Badge>
                                        <Badge variant="success mt-2 mr-1">Success</Badge>
                                        <Badge variant="danger mt-2 mr-1">Danger</Badge>
                                        <Badge variant="warning mt-2 mr-1">Warning</Badge>
                                        <Badge variant="info mt-2 mr-1">Info</Badge>
                                        <Badge variant="light mt-2 mr-1">Light</Badge>
                                        <Badge variant="dark mt-2 mr-1">Dark</Badge>
                                        <h5 className="card-title mt-4">Pill badges</h5>
                                        <p className="mb-2">Use the <code>.badge-pill</code> modifier class to make badges more rounded (with a larger <code>border-radius</code> and additional horizontal <code>padding</code>). Useful if you miss the badges from v3.</p>
                                        <Badge pill variant="primary mt-2 mr-1">Primary</Badge>
                                        <Badge pill variant="secondary mt-2 mr-1">Secondary</Badge>
                                        <Badge pill variant="success mt-2 mr-1">Success</Badge>
                                        <Badge pill variant="danger mt-2 mr-1">Danger</Badge>
                                        <Badge pill variant="warning mt-2 mr-1">Warning</Badge>
                                        <Badge pill variant="info mt-2 mr-1">Info</Badge>
                                        <Badge pill variant="light mt-2 mr-1">Light</Badge>
                                        <Badge pill variant="dark mt-2 mr-1">Dark</Badge>
                                        <h5 className="card-title mt-4">Links</h5>
                                        <p className="mb-2">Using the contextual <code>.badge-*</code> classes on an <code>&lt;a&gt;</code> element quickly provide <em>actionable</em> badges with hover and focus states.</p>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge badge-primary mr-1">Primary</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge badge-secondary mr-1">Secondary</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge badge-success mr-1">Success</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge badge-danger mr-1">Danger</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge badge-warning mr-1">Warning</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge badge-info mr-1">Info</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge badge-light mr-1">Light</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge badge-dark mr-1">Dark</Link>
                                    </Card.Body>
                                </Card>
                                <Card>
                                    <Card.Header>
                                        <Card.Header.Title>
                                        <h4 className="card-title">Contextual variations Border</h4>
                                        </Card.Header.Title>
                                        <Card.Header.Action>
                                            <i type="button" onClick={() =>setOpen5(!open5)}>
                                                <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                                                </svg>
                                            </i>
                                        </Card.Header.Action>
                                    </Card.Header>
                                    <Card.Body>
                                        <Collapse in={open5}>
                                            <div>
                                                <Card>
                                                    <kbd className="bg-dark"><pre className="text-white"><code>
{`<Badge variant=" border border-primary text-primary mt-2 mr-1">Primary</Badge>
<Badge pill variant=" mt-2 mr-1 border border-primary text-primary">Primary</Badge>
<Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge border border-primary text-primary mr-1">Primary</Link>
                                            `}  
                                                    </code></pre></kbd>
                                                </Card>
                                            </div>
                                        </Collapse>
                                        <p className="mb-2">Add any of the below mentioned modifier classes to change the appearance of a badge.</p>
                                        <Badge variant=" border border-primary text-primary mt-2 mr-1">Primary</Badge>
                                        <Badge variant=" border border-secondary text-secondary mt-2 mr-1">Secondary</Badge>
                                        <Badge variant=" border border-success text-success mt-2 mr-1">Success</Badge>
                                        <Badge variant=" border border-danger text-danger mt-2 mr-1">Danger</Badge>
                                        <Badge variant=" border border-warning text-warning mt-2 mr-1">Warning</Badge>
                                        <Badge variant=" border border-info text-info mt-2 mr-1">Info</Badge>
                                        <Badge variant=" border border-light text-light mt-2 mr-1">Light</Badge>
                                        <Badge variant=" border border-dark text-dark mt-2 mr-1">Dark</Badge>
                                        <h5 className="card-title mt-4">Pill badges</h5>
                                        <p className="mb-2">Use the <code>.badge-pill</code> modifier class to make badges more rounded (with a larger <code>border-radius</code> and additional horizontal <code>padding</code>). Useful if you miss the badges from v3.</p>
                                        <Badge pill variant=" mt-2 mr-1 border border-primary text-primary">Primary</Badge>
                                        <Badge pill variant=" mt-2 mr-1 border border-secondary text-secondary">Secondary</Badge>
                                        <Badge pill variant=" mt-2 mr-1 border border-success text-success">Success</Badge>
                                        <Badge pill variant=" mt-2 mr-1 border border-danger text-danger">Danger</Badge>
                                        <Badge pill variant=" mt-2 mr-1 border border-warning text-warning">Warning</Badge>
                                        <Badge pill variant=" mt-2 mr-1 border border-info text-info">Info</Badge>
                                        <Badge pill variant=" mt-2 mr-1 border border-light text-light">Light</Badge>
                                        <Badge pill variant=" mt-2 mr-1 border border-dark text-dark">Dark</Badge>
                                        <h5 className="card-title mt-4">Links</h5>
                                        <p className="mb-2">Using the contextual <code>.badge-*</code> classes on an <code>&lt;a&gt;</code> element quickly provide <em>actionable</em> badges with hover and focus states.</p>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge border border-primary text-primary mr-1">Primary</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge border border-secondary text-secondary mr-1">Secondary</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge border border-success text-success  mr-1">Success</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge border border-danger text-danger mr-1">Danger</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge border border-warning text-warning mr-1">Warning</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge border border-info text-info mr-1">Info</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge border border-light text-light mr-1">Light</Link>
                                        <Link to="/"  onClick={e => e.preventDefault()} className="mt-2 badge border border-dark text-dark mr-1">Dark</Link>
                                    </Card.Body>
                                </Card>
                            </Col>  
                        </Row>
                    </Container>
                </Row>
            </Container>
        </>
    )
}

export default UiBadges;
