// ops/1-assets/2-app-templates/all/movies-prod/v5/vue/frontend/src/components/merchandise/ProductCard.vue
<template>
  <div class="product-block">
    <span v-if="props.isSale == true" class="onsale bg-primary"> {{ $t('shop.sale!') }}! </span>

    <span v-else-if="props.isNew == true" class="onsale bg-primary">{{ $t('shop.new') }}! </span>
    <div class="image-wrap">
      <router-link :to="{ name: 'landing-page.merchandise.shop.detail' }">
        <div class="product-image">
          <img :src="props.thumbnail" class="img-fluid" alt="" loading="lazy" />
        </div>
      </router-link>

      <div class="buttons-holder">
        <ul class="list-unstyled m-0 p-0">
          <li>
            <router-link class-name="sq-btn" to="#"><i class="fa fa-eye"></i></router-link>
          </li>
          <li>
            <div class="on-first-load">
              <div class="add-button">
                <router-link to="#" class-name="add_to_wishlist">
                  <i class="fa-solid fa-heart" aria-hidden="true"></i>
                </router-link>
              </div>
            </div>
          </li>
          <li>
            <router-link to="#" class-name="added_to_cart d-flex align-items-center">
              <i class="fa-solid fa-basket-shopping"></i>
            </router-link>
          </li>
        </ul>
      </div>
    </div>
    <div class="product-caption">
      <h5 class="product__title">
        <router-link :to="{ name: 'landing-page.merchandise.shop.detail' }" class-name="css_prefix-product-title-link"> {{ $t(props.productName) }}</router-link>
      </h5>
      <div class="price-detail">
        <span class="price"
          ><del>{{ props.price }}</del
          >{{ props.finalPrice }}</span
        >
      </div>
      <div class="lh-1 ratting">
        <span>
          <i class="fa fa-star text-warning" aria-hidden="true"></i>
        </span>
        <span>
          <i class="fa fa-star text-warning" aria-hidden="true"></i>
        </span>
        <span>
          <i class="fa fa-star text-warning" aria-hidden="true"></i>
        </span>
        <span>
          <i class="fa fa-star text-warning" aria-hidden="true"></i>
        </span>
        <span>
          <i class="fa fa-star-half text-warning" aria-hidden="true"></i>
        </span>
      </div>
    </div>
  </div>
</template>
<script setup>
// import { newProduct } from '../../../StaticData/shop';
const props = defineProps({
  thumbnail: { type: String, default: '' },
  productName: { type: String, default: '' },
  slug: { type: String, default: '' },
  isSale: { type: [String, Boolean], default: true },
  isNew: { type: [String, Boolean], default: true },
  price: { type: String, default: '' },
  finalPrice: { type: String, default: '' },
  // ratting:{type:String, default: ''},
});
</script>

// ops/1-assets/1-app-templates/vue/movies-prod/v5/react/frontend/src/components/merchandise/product-card.jsx
import { memo, useState } from "react";
import { Link } from "react-router-dom";

//components
import RatingStar from "../rating-star";
import ProductModal from "./ProductModal";

//sweetalert2
import Swal from "sweetalert2";
import "sweetalert2/src/sweetalert2.scss";

// the hook
import { useTranslation } from "react-i18next";

const ProductCard = memo((props) => {
  const { t } = useTranslation();
  const showSwal = () => {
    Swal.fire({
      title: `${t("sweetalert.added")}`,
      text: `${t("sweetalert.added_to_wishlist")}`,
      icon: "success",
      confirmButtonText: `${t("sweetalert.ok_btn")}`,
      background: "#141314",
      color: "#ffffff",
    });
  };
  const cartSwal = () => {
    Swal.fire({
      title: `${t("sweetalert.added")}`,
      text: `${t("sweetalert.added_to_cart")}`,
      icon: "success",
      confirmButtonText: `${t("sweetalert.ok_btn")}`,
      background: "#141314",
      color: "#ffffff",
    });
  };

  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  const isSale = props.is_sale;
  const isNew = props.is_new;
  return (
    <>
      <div className="product-block">
        {isSale ? (
          <span className="onsale bg-primary">{t("shop.sale!")}</span>
        ) : isNew ? (
          <span className="onsale bg-primary">{t("shop.new!")}</span>
        ) : (
          ""
        )}

        <div className="image-wrap">
          <Link to="/product-detail">
            <div className="product-image">
              <img
                src={props.thumbnail}
                className="img-fluid w-100"
                alt=""
                loading="lazy"
              />
            </div>
          </Link>
          <div className="buttons-holder">
            <ul className="list-unstyled m-0 p-0">
              <li>
                <Link className="sq-btn" to="#" onClick={handleShow}>
                  <i className="fa fa-eye"></i>
                </Link>
              </li>
              <li>
                <div className="on-first-load">
                  <div className="add-button">
                    <Link to="#" className="add_to_wishlist" onClick={showSwal}>
                      <i className="fa fa-heart" aria-hidden="true"></i>
                    </Link>
                  </div>
                </div>
              </li>
              <li>
                <Link
                  to="#"
                  className="added_to_cart d-flex align-items-center "
                  onClick={cartSwal}
                >
                  <i className="fa-solid fa-basket-shopping"></i>
                </Link>
              </li>
            </ul>
          </div>
        </div>
        <div className="product-caption">
          <h5 className="product__title">
            <Link to="/product-detail" className="title-link">
              {props.product_name}
            </Link>
          </h5>
          <div className="price-detail">
            <span className="price">
              <del>{props.price}</del>
              {props.final_price}
            </span>
          </div>
          <div className="container-rating">
            <div className="star-rating text-primary">
              <RatingStar
                count={props.rating}
                count1={props.count1}
                starColor="text-warning"
              />
            </div>
          </div>
        </div>
      </div>

      <ProductModal show={show} handleClose={handleClose} />
    </>
  );
});

ProductCard.displayName = "ProductCard";
export default ProductCard;
