// ops/1-assets/2-app-templates/all/movies-prod/v5/vue/frontend/src/components/sections/BestOfInternationalShows.vue
<template>
  <!-- Best Of International Shows start -->
  <SectionSlider :title="$t(title)" :list="latestMovie" :slides-per-view="6" class="recommended-block section-top-spacing streamit-block" margin-padding="px-3 my-4">
    <template #headerLink>
      <router-link :to="{ name: 'landing-page.view-all' }" class="text-primary iq-view-all text-decoration-none flex-none">{{ $t('ott_home.view_all') }}</router-link>
    </template>
    <template #default="{ data }">
      <card-style :image="data.image" :title="$t(data.title)" :movie-time="data.movieTime" :watchlist-link="{ path: '/playlist' }" :link="{ path: '/movies-detail' }"></card-style>
    </template>
  </SectionSlider>
  <!-- Best Of International Shows end -->
</template>

<script setup>
import { ref } from 'vue';
import SectionSlider from '../slider/SectionSlider.vue';
import CardStyle from '../cards/CardStyle.vue';
import { latestMovie } from '../../StaticData/data';
const title = ref('form.international_shows');
</script>

// ops/1-assets/1-templates/vue/movies-prod/v5/react/frontend/src/components/sections/BestOfInternationalShows.jsx
import { useState, Fragment, memo } from "react";

//components
import SectionSlider from "../slider/SectionSlider";
import CardStyle from "../cards/CardStyle";

//static data
import { latestMovie } from "../../StaticData/data";

// the hook
import { useTranslation } from "react-i18next";

const BestOfInternationalShows = memo((props) => {
  const { t } = useTranslation();

  return (
    <Fragment>
      <SectionSlider
        title={t("form.international_shows")}
        list={latestMovie}
        className="recommended-block section-top-spacing streamit-block"
        slideMedium={props.slideMedium}
        paddingY={props.paddingY}
      // loop={true}
      >
        {(data) => (
          <CardStyle
            image={data.image}
            title={data.title}
            movieTime={data.movieTime}
            watchlistLink="/playlist"
            link="/movies-detail"
          />
        )}
      </SectionSlider>
    </Fragment>
  );
});

BestOfInternationalShows.displayName = "BestOfInternationalShows";
export default BestOfInternationalShows;
