// ops/1-assets/1-app-templates/react/movies-prod/v5/react/frontend/src/components/Loader.jsx
import { Fragment, memo } from "react";

// img
import LoaderGif from '/assets/images/loader.gif'

const Loader = memo(() => {
  return (
    <Fragment>
      <div className="loader simple-loader animate__animated">
        <div className="loader-body">
          <img
            src={LoaderGif}
            alt="loader"
            className="img-fluid"
            width="300"
          />
        </div>
      </div>
    </Fragment>
  );
});

Loader.displayName = "Loader";
export default Loader;

// ops/1-assets/1-app-templates/all/movies-prod/v5/vue/dashboard/src/components/custom/loader/LoaderComponent.vue
<template>
  <div id="loading">
    <div :class="`loader simple-loader ${!show ? 'd-none' : ''}`">
      <div class="loader-body">
        <img src="/assets/loader.gif" alt="loader" class="image-loader img-fluid" />
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    show: {
      type: Boolean,
      default: false,
    },
  },
};
</script>

<style lang="scss" scoped></style>
