// start/8-workspace/saitou/5-vue/1-vue3/6-ref-reactive/app1/src/components/Counter.vue
<template>
  <div>
    <h1>Counter</h1>
    <p>Count: {{ count }}</p>
    <button @click="plus">+</button>
    <button @click="minus">-</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)

const plus = () => {
  count.value = count.value + 1
}
const minus = () => {
  count.value = count.value - 1
}
</script>

<style scoped>
</style>

// bootcamp/5-workspace/9-du-hj/6-react/2-중급/1-props/app1/src/Counter.js
import React from 'react'

// export default function Counter({count, setCount}) {
export default function Counter({count, setCount}) {
    // const [count, setCount] = useState(0)

    const onIncrease = () => { setCount(count + 1) }
    const onDecrease = () => { setCount(count - 1) }

    return (
        <>
            <div>{count}</div>
            <button onClick={onIncrease}>+</button> 
            <button onClick={onDecrease}>-</button>
        </>
    )
}
