// frontend/6-vue/3-vue3(composition-api)/1-vue-syntax/3-vue-syntax(중급)/3-customHooks/3-utils/2-useInputUtil/app1/src/views/Counter.vue
<template>
  <h1>Counter App</h1>
  <div>
    <h2>카운트: {{ count }}</h2>
    <button @click="increase">+</button>
    <button @click="decrease">-</button>
  </div>
</template>

<script setup>
import { useCounter } from '@/composables/useCounter'

const { count, increase, decrease } = useCounter()
</script>

// bootcamp/5-workspace/9-du-hj/6-react/2-중급/1-props/app1/src/Counter.js
import React from 'react'

// export default function Counter({count, setCount}) {
export default function Counter({count, setCount}) {
    // const [count, setCount] = useState(0)

    const onIncrease = () => { setCount(count + 1) }
    const onDecrease = () => { setCount(count - 1) }

    return (
        <>
            <div>{count}</div>
            <button onClick={onIncrease}>+</button> 
            <button onClick={onDecrease}>-</button>
        </>
    )
}
