// ops/1-assets/2-app-templates/all/movies-prod/v5/react/dashboard/src/components/setting/sections/menu-style.jsx
import {memo,Fragment}from 'react'
import CheckboxBtn from '../elements/checkbox-btn'


const MenuStyle = memo((props) => {
    return (
        <Fragment>
            <h5 className="mt-4 mb-3">Menu Style</h5>
            <div className="d-grid gap-3 grid-cols-3 mb-4">
                <CheckboxBtn btnName="sidebar_type" className="text-center"  imgComponent={true} label="Mini"  labelclassName="overflow-hidden" id="sidebar-mini" defaultChecked={props.sidebarType} value="sidebar-mini" >
                    Mini
                </CheckboxBtn>
                <CheckboxBtn btnName="sidebar_type" className="text-center"  imgComponent={true} label="Hover"  labelclassName="overflow-hidden" id="sidebar-hover" defaultChecked={props.sidebarType} value="sidebar-hover" >
                    Hover
                </CheckboxBtn>
                <CheckboxBtn btnName="sidebar_type" className="text-center"  imgComponent={true} label="soft"  labelclassName="overflow-hidden" id="sidebar-soft" defaultChecked={props.sidebarType} value="sidebar-soft" >
                    Soft
                </CheckboxBtn>
                
            </div>
        </Fragment>
    )
}
)

MenuStyle.displayName="MenuStyle"
export default MenuStyle

// ops/1-assets/1-templates/vue/movies-prod/v5/vue/dashboard/src/components/setting/sections/MenuStyle.vue
<template>
  <div>
    <h5 class="mt-4 mb-3">Menu Style</h5>
    <div class="d-grid gap-3 grid-cols-3 mb-4">
      <checkbox-input
id="sidebar-mini" btn-name="sidebar_type" :img-component="true" label-title="Mini"
        :default-checked="menuStyle" value="sidebar-mini" @on-change="store.sidebar_type">
        Mini
      </checkbox-input>
      <checkbox-input
id="sidebar-hover" btn-name="sidebar_type" :img-component="true" label-title="Hover"
        :default-checked="menuStyle" value="sidebar-hover" @on-change="store.sidebar_type"> Hover </checkbox-input>
      <checkbox-input
id="sidebar-soft" btn-name="sidebar_type" :img-component="true" label-title="Hover"
        :default-checked="menuStyle" value="sidebar-soft" @on-change="store.sidebar_type"> Soft </checkbox-input>
    </div>
  </div>
</template>
<script setup>
import { computed } from 'vue';
import { useSetting } from '@/store/pinia';
import CheckboxInput from '../../custom/elements/CheckboxInput.vue';
// import _ from 'lodash';
const store = useSetting();
const menuStyle = computed(() => store.sidebar_type_value)

</script>
