// ops/1-assets/1-app-templates/all/movies-prod/v5/vue/frontend/src/components/cards/PersonalityCard.vue
<template>
  <img :src="image" alt="personality" class="img-fluid object-cover mb-4 rounded" loading="lazy" />
  <div class="text-center">
    <h6 class="mb-0">
      <router-link :to="link" class="font-size-14 text-decoration-none cast-title text-capitalize">{{ $t(title)
      }}</router-link>
    </h6>
    <router-link :to="categoryLink" class="font-size-14 text-decoration-none text-capitalize text-body">{{ $t(category)
    }}</router-link>
  </div>
</template>

<script setup>
defineProps({
  title: { type: String, default: '' },
  category: { type: String, default: '' },
  categoryLink: {
    type: [String, Object],
    default: () => '/',
  },
  link: {
    type: [String, Object],
    default: () => '/',
  },
  image: { type: String, default: '' },
});
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/components/cards/PersonalityCard.jsx
import { Fragment, memo } from "react";

//react-router-dom
import { Link } from "react-router-dom";

const PersonalityCard = memo((props) => {
  return (
    <Fragment>
      <img
        src={props.image}
        alt="personality"
        className="img-fluid object-cover mb-4 rounded"
      />
      <div className="text-center">
        <h6 className="mb-0">
          <Link
            to={props.link}
            className="font-size-14 text-decoration-none cast-title text-capitalize"
          >
            {props.title}
          </Link>
        </h6>
        <Link
          to={props.categoryLink}
          className="font-size-14 text-decoration-none text-capitalize text-body"
        >
          {props.category}
        </Link>
      </div>
    </Fragment>
  );
});

PersonalityCard.displayName = "PersonalityCard";
export default PersonalityCard;
