// ops/1-assets/1-app-templates/vue/movies-prod/v5/nuxt-js/components/cards/TagsCard.vue
<template>
  <nuxt-link :to="{ name: 'view-all' }" class="iq-tag-box">
    <span class="iq-tag">
      {{ props.title }}
    </span>
  </nuxt-link>
</template>
<script setup>
const props = defineProps({
  title: { type: String, default: "" },
  slug: { type: String, default: "" },
  type: { type: String, default: "" },
});

// params: { filter: 'tags', slug: props.slug, type: props.type }
</script>

// ops/1-assets/2-app-templates/all/movies-prod/v5/react/frontend/src/components/cards/TagsCard.jsx
import React, { Fragment, memo } from "react";

// react-router-dom
import { Link } from "react-router-dom";

const TagsCard = memo((props) => {
  return (
    <Fragment>
      <Link to="/view-all" className="iq-tag-box">
        <span className="iq-tag">{props.title}</span>
      </Link>
    </Fragment>
  );
});

TagsCard.displayName = "TagsCard";
export default TagsCard;
