// ops/1-assets/1-app-templates/react/movies-prod/v4/code-react/dashboard/src/views/backend/pages/blankpage.js
import React from 'react'
import { Container, Row, Col, Card } from 'react-bootstrap'

const BlankPage = () => {
   return (
      <>
         <Container fluid>
            <Row>
               <Col lg="12">
                  <Card>
                     <Card.Body>
                        Here Add Your HTML Content.....
                     </Card.Body>
                  </Card>
               </Col>
            </Row>
         </Container>
      </>
   )
}

export default BlankPage;

// ops/1-assets/1-app-templates/react/movies-prod/v4/code-vue/src/views/Pages/BlankPage.vue
<template>
  <b-container fluid>
      <b-row class="row">
        <b-col lg="12">
            <div class="iq-card">
              <div class="iq-card-body">
                  Add Your Content Here.....
              </div>
            </div>
        </b-col>
      </b-row>
  </b-container>
</template>
<script>
import { core } from '../../config/pluginInit'

export default {
  name: 'BlankPage',
  mounted () {
    core.index()
  }
}
</script>
